filecoin-project/venus

- commands/main.go
> Improve error message when client fails to contact non-running daemon

- tools/faucet/main.go
this PR changes the default limit time of the faucet to 1 hour.
> change faucet default to 1 hour

- .gitmodules
resolves: https://github.com/filecoin-project/go-filecoin/issues/1958
after merging this run a `git submodule sync`
> change submodule url scheme

- README.md
> doc: add `jq` ad dependency

- metrics/heartbeat.go
Logs once as a warning immediately on failure, then at error every 10 minutes.
Closes #1906
> Suppress repeated error log when hearbeat fails to connect.

- Dockerfile
- Dockerfile.faucet
- Dockerfile.genesis
use golang v1.11.2 in `Dockerfile`s
> #1989 use golang v1.11.2 in Dockerfiles

- api/impl/mpool.go
- node/block.go
- node/node.go
- node/node_test.go
- plumbing/api.go
- plumbing/ps/publisher.go
- plumbing/ps/subscriber.go
> Move pubsub to plumbing and remove from Node interface/object.

- scripts/install-rust-proofs.sh
Related to https://github.com/filecoin-project/go-filecoin/issues/2003.
> rust: stop install script if anything fails

- commands/swarm.go
Resolves https://github.com/filecoin-project/go-filecoin/issues/1733
> fix: swarm findpeer is not variadic

- protocol/storage/miner.go
Resolves https://github.com/filecoin-project/go-filecoin/issues/1618
> fix: don't leak error messages on seal fail

- commands/ping.go
> feat: change ping short flag from -n to -c

- commands/ping.go
> fix: ping is not variadic

- mining/block_generate.go
- mining/mqueue.go
- mining/mqueue_test.go
Messages are ordered by decreasing gas price subject to per-address nonces strictly
increasing.
Closes #1751.
> Implement a priority queue for messages to be mined.

- chain/default_store_test.go
- mining/worker.go
- types/block.go
- types/block_test.go
- types/tipset_test.go
improves chain validation part of sync time by a lot.
> cache block cids for faster everything

- commands/chain.go
Requested in https://github.com/filecoin-project/go-filecoin/pull/1831#discussion_r254941104
> Remove redundant sort of tipset blocks in chain head command.

- node/node.go
> Check for context canceled in handleSubscription

- CODEWALK.md
Also normalise quotes to "dumb quotes", more likely to be used consistently in the future.
cc @laser but your review not required.
> Add sector builder and proofs to CODEWALK.

- actor/actor.go
- actor/builtin/account/account.go
- api/impl/actor.go
- consensus/processor.go
- consensus/processor_test.go
- consensus/validation.go
- plumbing/mthdsig/getter.go
- vm/context.go
As requested by @acruikshank in https://github.com/filecoin-project/go-filecoin/pull/2193/files#r263439985
> Add Actor.IsEmpty() and account.IsAccount(actor) methods

- wallet/wallet.go
- wallet/wallet_test.go
Fixes https://github.com/filecoin-project/go-filecoin/issues/2012
> wallet: sort Addresses

- node/node.go
- protocol/storage/client.go
- protocol/storage/client_test.go
See https://github.com/filecoin-project/go-filecoin/issues/2035
> client: Check connection to miner before proposing storage deal

- commands/message_daemon_test.go
- consensus/processor.go
- consensus/processor_test.go
- consensus/validation.go
- consensus/validation_test.go
Also adds tests for the validator 🎉 
Closes #1934.
> Message validator checks value is non-negative and gas limit is below block limit

- commands/miner.go
> Fix units for miner set-price

- commands/message.go
> Fix units for value in message send

- commands/address_daemon_test.go
- commands/main.go
- commands/message_daemon_test.go
- commands/miner_daemon_test.go
- commands/mpool_daemon_test.go
- commands/payment_channel_daemon_test.go
- functional-tests/faucet_test.go
- functional-tests/lib/helpers.bash
- testhelpers/commands.go
- testhelpers/iptbtester/genesis.go
- tools/fast/process_action_options.go
- tools/faucet/main.go
- tools/iptb-plugins/filecoin/local/scripts/prepMining.sh
> Rename --price to --gas-price and --limit to --gas-limit

- README.md
uses badges generated from https://github.com/filecoin-project/go-filecoin-badges
badges will be automatically updated from go-filecoin in upcoming PR to ensure versions are always up to date
PR best reviewed by checking out https://github.com/filecoin-project/go-filecoin/blob/e3328384d36ffa98a687c06e091b9bec6e0eda67/README.md
> adds User Devnet and Nightly Devnet release badges

- commands/chain_daemon_test.go
- types/uint64.go
- types/uint64_test.go
> Serialize Uint64 to string in JSON

- core/testing.go
replaces #2305
merge after #2272 
merge before #2297 (that PR will also provide tests for this one)
> test: start block height at 0 when the tipset is empty

- build/main.go
- scripts/install-filecoin-parameters.sh
paramfetch exits with a non-zero status code if any parameters were unable to be fetched.
Closes #2219
> deps: fallback to paramcache if paramfetch fails

- .circleci/config.yml
otherwise it won't execute an important conditional step
noticed before trying deploy test fortunately
> pass missing user_devnet pramater to job

- .circleci/config.yml
no circle job was being triggered on pushing tag testnet-0.1.0
> combine two tag filters in to one regex

- commands/main.go
- commands/message.go
- commands/mpool_daemon_test.go
- commands/outbox.go
- commands/outbox_daemon_test.go
- commands/utils.go
- core/message_queue.go
- node/node.go
- plumbing/api.go
Also adds a handy SilentWriter for writing command output without too much error handling.
Related to #2165 and #2146.
> Add commands for outbox ls and clear.

- scripts/publish-release.sh
> remove an unnecessary bash flag

- commands/dht.go
- net/router.go
- plumbing/api.go
Simply wrap the same subcommand in IPFS as mentioned in #2177
Please check if there is anything that may need changing.
> Add DHT query subcommand to get closest peers

- scripts/publish-release.sh
did not implement warnings on replacing  with  as we use that style in several scripts
also fixes a bug checking `FILECOIN_BINARY_VERSION` environment variable
> update script to mostly conform to shellcheck

- .circleci/config.yml
fix for: https://circleci.com/gh/filecoin-project/go-filecoin/13031#artifacts/containers/0
> fix artifact filename in docker build

- scripts/install-bls-signatures.sh
- scripts/install-rust-fil-proofs.sh
fixes: https://github.com/filecoin-project/go-filecoin/issues/2360
> require rustup when building local rust dependencies

- commands/message.go
- commands/message_daemon_test.go
- plumbing/api.go
- plumbing/msg/waiter.go
> Add message status command unifying outbox, pool and chain.

- protocol/hello/hello.go
- protocol/hello/hello_test.go
enable the commit check during hello for test devnet (not just user devnet)
cherrypick for https://github.com/filecoin-project/go-filecoin-infra/issues/200
closes https://github.com/filecoin-project/go-filecoin/issues/2393
> check commit for test devnet

- protocol/storage/client.go
Right now the context deadline covers file transfer which prevents large files from getting transferred.
See this issue for more details https://github.com/filecoin-project/go-filecoin/issues/2411 and proposed follow up improvements.
Many bug reports have mentioned this, #2210 for example.
> remove context deadline from file transfer

- actor/actor_test.go
- address/address_test.go
- chain/get_ancestors.go
- commands/dag_daemon_test.go
- commands/init_test.go
- commands/miner.go
- commands/miner_daemon_test.go
- consensus/expected_test.go
- consensus/processor_test.go
- core/message_pool_test.go
- mining/worker_test.go
- plumbing/msg/waiter.go
- plumbing/msg/waiter_test.go
- porcelain/miner_test.go
- porcelain/payments.go
- protocol/hello/hello_test.go
- protocol/storage/miner_test.go
- tools/fast/fastutil/line_puller_test.go
- tools/fast/process_stderr_recorder_test.go
- tools/fast/tests/retrieval_test.go
- tools/iptb-plugins/filecoin/docker/dockerfilecoin/plugin.go
- tools/iptb-plugins/filecoin/local/localfilecoin/plugin.go
- types/fixed_point.go
- types/fixed_point_test.go
- types/tipset_test.go
- vm/storage_test.go
Required for https://github.com/filecoin-project/go-filecoin/issues/2207.
There seem to be some issues with daemon tests, but I'm not sure what causes that (also, circle seems dead - https://status.circleci.com/)
>  Fix golangci-lint warnings 

- protocol/hello/hello.go
- Fixing issue #2403
- I have simply edited the text message to suit the one specified in the existing issue.
- First PR! Let me know if I'm missing anything or something with procedure, I have tried to follow everything in the contributing file.
> Clarify error message wording for code version mismatch

- scripts/install-bls-signatures.sh
- scripts/install-rust-fil-proofs.sh
second part of: https://github.com/filecoin-project/go-filecoin/issues/2361
draft pr, pending merging of: https://github.com/filecoin-project/bls-signatures/pull/8
> use precompiled bls-signatures library

- consensus/expected.go
Studying the EC implementation, and have some handy comments, or fix invalid reference.
> Comments & import indicators added

- .circleci/config.yml
Resolves https://github.com/filecoin-project/go-filecoin/issues/2477
> circle: export GO111MODULE in facuet build

- tools/iptb-plugins/filecoin/local/localfilecoin.go
If the data returned from stdout exceeds that of the kernal buffer, reading from stderr will block forever because the stdout buffer will not drain and the command will deadlock waiting on stderr to close. Moving the reading into a go routine allows for the data to be buffered in user-space. This is a temporary fix to enable working with large data until #1701 can be resolved.
> localplugin: Read output in go routines

- networking.md
Very small change closing out #2351
> Add relay service as user of DHT in docs #2351

- net/bootstrap.go
> Use recommended defaults for kad dht bootstrap #1947

- commands/bitswap.go
- commands/bitswap_stats_test.go
- commands/main.go
- node/node.go
- plumbing/api.go
Add bitswap stats command and a corressponding plumbing api.
Closes #2302
> add bitswap stats command, close #2302

- Dockerfile
- Dockerfile.faucet
- Dockerfile.genesis
Should have fixed https://github.com/filecoin-project/go-filecoin/issues/2494
> Using go modules for docker

- gengen/README.md
- gengen/main.go
- Adds README to gengen
- Fixes testing flags in gengen help (#2363)
> gengen: Add README

- proofs/sectorbuilder/rustsectorbuilder.go
Makes incremental progress towards completion of #2492 
A recent change (`0407d8`) landed in rust-fil-proofs master with breaking API changes. This change was to support the go-filecoin side of #2492. The go-filecoin side of that PR is held up pending some infra-related changes. To prevent rust-fil-proofs/go-filecoin integration from blocking, a minimal change to the `get_max_user_bytes_per_staged_sector` CGO call needs to be made.
```
-----------------------------------------------
commit 0407d81f9cee01f123fdf7d01f03237b29cbcbee
Author: Ryan Kowalick <690440+rkowalick@users.noreply.github.com>
Date:   Wed Apr 10 11:51:29 2019 -0400
Change argument to get_max_user_bytes_per_staged_sector (#590)
* Add sector_size function to FFI
* deprecate old sector size method …
```
> replace max bytes C method with max bytes C function

- proofs/sectorbuilder/rustsectorbuilder.go
Broken in 79bba96d9426a1b2ebba62fc12a5dd76c63f1c93
> Fix broken references to old sector store type.

- commands/chain_daemon_test.go
Modify the existing chain head test to run the command with both text
and json encoding. This test also compares the results of the two,
ensuring they both have contain valid cids.
Resolves #2398
> Add a round trip test for chain head

- scripts/build-bundle.sh
> Include paramcache in release bundles

- commands/payment_channel_daemon_test.go
- tools/fast/fastesting/basic.go
- tools/fast/process_action_options.go
- tools/fast/series/get_head_block_height.go
- tools/fast/series/wait_for_block_height.go
~Depends on #2515~ merged.
Previously #2319
> FAST payment channel tests

- commands/message.go
- commands/message_daemon_test.go
> Support decimal FIL amount

- commands/client_daemon_test.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
> Client and Miner Rejects Pieces Over Sector Size

- commands/address_daemon_test.go
- commands/message_daemon_test.go
- commands/miner_daemon_test.go
- commands/mpool_daemon_test.go
- commands/outbox_daemon_test.go
- commands/payment_channel_daemon_test.go
- consensus/processor.go
- consensus/processor_test.go
- consensus/validation.go
- consensus/validation_test.go
- functional-tests/lib/helpers.bash
- mining/worker_test.go
- node/message_propagate_test.go
- node/node.go
- plumbing/msg/waiter_test.go
- protocol/storage/client.go
- protocol/storage/miner.go
- testhelpers/commands.go
- testhelpers/consensus.go
- testhelpers/iptbtester/genesis.go
- tools/faucet/main.go
- types/testing.go
Resolves #2523 
There is also an implied fast follow task to ensure that this requirement is communicated in the wiki.
> Require nonzero gas price

- commands/client_daemon_test.go
- commands/retrieval_client_daemon_test.go
- net/network.go
- net/pinger.go
- node/node.go
- plumbing/api.go
- porcelain/api.go
- porcelain/network.go
- porcelain/network_test.go
- protocol/retrieval/client.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- tools/fast/action_retrieval_client.go
- Wrap the libp2p pingService with a check for self dial
- Abstract pingMiner function into porcelain
- Handle self dial errors as part of pinging storage / retrieval miners
Want to check if this is roughly right before adding in testing cc @anorth
> Return descriptive error message upon self dial

- protocol/hello/hello.go
> Change version mismatch to warning

- commands/protocol.go
- porcelain/api.go
- porcelain/protocol.go
- porcelain/protocol_test.go
> Add sector sizes to protocol parameter output

- core/message_queue.go
- core/message_queue_test.go
> add stat for oldest message in queue

- commands/daemon.go
- commands/init.go
- commands/main.go
- commands/main_daemon_test.go
- config/config.go
- config/config_test.go
- node/node.go
- node/node_test.go
- paths/paths.go
- proofs/sectorbuilder/testing/builder.go
- repo/fsrepo.go
- repo/fsrepo_test.go
- repo/mem.go
- repo/repo.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
- separate repo interface into Repo and SectorRepo
- fsrepo handles repo data at the new <root>/repo path
> WIP Separate sector data from repo

- tools/migration/internal/logger.go
- tools/migration/internal/logger_test.go
- tools/migration/internal/runner.go
- tools/migration/internal/runner_test.go
- tools/migration/main.go
@shannonwells take a look and let me know if this is near to what you had in mind.
(Patterned pretty closely on your spike branch)
> migration logger

- tools/migration/internal/logger.go
- tools/migration/internal/runner.go
- tools/migration/main.go
We want a Printf method on the migration logger for #2708 
Add one!
Resolves #2740
> Added a Printf method to the migration logger

- testhelpers/commands.go
These are littering the temp dir.
> Clean up sector dir when testdaemon exits.

- core/outbox.go
- core/outbox_test.go
- core/policy.go
- core/policy_test.go
- node/node.go
Requested by @acruikshank – is this 👍 from you?
> Move outbound queue policy into Outbox.

- commands/daemon.go
- commands/id_daemon_test.go
- commands/init.go
- repo/fsrepo.go
- repo/fsrepo_test.go
- repo/repo.go
- repo/testing.go
- testhelpers/commands.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
- tools/migration/internal/repo_fs_helpers.go
- tools/migration/internal/repo_fs_helpers_test.go
- tools/migration/internal/runner.go
- tools/migration/internal/runner_buildonly_test.go
- tools/migration/internal/runner_install_test.go
- tools/migration/internal/runner_migrate_test.go
- tools/migration/internal/runner_test.go
- tools/migration/internal/test_helpers.go
- tools/migration/main_test.go
The init command creates a symbolic link to a repo directory.
Updates lots of tests, especially the migration ones which necessarily inspected the filesystem.
> init creates a symlink to actual repo directory.

- go.mod
- go.sum
Should have been in 882fca3142fa108e5002ebafb2974820474f5bd2
Whoever approves this second, please go ahead and land it for me.
> Gomod changes that should have been part of 882fca31

- build/main.go
> Clean gengen fixture data before generation

- .gitignore
- CODEWALK.md
- README.md
- proofs/rustverifier.go
- proofs/sectorbuilder/rustsectorbuilder.go
- proofs/sectorbuilder/transforms.go
- proofs/transforms.go
- scripts/install-rust-fil-proofs.sh
- types/proofs_mode.go
The name of the archive file, header file, and pkg-config file have changed due our reorganizing the rust-fil-proofs repo in preparation for decomposition into multiple Git repos.
Update documentation and installation scripts to point to new assets.
```
-----------------------------------------------
commit 834a08c2ef96dd343ba587a605fdbc31742e0040
Author: Friedel Ziegelmayer <dignifiedquire@users.noreply.github.com>
Date:   Thu Jun 6 22:20:33 2019 +0200
refactor: split code into new crates, to prepare for repo splitting (#687)
* refactor: split code into new crates, to prepare for repo splitting
Ref #682
* fixup: try to make circecli work
* fix version
* try fix cbindgen again
* fixup: typing is hard
* (build): rename to accommodate new layout
Update README and release script to point to …
```
> consume libsector_builder_ffi instead of libfilecoin_proofs

- bin/devnet_start
the devnets have changed repo directory structure. currently if the node gets restarted, the restart check will never evaluate to true
> update repo directory to latest path

- bin/node_restart
the repo directory is a now a sub-directory within /var/local/filecoin
> repo directory update to fix restart bug

- commands/deals_daemon_test.go
After investigating #2960 I found a few things.  First going off a helpful tip from @travisperson there is solid evidence that the nondeterminism is not caused by AttoFil math at all, but rather a race condition in the existing test.  Currently the test assumes that the `commitSector` message gets into the chain and its gas cost is deducted *before* the old balance is recorded for comparison.  Investigating the chain I found that the gas price of `commitSector` is `0.0000000000000002`, exactly the amount missing during flakes.  <details><summary>(Click here for the block json)</summary>
<p>
```json
Block cid=[zDPWYqFCt75CwJyReU4u6f6ZtFcy6umYX7kBkQ1AiRheCR3t2VcH]: {
"miner": "t2udhmwzokf4hq7oe4zj4g3faah7oz4dnbxtxaqoy",
"ticket": "IM8DZo6YyvGMWWawTlnMX/aILVqmmjcWWiSYBtCdwQcGmmQSIONle2+pSzSXb …
```
> remove flake from redeem test

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- This PR changes the proving period to 1000 blocks.
> change proving period to 1000 blocks

- consensus/processor.go
- go.mod
- go.sum
- metrics/timer.go
This PR adds a tag to the apply_message timer in the consensus package. Said tag is used to represent which method a timer is ran over. This is a byproduct of the work being done to profile chain syncing and processing.
Example Prometheus Metrics with tags:
```
filecoin_consensus_apply_message_sum{consensus_keys_message_method="updatePeerID"} 1
filecoin_consensus_apply_message_count{consensus_keys_message_method="updatePeerID"} 1
...
filecoin_consensus_apply_message_sum{consensus_keys_message_method="submitPoSt"} 1
filecoin_consensus_apply_message_count{consensus_keys_message_method="submitPoSt"} 1
...
filecoin_consensus_apply_message_sum{consensus_keys_message_method="createChannel"} 1
filecoin_consensus_apply_message_count{consensus_keys_message_method="createChannel"} 1
``` …
> add tag to apply message timer for message method

- CHANGELOG.md
This is copied from the changelog published to the blog approved by @mishmosh so content and editing should be good.
> Update CHANGELOG.md for 0.3.2 release

- node/node.go
- node/node_test.go
> fix: mining start add get miner actor (#1544)

- mining/worker.go
- mining/worker_test.go
- node/node.go
> One argument for the mining.NewDefaultWorker function (#1830)

- chain/store.go
- chain/store_test.go
- chain/syncer.go
- chain/syncer_integration_test.go
- chain/syncer_test.go
- chain/tip_index.go
- types/tipset_key.go
Fix #3119
Add Serialize func for TipSetKey. It can replace String() if need.
> fix Chain store takes tipset keys (#3119)

- node/node.go
Please rebase and land this for me directly if you're the final ✅ .
> Fix and remove redundant log messages on pubsub failure

- .circleci/config.yml
- .gitmodules
- address/address.go
- address/address_test.go
- bls-signatures/bls.go
- bls-signatures/bls_test.go
- bls-signatures/types.go
- build/main.go
- go.mod
- scripts/install-bls-signatures.sh
This reverts commit 0927b9c3468664a3f0bfe0d00d84f9c049d50248.
See https://github.com/filecoin-project/go-filecoin/pull/3099#issuecomment-517109189
cc @sidke @laser @travisperson
> Revert "switch bls-signatures to go-bls-sigs package (#3099)"

- actor/builtin/miner/miner_test.go
- actor/builtin/storagemarket/storagemarket_test.go
- chain/testing.go
- core/outbox_test.go
- metrics/heartbeat_test.go
- net/fetcher_test.go
- plumbing/dag/dag_test.go
- sampling/chain_randomness_test.go
- testhelpers/mining.go
- types/testing.go
> Delete some block-building test helpers that have been replaced with chain.Builder

- chain/message_store.go
- chain/message_store_test.go
- chain/testing.go
- core/inbox.go
- core/inbox_test.go
- core/policy.go
- core/policy_test.go
- core/testing.go
- mining/worker.go
- mining/worker_test.go
- node/node.go
- plumbing/cst/chain_state.go
- plumbing/msg/testing.go
- plumbing/msg/waiter.go
- plumbing/msg/waiter_test.go
- types/testing_messages.go
> Prep for breaking messages out of blocks

- chain/message_store.go
- chain/syncer.go
- chain/syncer_integration_test.go
- chain/testing.go
- commands/chain.go
- commands/message_daemon_test.go
- commands/schema/filecoin_block.schema.json
- consensus/genesis.go
- consensus/processor_test.go
- core/inbox.go
- core/policy.go
- core/testing.go
- gengen/util/gengen.go
- metrics/heartbeat_test.go
- mining/block_generate.go
- mining/worker_test.go
- net/fetcher.go
- net/graphsync_fetcher.go
- net/graphsync_fetcher_test.go
- node/block_propagate_test.go
- plumbing/cst/chain_state.go
- plumbing/msg/waiter.go
- plumbing/msg/waiter_test.go
- types/block.go
- types/block_test.go
- types/message.go
- types/testing.go
- types/tipset_test.go
Compiles.  Tests are still broken.
> Break messages and receipts out of block header

- .circleci/config.yml
- README.md
- commands/init.go
- commands/main.go
- fixtures/constants.go
- functional-tests/lib/helpers.bash
- protocol/hello/hello.go
- protocol/hello/hello_test.go
- tools/fast/process_options.go
Once this merges we will need to update the wiki for the references there. Should be fairly limited.
> Rename devnet test to devnet staging

- chain/store_test.go
- consensus/expected_test.go
- consensus/validation_test.go
- mining/scheduler_test.go
- net/peer_tracker_test.go
- plumbing/dag/dag_test.go
- plumbing/msg/waiter_test.go
- porcelain/miner_test.go
- protocol/storage/client_test.go
- types/block_test.go
- types/testing.go
- types/testing_test.go
- vm/vm_test.go
> remove SomeCid replace by CidFromString (#3193)

- .circleci/config.yml
- Dockerfile
- README.md
> misc: load git submodules before deps

- chain/get_ancestors_test.go
- chain/store_test.go
- chain/testing.go
- core/inbox_test.go
- core/policy_test.go
- core/testing.go
- net/fetcher.go
- net/graphsync_fetcher.go
- net/graphsync_fetcher_test.go
- sampling/chain_randomness_test.go
- types/message.go
With these changes, I have synced a node to the 0.4.0 staging devnet.
Fixes #3220
> Graphsync fetcher fixed recursive selector to include messages/receipts, verifies their fetch

- commands/client_daemon_test.go
- commands/deals_daemon_test.go
- tools/fast/action_miner_test.go
Source tests from https://circleci.com/build-insights/gh/filecoin-project/go-filecoin/master
Once we close out https://github.com/filecoin-project/go-filecoin/issues/2968 I will come back through and update these tests.
> Skip tests which flake most often due to async mining

- actor/builtin/miner_redeem_test.go
The miner redeem test tests that a miner can redeem a voucher with a verify piece inclusion condition so long as they have the sector and a piece inclusion proof. This test had been written by specifying the bytes of an actual PIP. Something about the way PIPs are generated changed in a recent rust proofs build, and the test will no longer pass once the changes are checked in.
We looked into mocking this test out, but a lot of testing infrastructure would need to be created. It was much simpler to actually seal a sector and use the proof provided by sealing, so changes to proof construction will always be carried over to the test.
Since takes much longer now to accommodate sealing, it is now a functional test.
> update miner redeem test to use real sealing

- net/protocols.go
- net/topics.go
Update pubsub topic / dht names for new release.
Resolves #3221
> Update DHT and topic names for 0.4

- scripts/install-filecoin-parameters.sh
> misc: download parameters only for 1kb sector size

- core/handler.go
- core/handler_integration_test.go
- core/inbox_test.go
- core/message_pool_test.go
- core/outbox_test.go
- core/policy.go
- core/publisher.go
- core/publisher_test.go
- core/testing.go
- node/node.go
This allows demonstration of the bug reported in #3052.
This PR is in two commits. The first is just noise moving out some test support code for reuse.
> Factor a NewHeadHandler from code in Node, add integration tests for message handling.

- chain/store_test.go
- chain/syncer_integration_test.go
This PR removes the last of the ugly store test setup in favor of the new chain builder.
While trying to close out #2222 I found myself making laborious fixes to this code and realizing that it was all scheduled to be erased.  It seemed like as good a time as any to do this.
#2128 was called out in the chain store test comments as tracking cleanup.  I don't think we should close that with this merging because there is some unresolved and healthy discussion there.
> Cleanliness is next to godliness

- chain/syncer_integration_test.go
- commands/chain_daemon_test.go
- commands/schema/filecoin_block.schema.json
- commands/show.go
- commands/show_test.go
- consensus/genesis.go
- core/policy_test.go
- metrics/heartbeat_test.go
- mining/worker_test.go
- plumbing/msg/waiter_test.go
- porcelain/miner_test.go
- protocol/hello/hello_test.go
- testhelpers/chain.go
- testhelpers/consensus.go
- types/block.go
- types/block_test.go
- types/tipset_test.go
> remove nonce field from block header

- net/graphsync_fetcher_test.go
Per @anorth , just the refactors of #3313 first, sans any other changes.
Similar to #3264 but with follow-ups and additional improvements.
> Refactor to Graphsync Mocks

- tools/fast/action_miner_test.go
closes #3236
We have one last skipped test. `TestFilecoin_MinerPower` has some confusing behavior. It creates a genesis node and a miner node, creates a miner and ask and initiates a deal with it. Eventually, running a deal will cause the miner to gain power, but this test wasn't waiting for that. It's asserting that the miner's power is zero.
I removed all the deal creation code and removed the mining starts so the test execution is more deterministic. I also changed the expected power, since it seems to have changed since this test was skipped. I added an assertion that `MinerPower` returns a non-zero numerator for the genesis miner. Then I un-skipped the test.
> simplify and unskip action_miner_test

- chain/syncer.go
- chain/syncer_test.go
> rename exceedsFinalityLimit to indicate trust

- clock/clock.go
- commands/daemon.go
- node/block_propagate_test.go
- node/node.go
- testhelpers/clock.go
This PR modifies the node structure to contain the clock interface and closes #3337
> add clock interface to node

- commands/leb128.go
- commands/leb128_test.go
- commands/main.go
> add leb128 cli

- README.md
- build/main.go
No longer checked by hello protocol.
> Remove use of FILECOIN_OVERRIDE_BUILD_SHA 

- actor/builtin/miner/miner.go
- protocol/storage/prover.go
These are the logs that @ZenGround0 had in 0.5.2. I'm preserving them to master for now, though we may rework the logs later.
> Log PoSt computation and verification parameters

- message/inbox.go
- message/inbox_test.go
- message/policy.go
closes #3508 
When a chain is reorged, we transfer messages mined in the old chain that have not been mined in the new chain to the miner's inbox so these messages don't get lost entirely. Messages are added to the inbox at a particular chain height so that they can eventually be timed out. We currently add reorged messages to the inbox at the same chain height they entered the pool. If the length of the new chain head exceeds the inbox timeout, messages from old chain could be immediately timed out, defeating the purpose of preserving.
Before processing the messages from the old chain, we compute the chain height of the new chain. When we add messages from the old chain to the Inbox we add them at the height of the new chain.
> set chain height of reorged messages to height of new tipset

- CONTRIBUTING.md
> Add @zenground0 to maintainers in CONTRIBUTING

- net/peer_tracker.go
- net/peer_tracker_test.go
- node/node.go
- porcelain/api.go
- protocol/hello/hello.go
- protocol/hello/hello_test.go
- cleanup some unused hello/peertracker code. 
- minor changes based on spec v1.1
> refactor: hello/peertracker cleanup

- internal/pkg/protocol/storage/client.go
- internal/pkg/protocol/storage/miner.go
> refact: rm useless code

- cmd/go-filecoin/ping_daemon_test.go
- internal/app/go-filecoin/internal/submodule/discovery_submodule.go
- internal/app/go-filecoin/internal/submodule/network_submodule.go
- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/app/go-filecoin/node/node.go
> Remove redundant host member.

- internal/pkg/consensus/expected.go
- internal/pkg/consensus/processor.go
- internal/pkg/consensus/processor_test.go
The `ProcessTipsetResponse` contained fields which indicated which messages failed, but these were ignored by callers.
Removed the custom response type in favour of returning a slice of the message results (pass thru from ApplyMessagesEtc) and document the dropping of errors.
I suggest this land before #3622, and that that PR must now handle these errors somehow.
> Remove misleading ProcessTipsetResponse which implied that errors are not ignored.

- cmd/go-filecoin/init.go
The work done in https://github.com/filecoin-project/go-filecoin/pull/3594 creates a car file contaning a chain with genesis block state s.t. a go-filecoin node may be initialized with it e.g. `go-filecoin init --genesisfile=chain.car`.
> init accepts a car file with full chain

- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/chainsync/chainsync.go
- internal/pkg/chainsync/internal/dispatcher/dispatcher.go
- internal/pkg/chainsync/internal/dispatcher/dispatcher_test.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/chainsync/internal/syncer/syncer_integration_test.go
- internal/pkg/chainsync/internal/syncer/syncer_test.go
Prefactor for finality that allows the chain store update to be deferred until a safe chain syncing state.
- Extract out heaviest chain check / head setting
- Add staging field to syncer
Closes issue #3664
> Finality refactor

- internal/pkg/consensus/processor.go
- internal/pkg/vm/internal/exitcode/exitcode.go
- internal/pkg/vm/internal/result/result.go
- internal/pkg/vm/internal/runtime/runtime.go
- internal/pkg/vm/internal/storagemap/storagemap.go
- internal/pkg/vm/internal/vmcontext/actor_state_handle.go
- internal/pkg/vm/internal/vmcontext/actor_state_handle_test.go
- internal/pkg/vm/internal/vmcontext/export_test.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- internal/pkg/vm/testing.go
We need to use the new contracts from #3658
We have options.. lets talk.
> feat: new actor state handle

- internal/pkg/proofs/verification/interface.go
- internal/pkg/vm/actor/builtin/initactor/init.go
- internal/pkg/vm/actor/builtin/miner/miner.go
- internal/pkg/vm/actor/builtin/paymentbroker/paymentbroker.go
- internal/pkg/vm/actor/builtin/power/power.go
- internal/pkg/vm/actor/builtin/storagemarket/storagemarket.go
- internal/pkg/vm/actor/storage.go
- internal/pkg/vm/internal/runtime/runtime.go
- internal/pkg/vm/internal/vmcontext/export.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- internal/pkg/vm/internal/vmcontext/vmcontext_test.go
- internal/pkg/vm/testing.go
Spec changed, we change. 
- using implementer discretion on:
* Send signature
* Grouping of exposed methods
> feat: match latest vm spec PR

- internal/pkg/net/validators.go
message topic pubsub validation
New message topic validator for constructing pubsub validator messages
Closes issue #3558
> Pubsub message validation

- internal/pkg/chainsync/internal/dispatcher/dispatcher.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/chainsync/internal/syncer/syncer_test.go
Soft finality needs to be enforced with a validation rule.
Add in check for departure of more than finality epochs from the current head
Closes issue #3676
> Finality rule

- go.mod
- go.sum
Fixes a bunch of important issues.
> chore(dep): update go-cid, go-multihash, go-ipfs-blockstore

- internal/pkg/vm/actor/actor_encoding_gen.go
- internal/pkg/vm/actor/builtin/initactor/init.go
- internal/pkg/vm/actor/builtin/miner/miner.go
- internal/pkg/vm/actor/builtin/power/power.go
- internal/pkg/vm/actor/builtin/storagemarket/storagemarket.go
- internal/pkg/vm/actor/storage.go
- internal/pkg/vm/actor/testing.go
- internal/pkg/vm/internal/runtime/runtime.go
More cleanup due to new VM runtime.
> feat: remove LegacyStorage method from runtime

- cmd/go-filecoin/actor.go
- internal/pkg/consensus/genesis.go
- internal/pkg/consensus/processor_test.go
- internal/pkg/consensus/validation.go
- internal/pkg/mining/worker_test.go
- internal/pkg/testhelpers/core.go
- internal/pkg/types/constants.go
- internal/pkg/vm/actor/actor.go
- internal/pkg/vm/actor/actor_test.go
- internal/pkg/vm/actor/builtin/account/account.go
- internal/pkg/vm/actor/builtin/default.go
- internal/pkg/vm/actor/builtin/initactor/init.go
- internal/pkg/vm/actor/builtin/miner/miner.go
- internal/pkg/vm/actor/builtin/power/power.go
- internal/pkg/vm/actor/builtin/storagemarket/storagemarket.go
- internal/pkg/vm/actor/storage_test.go
- internal/pkg/vm/internal/pattern/pattern.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/state/cached_tree_test.go
- internal/pkg/vm/state/tree_test.go
- tools/gengen/util/gengen.go
Actor code ID's are now defined in the specs-actors repo.
> feat: use spec actors cid codes

- go.mod
- go.sum
- internal/pkg/types/constants.go
- internal/pkg/vm/actor/actor.go
- internal/pkg/vm/actor/actor_test.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
`IsSingleton` and `IsBuiltin` logic moved to specs-actors.
> refactor: use new actor type functions provided in specs-actors

- internal/app/go-filecoin/storage_miner_connector/connector.go
Implement storage miner node methods: WalletHas, CheckSealing, CheckPieces, GetReplicaCommitmentByID, WaitForReportFaults, SendReportFaults.
There are a handful of stub methods in here, and a hard-coded value for fault durations.
> Basic implementation of additional Storage Miner Node methods

- go.mod
- go.sum
- internal/app/go-filecoin/storage_miner_connector/connector.go
- internal/pkg/consensus/genesis.go
- internal/pkg/vm/internal/runtime/runtime.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
- internal/pkg/vm/internal/vmcontext/syscalls.go
- internal/pkg/vm/testing.go
> feat: hook some of the new syscalls

- internal/pkg/consensus/genesis.go
- internal/pkg/types/message.go
- internal/pkg/types/signed_message.go
- internal/pkg/vm/gas/gas.go
- internal/pkg/vm/internal/gascost/gascost.go
- internal/pkg/vm/internal/runtime/runtime.go
- internal/pkg/vm/internal/storage/storage.go
- internal/pkg/vm/internal/vmcontext/actor_store.go
- internal/pkg/vm/internal/vmcontext/context_store.go
- internal/pkg/vm/internal/vmcontext/gas_tracker.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
- internal/pkg/vm/internal/vmcontext/testing.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- tools/gengen/util/generator.go
Gas accounting changed on the new spec
> feat: add new gas costs

- internal/pkg/vm/internal/gascost/gascost.go
- internal/pkg/vm/internal/gascost/pricelistV0.go
- internal/pkg/vm/internal/vmcontext/actor_store.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/testing.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
Gas prices will undoubtedly changed during the lifetime of the chain. 
We need to be able to apply the correct price at a given point in time.
- have prices list based on the epoch
> feat: gas prices based on epoch

- internal/pkg/vm/internal/vmcontext/actor_state_handle.go
> fix: state handle does not support using different objects

- internal/app/go-filecoin/node/init.go
If the sector dir isn't given in the repo config, the default needs to be resolved.
Resolve it at time of use.
Possibly better long term would be to ensure it gets written into the repo config.
> Fix resolving default sector dir path when importing

- internal/pkg/vm/state/state_test.go
:clinking_glasses: https://github.com/filecoin-project/lotus/pull/1424
> add test to ensure state tree root is consistent and matches lotus

- internal/pkg/vm/internal/runtime/runtime.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
New actor address computation is given by https://github.com/filecoin-project/specs/issues/894
- Use the originator's stable (pubkey) address, not the immediate caller' ID address
- Use a counter of calls to NewActorAddress rather than all VM calls
FYI @arajasek, @whyrusleeping, @frrist 
Closes #3826
> Update NewActorAddress computation.

- internal/pkg/state/sigval.go
- internal/pkg/state/sigval_test.go
- internal/pkg/types/signed_message.go
> Message cid signing

- go.mod
- go.sum
- parameters.json
This PR updates go-filecoin to use a version of libfilecoin that uses v24 groth parameters.
> v24 Groth Parameters

- internal/pkg/vm/internal/vmcontext/testing.go
- internal/pkg/vm/internal/vmcontext/validation_test.go
Also enables return value validation.
> Unskip passing chain validation tests.

- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/state/state.go
https://github.com/filecoin-project/specs-actors/pull/246 introduces a beneficiary for the deleted actor's balance.
This PR does the work to transfer the balance so that subsequent actor upgrade is easy.
> Transfer balance of deleted actor to beneficiary.

- internal/pkg/clock/chainclock.go
See https://github.com/filecoin-project/specs/issues/896
Closes #3913
> Set epoch time to 25 seconds, the interop-net value

- go.mod
- go.sum
- internal/pkg/vm/internal/vmcontext/testing.go
Changes to match the updates that landed in chain-validation around message application return types.
> update chainval: match new applymessage returns

- internal/app/go-filecoin/connectors/retrieval_market/client_test.go
- internal/app/go-filecoin/porcelain/wallet_test.go
- internal/pkg/chain/store_test.go
- internal/pkg/consensus/validation_test.go
- internal/pkg/enccid/enc_cid.go
- internal/pkg/message/handler_integration_test.go
- internal/pkg/message/outbox_test.go
- internal/pkg/mining/worker_test.go
- internal/pkg/vm/actor/actor.go
- internal/pkg/vm/actor/actor_test.go
- internal/pkg/vm/state/state_test.go
- tools/gengen/util/generator.go
Account actors in genesis were wrong, lacking state and Head CIDs
Initialize account actor state in genesis.
FYI @Kubuxu
> Fix undefined account actor head CIDs in genesis

- internal/pkg/vm/internal/vmcontext/vmcontext.go
The system (and other non-account) actor's CallSeqNum should not be incremented.
See https://github.com/filecoin-project/specs/issues/761
ApplyImplicitMessage checks the originator's code type before incrementing nonce.
> Skip CallSeqNum increment for non-account (incl system) actors

- internal/pkg/chainsync/internal/dispatcher/dispatcher.go
> Add debug logs to dispatcher

- cmd/go-filecoin/init.go
- internal/app/go-filecoin/node/init.go
- internal/app/go-filecoin/node/test/builder.go
- internal/app/go-filecoin/plumbing/msg/testing.go
- internal/pkg/chain/init.go
- internal/pkg/genesis/genesis.go
- tools/gengen/util/generator.go
- tools/gengen/util/gengen.go
Remove logically separate things from consensus to embrace data dependency as package dependency.
Closes #3973
> Remove genesis stuff from consensus

- internal/pkg/vm/internal/vmcontext/invocation_context.go
Implements the money supply syscall.
This isn't the right long term implementation, but crafted for short-term Lotus interop pending clean-up work in the reward actor. See #4017.
Match the Lotus implementation.
Closes #3996
> Implement money supply syscall

- go.mod
- go.sum
- internal/pkg/consensus/election.go
Upgrade to first interop-target.
We were only 3 commits behind, so this is easy.
FYI @frrist
> Upgrade to actors v1.0.0

- go.mod
- go.sum
- internal/app/go-filecoin/node/block_propagate_test.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/validation.go
- internal/pkg/types/message.go
- internal/pkg/types/message_test.go
See https://github.com/filecoin-project/specs/pull/915
~The chain validation tests are failing until I update the test expectations with the new message gas costs. I will either do that before landing this, or disable those tests here and restore them later.~
Closes #4033
> Add version field to message

- internal/pkg/vm/internal/vmcontext/invocation_context.go
There's no real reason to charge gas until an actual state change occurs. More context can be found [here](https://filecoinproject.slack.com/archives/CEHHJNJS3/p1588216005182400).
> Only charge gas in CreateActor once we've made a state change

- go.mod
- go.sum
- internal/pkg/vm/state/state.go
- internal/pkg/vm/state/state_test.go
> Update to fixed go-hamt-ipld package

- internal/pkg/drand/drand.go
- internal/pkg/drand/drand_grpc.go
- internal/pkg/drand/testing.go
- internal/pkg/mining/worker.go
Drand service no longer can have gaps.  Removing this assumption simplifies our handling a great deal.
Closes #4053
> Remove gap handling from drand

- go.mod
- go.sum
- internal/app/go-filecoin/connectors/fsm_node/connector.go
- internal/app/go-filecoin/connectors/storage_market/client.go
- internal/app/go-filecoin/connectors/storage_market/common.go
- internal/app/go-filecoin/connectors/storage_market/provider.go
- internal/app/go-filecoin/node/init.go
- internal/pkg/state/view.go
Updating v0.4.0 to match lotus and join interopnet
- Fix state view
- Update chain val
- Fix storage connector to get provider deal ids without using now gone deals by party multimap.
> Fixing state accessors and updating chain val

- internal/pkg/version/protocol_versions.go
We need to define protocol versions for the upcoming testnet phase 2.
> Add protocol version table entry for testnet

- internal/pkg/block/block.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher.go
- internal/pkg/consensus/expected.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/mqueue.go
- internal/pkg/mining/mqueue_test.go
This is a thing Lotus does, and so is needed for painnet interop.
> enforce a message limit on blocks

- cmd/go-filecoin/daemon.go
- fixtures/setup.json
- functional-tests/common.go
- go.mod
- go.sum
- internal/app/go-filecoin/node/block_propagate_test.go
- internal/app/go-filecoin/node/builder.go
- internal/app/go-filecoin/node/message_propagate_test.go
- internal/app/go-filecoin/node/test/setup.go
- internal/pkg/config/config.go
- tools/gengen/util/generator.go
Compatibility with lotus
Update filecoin-ffi, specs-actors and chain-validation
> update specs-actors, ffi, chain-val

- README.md
Update 3 docs URLs in *Usage* section
> Update docs URLs in README

- go.mod
- go.sum
Consume a fix to the market actor.
> Upgrade to actors v0.5.2

- go.mod
- go.sum
Consume fix to verified deals registry.
> Upgrade to actors v0.5.3

- cmd/go-filecoin/init.go
- cmd/go-filecoin/main.go
- fixtures/networks/testnet.go
Might want to fix the devnet testnet. Please take over this PR and make it as you please.
https://ipfs.io/ipfs/QmXZQeezX1x8uRQX9EUaYxnyivUpTfJqQTvszk3c8SnFPN/testnet.car
> Testnet Phase 2 network info

- README.md
- fixtures/networks/testnet.go
> Testnet config default bootstraps automatically

- internal/pkg/vm/actor/builtin/default.go
this is why gfc can't sync to testnet phase 2
with this I get to height 380
> add VerifiedRegistry to default actors

- internal/pkg/vm/internal/vmcontext/invocation_context.go
Avoid clogging the logs while syncing.
> Quiet noisy vm log

- cmd/go-filecoin/address_integration_test.go
- cmd/go-filecoin/chain_integration_test.go
- cmd/go-filecoin/client_daemon_test.go
- cmd/go-filecoin/commands_test.go
- cmd/go-filecoin/message_integration_test.go
- cmd/go-filecoin/miner_daemon_test.go
- cmd/go-filecoin/mining_integration_test.go
- cmd/go-filecoin/mpool_integration_test.go
- cmd/go-filecoin/outbox_integration_test.go
- cmd/go-filecoin/show_test.go
- fixtures/fortest/constants.go
- internal/app/go-filecoin/node/testing.go
Follow up resolution of #3863 to help it stay fixed.
> Move test fixtures to new package to make unintended import of side-effects less likely

- cmd/go-filecoin/daemon.go
The default was not a string so the type-conversion failed.
Closes #4148
> Fix default value of --block-time parameter

- internal/pkg/block/block.go
- internal/pkg/block/block_test.go
To make block_test.go test cases pass. 
The null block test case could not pass due to varint error.
> make block_test work

- README.md
Update the Readme to add IPFS Force as go-filecoin maintainers.
> Update go-filecoin maintainers

- README.md
2 small tweaks - typo fix & name change clarification (go-filecoin to venus)
> typo fix & name clarification

- go.sum
- internal/pkg/chain/car.go
- internal/pkg/chain/testing.go
- internal/pkg/config/testing.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/circulating_supply.go
- internal/pkg/consensus/validation_test.go
- internal/pkg/consensus/weight_test.go
- internal/pkg/discovery/hello_protocol_test.go
- internal/pkg/message/handler_integration_test.go
- internal/pkg/message/inbox_test.go
- internal/pkg/message/outbox_test.go
- internal/pkg/message/policy_test.go
- internal/pkg/message/testing.go
- internal/pkg/metrics/heartbeat_test.go
- internal/pkg/repo/fsrepo.go
- internal/pkg/testhelpers/consensus.go
- internal/pkg/testhelpers/core.go
- internal/pkg/testhelpers/test_daemon.go
> fix test pk

- cmd/go-filecoin/show_test.go
- go.mod
- go.sum
- internal/app/go-filecoin/node/test/builder.go
> fix app test

- internal/pkg/vm/gas/pricelistV0.go
- internal/pkg/vm/internal/vmcontext/actor_store.go
- internal/pkg/vm/internal/vmcontext/gas_charge_ipld.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
- internal/pkg/vm/internal/vmcontext/syscalls.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- internal/pkg/vm/state/state.go
- internal/pkg/vm/state/testing.go
- internal/pkg/vm/storage/storage.go
> fix vm log debug

- README.md
- bin/container_daemon
- cmd/go-filecoin/chain_integration_test.go
- cmd/go-filecoin/daemon_daemon_test.go
- cmd/go-filecoin/import.go
- cmd/go-filecoin/init.go
- cmd/go-filecoin/inspector.go
- cmd/go-filecoin/log.go
- cmd/go-filecoin/protocol_cmd_test.go
- cmd/go-filecoin/swarm.go
- cmd/go-filecoin/version.go
- go.mod
- go.sum
- internal/app/go-filecoin/node/test/api.go
- internal/app/go-filecoin/porcelain/protocol.go
- internal/app/go-filecoin/porcelain/protocol_test.go
- internal/pkg/state/types.go
- scripts/build-bundle.sh
- tools/chain-util/main.go
- tools/fast/bin/localnet/main.go
- tools/fast/series/ctx_sleep_delay.go
- tools/iptb-plugins/filecoin/docker/scripts/prepMining.sh
- tools/iptb-plugins/filecoin/local/localfilecoin.go
- tools/iptb-plugins/filecoin/local/scripts/prepMining.sh
- tools/iptb-plugins/filecoin/mock/mockfilecoin.go
> fix cmd test & change go-filecoin to venus

- app/node/builder.go
- app/submodule/chain_submodule.go
- cmd/daemon.go
- cmd/import.go
- cmd/init.go
- cmd/main.go
- pkg/chain/init.go
- pkg/chain/store.go
- pkg/chain/store_test.go
- pkg/chain/testing.go
- pkg/chainsync/internal/syncer/syncer_integration_test.go
- pkg/conformance/driver.go
support check point to start a node
> init add importfile option & check point cache

- pkg/consensus/expected.go
> fix winner check

- .circleci/config.yml
> fix mac build

- pkg/chain/message_store.go
> fix msg seq in tipset

- cmd/main.go
- pkg/message/outbox.go
> fix send transfer message

- cmd/init.go
> set default network

- cmd/daemon.go
- cmd/init.go
- cmd/main.go
> add import snapshot

- pkg/vm/state/state.go
> fix ApplyMessage error: actor not found handling

- app/node/builder.go
- cmd/init.go
- fixtures/networks/calibration.go
- pkg/chain/message_store.go
- pkg/config/config.go
- pkg/consensus/expected.go
- pkg/constants/shared_vals.go
- pkg/fork/fork.go
- pkg/version/protocol_versions.go
- pkg/vm/dispatch/dispatch.go
- pkg/vm/vmcontext/invocation_context.go
- pkg/vm/vmcontext/vmcontext.go
> calibration network

- pkg/chainsync/internal/syncer/syncer.go
> fix slice index out

- app/node/builder.go
- fixtures/networks/integrationtestnet.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- fixtures/networks/testnet.go
- main.go
- pkg/chain/store_test.go
- pkg/chainsync/internal/dispatcher/dispatcher.go
- pkg/chainsync/internal/syncer/syncer.go
- pkg/vm/vmcontext/vmcontext.go
- pkg/vm/vmcontext/vmdebugger.go
> fix exceed internal msg gaslimit

- pkg/chain/chain_index.go
- pkg/chain/store.go
> opt tipset cache key

- pkg/util/blockstoreutil/buf_bstore.go
- pkg/vm/vmcontext/vmcontext.go
> opt copyblock

- app/submodule/mpool/mpool_api.go
- app/submodule/mpool/mpool_submodule.go
- cmd/main.go
- cmd/message.go
- cmd/mpool.go
- pkg/consensus/call_invoke.go
- pkg/messagepool/messagepool.go
- pkg/types/cbor_gen.go
> fix debug:send message

- app/client/client.go
- app/submodule/chain/actor_api.go
- app/submodule/chain/miner_api.go
- pkg/specactors/builtin/power/power.go
- pkg/state/view.go
> add miner state functions

- app/submodule/mpool/mpool_api.go
- cmd/mpool.go
- pkg/messagepool/messagepool.go
> mpool delete by address

- app/node/node.go
- app/node/test/builder.go
- cmd/daemon_daemon_test.go
- cmd/main_daemon_test.go
- pkg/testhelpers/test_daemon.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
- tools/iptb-plugins/filecoin/util.go
> fix port commit

- cmd/main.go
- cmd/state.go
- cmd/utils.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/constants/shared_vals.go
> add state command

- cmd/chain.go
- cmd/chain_integration_test.go
> optimize chain print

- pkg/consensus/processor.go
- pkg/vm/vmcontext/interpreter.go
- pkg/vm/vmcontext/vmcontext.go
- tools/conformance/driver.go
> fix panic when daemon exit

- cmd/address.go
- cmd/address_integration_test.go
- pkg/crypto/keyinfo.go
- tools/conformance/driver.go
> fix keyinfo marshal

- cmd/mpool.go
- pkg/messagepool/gas.go
- pkg/messagepool/messagepool.go
> fix bug: null pointer at gas & mpool replace error

- README.md
- cmd/main.go
- fixtures/networks/calibration.go
> fix readme

- README.md
> fix version and daemon command

- pkg/chain/store_test.go
> fix test revert change ,fetch new head if receive old chain head

- app/submodule/syncer/syncer_api.go
- app/submodule/syncer/syncer_submodule.go
- cmd/chain.go
- cmd/main.go
- cmd/sync.go
- pkg/chain/store.go
- pkg/chainsync/chainsync.go
- pkg/chainsync/dispatcher/dispatcher.go
- pkg/chainsync/dispatcher/dispatcher_test.go
- pkg/chainsync/syncer/syncer.go
- pkg/chainsync/syncer/syncer_integration_test.go
- pkg/chainsync/syncer/syncer_test.go
- pkg/chainsync/types/syncstate.go
- pkg/chainsync/types/target_tracker.go
- pkg/consensus/chain_selector.go
- pkg/discovery/hello_protocol.go
- pkg/slashing/monitor.go
> fix expand base

- app/node/node.go
- app/submodule/chain/api_types.go
- app/submodule/chain/chaininfo_api.go
- app/submodule/mpool/mpool_submodule.go
- cmd/chain.go
- go.mod
- go.sum
- pkg/chain/store.go
- pkg/chainsync/syncer/syncer.go
- pkg/messagepool/messagepool.go
> subscribe msg after sync completed

- app/node/builder.go
- cmd/address.go
- cmd/address_integration_test.go
- cmd/utils.go
- fixtures/networks/calibration.go
- fixtures/networks/integrationtestnet.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- fixtures/networks/testnet.go
- pkg/chainsync/dispatcher/dispatcher.go
- pkg/config/config.go
> fix wallet address display

- pkg/consensus/call_invoke.go
- pkg/consensus/expected.go
- pkg/consensus/processor.go
> fix GasLimit estimate

- cmd/message.go
- pkg/wallet/dsbackend.go
> fix send command

- app/submodule/paych/paych_api.go
- app/submodule/syncer/api_types.go
- pkg/chain/waiter.go
> redefine paych type as api types

- cmd/address.go
> fix password input

- app/submodule/wallet/wallet_api.go
- cmd/address.go
- pkg/messagepool/messagepool_test.go
- pkg/wallet/backend.go
- pkg/wallet/dsbackend.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
> fix wallet command and hash wallet password

- cmd/address.go
- pkg/chainsync/types/target_tracker.go
- pkg/wallet/backend.go
- pkg/wallet/dsbackend.go
- pkg/wallet/passphrase.go
- pkg/wallet/passphrase_test.go
- pkg/wallet/wallet.go
> change password type []byte

- cmd/chain.go
- cmd/chain_integration_test.go
> simplify chainls output

- pkg/consensus/call_invoke.go
> call with process implicit message

- app/node/test/node.go
- app/submodule/wallet/wallet_api.go
- cmd/address.go
- cmd/address_integration_test.go
- pkg/wallet/dsbackend.go
- pkg/wallet/dsbackend_test.go
- pkg/wallet/passphrase_test.go
- pkg/wallet/signature_test.go
- pkg/wallet/wallet.go
> fix lock and unlock command

- cmd/chain.go
- cmd/chain_integration_test.go
> fix chainlist err

- .gitmodules
- app/submodule/mining/mining_api.go
- cmd/address_integration_test.go
- cmd/daemon.go
- go.mod
- go.sum
- pkg/crypto/sigs/bls/bls_bench_test.go
- pkg/crypto/sigs/bls/init.go
- pkg/crypto/sigs/sigs.go
- pkg/types/block.go
- pkg/types/block_test.go
> rm fil blst package

- cmd/daemon.go
- pkg/consensus/block_validator.go
- pkg/constants/version.go
- pkg/fork/fork.go
> fix sync err for upgrade-v3

- app/submodule/network/network_api.go
- pkg/constants/version.go
> fix NodeType

- app/submodule/mpool/mpool_api.go
> refact(mpool): fill msg raw data into msgMeta extra

- app/client/client.go
- app/submodule/mpool/mpool_api.go
- pkg/fork/fork.go
- pkg/messagepool/selection.go
> fix(ffi): ffi version

- Makefile
- app/submodule/chain/chain_submodule.go
- app/submodule/network/network_api.go
- cmd/daemon.go
- fixtures/networks/calibration.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- fixtures/networks/testnet.go
- pkg/config/config.go
- pkg/constants/network.go
- pkg/constants/version.go
- pkg/fork/fork.go
- tools/conformance/driver.go
> fix network type

- app/submodule/chain/chaininfo_api.go
- app/submodule/mpool/mpool_api.go
- app/submodule/wallet/wallet_api.go
- cmd/address.go
- cmd/miner.go
- pkg/wallet/backend.go
- pkg/wallet/dsbackend.go
- pkg/wallet/wallet.go
> fix wallet lock

- app/node/test/builder.go
- cmd/message.go
- pkg/chainsync/types/target_tracker.go
- pkg/config/config.go
- pkg/config/config_test.go
- tools/iptb-plugins/filecoin/docker/dockerfilecoin.go
> modify the default libp2p swarm address

- pkg/messagepool/selection.go
> fix bug for mpool msgs select

- app/submodule/network/network_submodule.go
- fixtures/networks/calibration.go
- fixtures/networks/mainnet.go
- fixtures/networks/nerpanet.go
- fixtures/networks/testnet.go
- pkg/config/config.go
> add devnet default config for network name

- app/node/builder.go
- app/submodule/wallet/wallet_api.go
- app/submodule/wallet/wallet_submodule.go
- cmd/address.go
- cmd/daemon.go
- cmd/main.go
- cmd/miner.go
- pkg/market/fundmanager_test.go
- pkg/messagepool/messagepool_test.go
- pkg/wallet/dsbackend.go
- pkg/wallet/dsbackend_test.go
- pkg/wallet/passphrase_test.go
- pkg/wallet/signature_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
> support setting wallet password at startup

- cmd/daemon.go
- pkg/migration/migrate.go
- pkg/repo/fsrepo.go
- pkg/repo/fsrepo_test.go
- pkg/repo/mem.go
- pkg/repo/repo.go
> migrate data version

- go.mod
- go.sum
> fix(auth): venus auth package upgrade

- go.sum
> rm filblst

- pkg/net/msgsub/validator.go
> fix msgsub logger

- app/submodule/mining/mining_api.go
> does not sign when no wallet

- app/submodule/wallet/remotewallet/remote.go
- app/submodule/wallet/wallet_api.go
- app/submodule/wallet/wallet_submodule.go
- pkg/messagepool/messagepool_test.go
- pkg/messagepool/selection_test.go
- pkg/state/signer.go
- pkg/wallet/wallet.go
> refact: wallet api replace if else to interface

- app/submodule/syncer/syncer_submodule.go
- pkg/chainsync/slashfilter/mysqldb.go
- pkg/chainsync/slashfilter/slashfilter.go
- pkg/config/config.go
> refactor mysql slashfilter

- Makefile
> fix illegal instruction

- pkg/types/message.go
> opt default maxfee:0

- pkg/vm/dispatch/dispatch.go
> fix upgrade actor v4 bug

- app/client/client.go
- app/submodule/mpool/mpool_api.go
> add estimate gaslimit api

- go.sum
> fix: go.sum flatbuffers from goproxy cn

- pkg/messagepool/messagepool.go
> disable local message environment

- app/submodule/apitypes/chain.go
- app/submodule/chain/miner_api.go
- cmd/chain.go
- cmd/dispute.go
> add chain disputer cmd: for wdPoSt disputer

- pkg/chainsync/exchange/client.go
- pkg/chainsync/syncer/syncer.go
> check message length

- app/node/inspector_api_test.go
- pkg/config/config.go
- pkg/market/fundmanager_test.go
- pkg/repo/mem.go
- pkg/wallet/dsbackend_test.go
- pkg/wallet/passphrase_test.go
- pkg/wallet/signature_test.go
- pkg/wallet/wallet_test.go
> update scrypt N parameter

- app/submodule/apiface/wallet.go
- app/submodule/wallet/wallet_api.go
- cmd/address.go
- pkg/wallet/backend.go
- pkg/wallet/dsbackend.go
- pkg/wallet/wallet.go
> lock wallet not require password

- app/submodule/apiface/wallet.go
- app/submodule/wallet/wallet_api.go
- cmd/address.go
- cmd/message.go
- pkg/chainsync/syncer/syncer.go
- pkg/wallet/backend.go
- pkg/wallet/dsbackend.go
- pkg/wallet/passphrase.go
- pkg/wallet/wallet.go
> fix misleading names

- app/node/node.go
- app/submodule/network/libp2p.go
- cmd/version_daemon_test.go
- pkg/metrics/export.go
> remove deprecated packages

- app/submodule/network/network_submodule.go
> remove the blankValidator from the DHT initialization

- cmd/daemon.go
> Clean the repo that failed to initialize

- app/node/config.go
- app/node/init.go
- pkg/fskeystore/fskeystore.go
- pkg/fskeystore/fskeystore_test.go
- pkg/fskeystore/keystore.go
- pkg/fskeystore/memkeystore.go
- pkg/fskeystore/memkeystore_test.go
- pkg/fskeystore/sync.go
- pkg/jwtauth/local_jwt.go
- pkg/repo/fsrepo.go
- pkg/repo/mem.go
- pkg/repo/repo.go
- pkg/types/keystore.go
> use 32 random bytes as HMAC JSON web token secret

- app/client/client_gen.go
- app/submodule/apiface/mpool.go
- app/submodule/mpool/mpool_api.go
- app/submodule/network/network_submodule.go
- fixtures/networks/calibration.go
- fixtures/networks/nerpanet.go
- pkg/chainsync/exchange/client.go
- pkg/messagepool/gas.go
- pkg/types/message.go
> batch estimate message gas

- app/client/client_gen.go
- app/submodule/apiface/wallet.go
- app/submodule/network/network_submodule.go
- fixtures/networks/calibration.go
- pkg/chainsync/exchange/client.go
> export wallet balance interface

- pkg/config/config.go
- pkg/messagepool/gas.go
> fix over estimate

- README.md
Browsing the README.md to get acquainted and noticed a minor spelling issue. 
Fixed spelling of the word _components_.
> tiny little spelling error

- app/submodule/mpool/mpool_api.go
- app/submodule/mpool/mpool_submodule.go
- pkg/messagepool/gas.go
- pkg/messagepool/messagepool.go
- pkg/messagepool/messagepool_test.go
- pkg/messagepool/provider.go
- pkg/messagepool/pruning.go
- pkg/messagepool/repub.go
- pkg/messagepool/repub_test.go
- pkg/messagepool/selection.go
- pkg/messagepool/selection_test.go
- pkg/messagesigner/messagesigner.go
- pkg/messagesigner/messagesigner_test.go
- pkg/types/storage.go
> upgrade to actor-v5

- app/submodule/apiface/multisig.go
- app/submodule/apiface/paych.go
> add api comment

- go.mod
- go.sum
- pkg/messagepool/messagepool.go
> upgrade ffi and go-paramfetch

- app/submodule/chain/chaininfo_api.go
> fix beacon randomness

- pkg/chain/message_store.go
- pkg/messagepool/gas.go
> fix gas estimate

- app/submodule/mpool/mpool_api.go
- pkg/chain/circulating_supply.go
- pkg/consensus/call_invoke.go
- pkg/consensus/expected.go
- pkg/consensus/processor.go
- pkg/messagepool/gas.go
> fix bug for batch msg estimate

- app/node/builder.go
- app/node/test/node.go
- app/submodule/chain/chain_submodule.go
- app/submodule/syncer/syncer_submodule.go
- pkg/consensus/expected.go
- pkg/consensus/processor.go
- pkg/crypto/bls/init.go
- pkg/crypto/secp/init.go
- pkg/crypto/sigs.go
- pkg/gen/genesis/genesis.go
- pkg/gen/genesis/miners.go
- pkg/messagepool/messagepool_test.go
- pkg/messagepool/selection_test.go
- pkg/state/sigval.go
- pkg/state/sigval_test.go
- pkg/state/view.go
- pkg/util/ffiwrapper/impl/config.go
- pkg/util/ffiwrapper/impl/partialfile.go
- pkg/util/ffiwrapper/impl/sealer.go
- pkg/util/ffiwrapper/impl/sealer_cgo.go
- pkg/util/ffiwrapper/impl/testing.go
- pkg/util/ffiwrapper/impl/types.go
- pkg/util/ffiwrapper/impl/unseal_ranges.go
- pkg/util/ffiwrapper/impl/verifier_cgo.go
- pkg/util/ffiwrapper/verifier.go
- pkg/vmsupport/syscalls.go
- tools/conformance/driver.go
- tools/gengen/util/generator.go
- tools/seed/seed.go
> fix reference

- pkg/jwtauth/local_jwt.go
default api token generated by venus have all permission
> default api token generated by venus have all permission

- Makefile
- app/client/full.go
- app/client/v0api/full.go
- app/submodule/apiface/chain.go
- app/submodule/chain/chaininfo_api.go
> add ChainGetMessagesInTipset api

- app/node/builder.go
- app/node/node.go
- cmd/main.go
- pkg/jwtauth/local_jwt.go
- pkg/repo/fsrepo.go
> opt unite auth_url

- .gitignore
- app/node/node.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/jwtauth/remote_auth.go
request rate limit base on user-account
Closes #
> request rate limit configs

- pkg/types/fil.go
> ref lotus 1.10.1

- bin/container_daemon
- cmd/swarm_integration_test.go
- pkg/repo/fsrepo.go
- pkg/testhelpers/test_daemon.go
- tools/gengen/main.go
> inaccurate log prompt and rm "venus init"

- app/node/rpc.go
- go.mod
- go.sum
- pkg/jwtauth/local_jwt.go
- pkg/jwtauth/remote_auth.go
> update auth, fix nil interface

- pkg/events/events_called.go
> cache for loaded message in evnets

- app/client/node.go
- app/submodule/wallet/remotewallet/parse.go
- go.mod
- go.sum
> support tls

- go.mod
- go.sum
> Feat/update auth+jsonrpc

- go.mod
- go.sum
> update metrics mod, to change span attribute "Acount" to lower case

- go.mod
- go.sum
- pkg/fork/fork.go
> fix bug state type version

- fixtures/networks/nerpanet.go
> fix UpgradeClausHeight for nerpa

- pkg/types/tipset.go
> check tipset is nil

- pkg/migration/migrate.go
> close repo after version4upgrate

- cmd/daemon.go
- cmd/seed.go
- pkg/chainsync/syncer/syncer.go
> Genesis Node: add some cmd

- cmd/main.go
> clear commond line help string

- fixtures/networks/net_2k.go
- pkg/chain/store.go
> fix import bug from chain file

- app/client/full.go
- app/submodule/apiface/chain.go
- app/submodule/chain/chaininfo_api.go
> support ChainGetPath

- app/client/full.go
- app/submodule/apiface/chain.go
- app/submodule/chain/chaininfo_api.go
- pkg/events/cache.go
- pkg/events/eventAPI.go
- pkg/events/events.go
- pkg/events/events_called.go
- pkg/events/events_height.go
- pkg/events/events_test.go
- pkg/events/message_cache.go
- pkg/events/observer.go
- pkg/events/state/fastapi.go
- pkg/events/state/mock/api.go
- pkg/events/state/predicates.go
- pkg/events/state/predicates_test.go
- pkg/events/tscache.go
- pkg/events/tscache_test.go
- pkg/events/utils.go
- tools/conformance/chaos/state.go
> Sealing: upgrade chain event

- pkg/migration/migrate.go
> upgrate forcenet 'forkupgadeparams' on migration from version 3 to 4'

- pkg/messagepool/gas.go
> fix message send spec is nil

- documentation/venus-market module design & roadmap.md
The structure diagram is supplemented
> Update venus-market module design & roadmap.md

- app/submodule/network/network_submodule.go
> fix default network name

- pkg/util/blockstoreutil/badger.go
> less cache size to reduce memory

- fixtures/networks/forcenet.go
> upgrade force net

- pkg/migration/migrate.go
> add prefix for data migrate, make different withe actor migrate

- pkg/migration/migrate.go
> fix migrate version log error

- pkg/config/config.go
- pkg/messagepool/gas.go
> set default max fee and default chocolate upgrade height

- pkg/chain/store.go
- pkg/chain/store_test.go
- pkg/chain/tip_index.go
- pkg/chainsync/syncer/syncer.go
- pkg/chainsync/syncer/syncer_test.go
> Simplify the tipset states index

- .github/workflows/tag-workflow.yml
policies:
1. tags 
- tags with 'v*' prefix would trigger auto-building and release, 
- other tag would trigger auto-building and upload outputs to artifacts.
2. pull requests
- any PR would trigger auto-building and upload outputs to artifacts.
3. pull 
- any pull to 'master' would trigger auto-building and upload outputs to artifacts.
if a release is created, send a release request to godeye, otherwise a test.
>  github workflow

- .github/workflows/tag-workflow.yml
> fix godeye push method

- fixtures/networks/integrationtestnet.go
- pkg/types/specactors/builtin/init/diff.go
- pkg/types/specactors/builtin/market/diff.go
- pkg/types/specactors/builtin/miner/diff.go
- pkg/types/specactors/builtin/miner/diff_deadlines.go
- pkg/types/specactors/builtin/multisig/diff.go
- pkg/types/specactors/builtin/power/diff.go
- pkg/types/specactors/policy/policy.go
> specactors: Add code not generated by the template

- app/submodule/mining/mining_api.go
- pkg/messagepool/repub.go
- pkg/messagepool/selection.go
- pkg/messagepool/selection_test.go
- tools/gengen/util/generator.go
- venus-shared/api/chain/v0/fullnode.go
- venus-shared/chain/complex_provider_test.go
- venus-shared/chain/tipset_key.go
https://github.com/filecoin-project/lotus/pull/7321
Closes #
> Mempool msg selection should respect block message limits

- pkg/chain/utils.go
> fix method map

- cmd/show_test.go
- cmd/state.go
- pkg/types/internal/cbor_gen.go
- pkg/types/internal/message.go
- pkg/types/internal/testing_messages.go
> Unify the definition of MessageReceipt

- .github/workflows/tag-workflow.yml
clean go mod cache before make
> clean go mod cache before make

- pkg/chain/utils.go
- pkg/vm/vmcontext/runtime_adapter.go
- pkg/vm/vmcontext/syscalls.go
> more inline template

- pkg/fork/fork.go
- pkg/vm/gas/gascost.go
- tools/conformance/driver.go
- tools/conformance/runner.go
> test vector runner fixes for v6 vectors

- pkg/vm/gas/gascost.go
- pkg/vm/gas/pricelistV0.go
> add gas charge for VerifyReplicaUpdate

- go.mod
- go.sum
https://github.com/filecoin-project/lotus/issues/7886
新增一个参数 `TRUST_PARAM `，**主网升级时需要禁用该参数**：
* 检查本地是否存在有效的参数
* 如果没有，则从提供的源获取
> mod: update go-paramfetch

- Makefile
- fixtures/_assets/proof-params/parameters.json
> add temp snap params

- pkg/vm/vmcontext/invocation_context.go
- pkg/vm/vmcontext/vmcontext.go
fixed: https://github.com/filecoin-project/lotus/issues/7596
> fix sender and receiver are the same

- go.mod
- go.sum
> Integrate proof v11.0.0

- build/main.go
- cmd/version.go
- cmd/version_daemon_test.go
> opt version cmd

- pkg/constants/version.go
> bump version to v1.2.0-rc1

- pkg/constants/version.go
> bump version to v1.2.0-rc3

- pkg/constants/version.go
> bump version to v1.2.0-rc4

- pkg/wallet/dsbackend.go
> fix: wallet: unlock failed

- pkg/util/blockstoreutil/badger.go
badger panic while put data after closing.  here use wait group to gurantee close adter all data flushed
https://github.com/filecoin-project/venus/issues/4578
> fix panic while closing badger

- fixtures/_assets/proof-params/parameters.json
> fix: remove unrelated parmas

- pkg/migration/migrate.go
- pkg/repo/fsrepo.go
> fix: config: migrate v7 version config

- fixtures/networks/mainnet.go
> chore: build: fix comment

- pkg/constants/version.go
> build: venus: update version to v1.2.0

- pkg/constants/version.go
> build: bump version to v1.2.1

- go.mod
- go.sum
- venus-component/go.mod
- venus-component/go.sum
- venus-devtool/go.sum
> chore: dep: upgrade deps

- pkg/constants/version.go
> build: update version to v1.2.2

- pkg/chain/store.go
fix import snapshot may fail for different snapshots
> fix: snapshot: import snapshot may fail for different snapshots

- pkg/constants/version.go
> build: venus: update version to v1.2.3

- cmd/main.go
- cmd/message.go
> fix: cmd: remove default repo_dir value

- .github/workflows/baisc_checks.yml
- .github/workflows/tag-workflow.yml
- .github/workflows/test.yml
- pkg/constants/version.go
> chore:update version

- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/compatible-checks/api-checksum.txt
- venus-shared/compatible-checks/api-diff.txt
> chore: venus-devtool: update lotus to v1.16.0

- app/submodule/chain/beacon.go
- app/submodule/chain/chain_submodule.go
> fix: impl api BeaconGetEntry

- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump version to v1.6.0

- pkg/chainsync/slashfilter/mysqldb.go
> fix(slashfilter): increase parent_key field length for mysql db

- docker/script/compose.sh
https://github.com/filecoin-project/venus/issues/4974
check whether  snapshot provide,and launch venus daemon correspondingly
> feat #4974 : venus : make snapshot optional

- venus-shared/api/market/api.go
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
- venus-shared/types/market/piecestorage.go
change api name PieceStorageList to  PieceStorageInfos
> style: change api name PieceStorageList to  PieceStorageInfos

- docker/script/compose.sh
add genesisfile support in compose script
> chore : docker add genesisfile support

- .github/workflows/tag-workflow.yml
fix: git action: mission colon in auto release workflow.
> fix:git action: mission colon in auto release workflow

- cmd/sync.go
- pkg/chainsync/dispatcher/dispatcher.go
resolve  https://github.com/filecoin-project/venus/issues/5035
add height diff field in sync status subcomand
> feat: add height diff in sync status

- pkg/chainsync/slashfilter/slashfilter.go
fix return error message in slashfilter so if the error occurs correct message will be displayed
> fix: error message: correct error message 

- venus-shared/api/messager/method.md
- venus-shared/types/messager/address.go
- venus-shared/types/messager/spec.go
暂不包含 : https://github.com/filecoin-project/venus/pull/5106
> fix: revert #5106

- pkg/constants/version.go
resolve: https://github.com/filecoin-project/venus/issues/5049
> chore: bump version to v1.6.1

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
fix https://github.com/filecoin-project/venus/issues/5130
> chore: remove community label from template

- Makefile
- venus-shared/api/market/api.go
- venus-shared/api/market/method.md
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
involve https://github.com/filecoin-project/venus/issues/5088
add interface to add offline deal
> feat: 增加导入离线订单的接口 / add interface to add offline deal

- venus-shared/api/market/api.go
- venus-shared/api/market/method.md
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
- venus-shared/types/market/piecestorage.go
involve  https://github.com/filecoin-project/venus/issues/5069
fix interface which add s3piecestorage
fix structure which transpor info about s3piecestorage
> feat: 修改增加s3piecestorage的market接口 / fix interface which add s3piecestorage

- venus-shared/api/messager/api.go
- venus-shared/api/messager/proxy_gen.go
> chore: rename maxFeeCap to gasFeeCap

- app/submodule/wallet/remotewallet/parse.go
- go.mod
- go.sum
> opt: 统一使用venus-shared库中的apiinfo / unified use apiinfo in venus-shared

- networking.md
- venus-devtool/api-gen/example.go
- venus-shared/api/market/api.go
- venus-shared/api/market/method.md
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
- venus-shared/types/market/piecestorage.go
- venus-shared/types/market/storage.go
close https://github.com/filecoin-project/venus/issues/5207
返回各状态订单的数量
> feat: market增加统计接口，用于监控使用/ add statistic for storage and retrieval deals

- venus-devtool/cborgen/main.go
close
fix: dev-tool: generated wrong market type
> fix: dev-tool: generated wrong market type

- pkg/market/cbor_gen.go
- venus-devtool/cborgen/main.go
- venus-shared/api/market/method.md
- venus-shared/types/market/assigner_type.go
- venus-shared/types/market/cbor_gen.go
- venus-shared/types/market/funded_address_state.go
- venus-shared/types/market/miner_deal.go
- venus-shared/types/market/paych.go
- venus-shared/types/market/retrieval_ask.go
- venus-shared/types/market/retrieval_deal.go
close nil
add timestamp to storagedeal and retrievaldeal.
> feat: add timestamp into storagedeal, retrievaldeal

- cmd/daemon.go
- docker/script/compose.sh
- fixtures/networks/network_parse.go
- fixtures/networks/network_parse_test.go
- venus-shared/utils/utils.go
- venus-shared/utils/utils_test.go
close https://github.com/filecoin-project/venus/issues/5187
> opt: 调整network flag的值和网络名一致 / optimize network flag

- .github/workflows/common_docker_image.yml
fix: download dockerfile before build
> fix: download dockerfile before build

- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump version to v1.7.0

- .github/workflows/build_upload.yml
- .github/workflows/common_docker_image.yml
- .github/workflows/docker_image.yml
- Makefile
involve https://github.com/filecoin-project/venus/issues/5267
- make deps before make docker
> fix: make deps before make docker

- venus-shared/api/messager/api.go
- venus-shared/api/messager/method.md
- venus-shared/api/messager/mock/mock_imessager.go
- venus-shared/api/messager/proxy_gen.go
- venus-shared/types/messager/address.go
- venus-shared/types/messager/spec.go
close https://github.com/filecoin-project/venus/issues/5139
> feat:  接口增加 basefee 参数 / add basefee for messager api

- app/submodule/syncer/syncer_submodule.go
- pkg/chainsync/dispatcher/dispatcher.go
- pkg/chainsync/syncer/syncer.go
- pkg/chainsync/types/target_tracker.go
- pkg/consensus/block_validator.go
- pkg/consensus/expected.go
- pkg/consensus/processor.go
> chore: 减少日志输出 / opt log

- pkg/net/exchange/client.go
- pkg/net/exchange/server.go
- venus-shared/libp2p/exchange/exchange.go
close https://github.com/filecoin-project/venus/issues/5288
> chore: 移除blocksync协议 / remove blocksync protocol

- pkg/net/exchange/peer_tracker.go
- pkg/net/peermgr/peermgr.go
close https://github.com/filecoin-project/venus/issues/5288
> chore: 增加移除peer事件 / opt peer event

- app/submodule/chain/chaininfo_api.go
- pkg/chain/store.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
close https://github.com/filecoin-project/venus/issues/5222
close https://github.com/filecoin-project/venus/issues/5294
> feat: 增加两个链接口 / add chain api

- cmd/sync.go
> opt: Status display when sync is complete / 一些命令行显示的优化

- pkg/chainsync/slashfilter/mysqldb.go
close https://github.com/filecoin-project/venus/issues/5094
> fix: 调整 parent_key字段长度 / update parent_key field to varchar(2048)

- cmd/multisig.go
lotus pr：https://github.com/filecoin-project/lotus/pull/8833/files
> chore: Check for existing signers in add-propose

- fixtures/networks/mainnet.go
lotus pr：https://github.com/filecoin-project/lotus/pull/9008/files
> chore: 调整 1475 bootstrap的peer id / change 1475 bootstrap peer

- app/submodule/chain/miner_api.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
lotus pr：https://github.com/filecoin-project/lotus/pull/9183
> feat: add chain api `StateMinerAllocated`

- .github/workflows/common_build_upload.yml
- .github/workflows/common_go.yml
close
1. 在通用测试工作流中, 增加设置超时的参数.
2. 当upload ftp失败是, 允许继续后面的job.
3. 检查`go mod tidy`
> feat: add timeout params for shared common test/共享的通用测试工作流中添加超时的参数.

- cmd/main.go
close https://github.com/filecoin-project/venus/issues/5242
> feat: conceal the detail of state cmd

- app/submodule/mpool/mpool_submodule.go
- fixtures/networks/butterfly.go
- fixtures/networks/calibration.go
- fixtures/networks/forcenet.go
- fixtures/networks/integrationtestnet.go
- fixtures/networks/interopnet.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- pkg/config/config.go
- pkg/constants/chain_parameters.go
- pkg/messagepool/messagepool.go
- pkg/messagepool/messagepool_test.go
- pkg/messagepool/repub_test.go
- pkg/messagepool/selection_test.go
- pkg/migration/migrate.go
lotus pr：https://github.com/filecoin-project/lotus/pull/9290/
> feat: move propagationDelaySecs to config

- cmd/seed.go
- pkg/constants/shared_vals.go
- pkg/messagepool/messagepool.go
- pkg/messagepool/messagepool_test.go
- pkg/messagepool/provider.go
- pkg/paychmgr/mock_test.go
- venus-devtool/api-gen/example.go
close https://github.com/filecoin-project/venus/issues/5338
> feat: refactor: remove NewestNetworkVersion

- go.mod
- go.sum
- pkg/vm/dispatch/dispatch.go
- pkg/vm/dispatch/loader.go
- pkg/vm/register/default.go
- tools/conformance/driver.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/actors/builtin/registry.go
- venus-shared/actors/builtin/registry.go.template
- venus-shared/utils/method_map.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9342
> chore: actors: Allow builtin-actors to return a map of methods

- fixtures/networks/butterfly.go
- fixtures/networks/calibration.go
- fixtures/networks/forcenet.go
- fixtures/networks/integrationtestnet.go
- fixtures/networks/interopnet.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- pkg/config/config.go
- pkg/fork/fork.go
- pkg/migration/migrate.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9462 https://github.com/filecoin-project/lotus/pull/9483
> chore: update clib and butterfly asset

- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump version to v1.8.0-rc1

- pkg/messagepool/messagepool.go
- pkg/messagepool/messagepool_test.go
close https://github.com/filecoin-project/venus/issues/5382
> fix: add gaspremium check when less than maxfee

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
lotus pr：https://github.com/filecoin-project/lotus/pull/9502
> chore: update to go-state-types v0.9.1

- fixtures/networks/net_2k.go
- pkg/config/config.go
> fix: Update DevNet to true in 2k network configuration

- app/submodule/chain/chaininfo_api.go
- pkg/constants/version.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/types/api_types.go
> chore: bump version to 1.8.0-rc2

- pkg/constants/version.go
> chore: bump version to v1.8.0-rc3

- pkg/fork/fork.go
https://github.com/filecoin-project/lotus/pull/9525
> feat: add a second premigration for nv17

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
close
lotus pr: https://github.com/filecoin-project/lotus/pull/9537
> chore: Update to latest go-state-types for migration fixes

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
> chore: update go-state-types to v-0.9.7

- app/submodule/chain/miner_api.go
- app/submodule/chain/v0api/chaininfo_v0api.go
- pkg/gen/genesis/miners.go
- pkg/gen/genesis/types.go
- pkg/market/fundmanager.go
- pkg/market/fundmanager_test.go
- pkg/paychmgr/manager.go
- pkg/paychmgr/paych.go
- pkg/paychmgr/paych_test.go
- pkg/state/view.go
- tools/seed/seed.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/types/alias.go
- venus-shared/types/api_types.go
- venus-shared/types/market/assigner_type.go
- venus-shared/types/market/miner_deal.go
- venus-shared/types/market/paych.go
- venus-shared/types/market/storage.go
- venus-shared/types/paych.go
close https://github.com/filecoin-project/venus/issues/5053
> feat: 把部分go-state-types中会随版本变化的结构重命名到venus-shared / alias types

- app/node/node.go
> chore: shutdown server when receiving exit signal

- cmd/swarm.go
close https://github.com/filecoin-project/venus/issues/5371
> chore: specify arg in net ping cmd

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
> feat: update go-ipfs-cmd version

- fixtures/networks/butterfly.go
- pkg/migration/migrate.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9586
> chore: update butterfly

- fixtures/networks/calibration.go
- pkg/migration/migrate.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9584
> chore: set new upgrade heights for calibnet

- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump version to v1.8.0-rc4

- venus-shared/blockstore/mem.go
- venus-shared/blockstore/mem_test.go
from different codex
close https://github.com/filecoin-project/venus/issues/5370
> feat: make blockstore compatible with different cid of codex 

- pkg/fvm/fvm.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9591
> chore: Allow setting local bundles for Debug FVM for av 9+

- venus-shared/blockstore/autobatch.go
- venus-shared/blockstore/autobatch_test.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9603
> fix: autobatch: remove potential deadlock when a block is missing

- .github/workflows/common_go.yml
> chore: install jq

- venus-shared/api/messager/api.go
- venus-shared/api/messager/method.md
- venus-shared/api/messager/mock/mock_imessager.go
- venus-shared/api/messager/proxy_gen.go
https://github.com/filecoin-project/venus/issues/5417
> refactor: refactor log api for messager

- venus-shared/api/messager/method.md
- venus-shared/types/messager/message.go
> Feat/tanlang/add errorMsg field to message

- venus-devtool/api-gen/doc_gen.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
> Fix/tanlang/escape left open angle in comment of API doc

- fixtures/networks/integrationtestnet.go
- fixtures/networks/mainnet.go
- pkg/config/config.go
- pkg/migration/migrate.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9640
> chore: update mainnet shark epoch

- .github/workflows/common_build_upload.yml
> chore: update release action

- go.mod
- go.sum
- pkg/constants/version.go
https://github.com/filecoin-project/venus/issues/5401
> chore: bump version to v1.8.0

- cmd/address.go
> fix: remove unused argument

- pkg/chain/store.go
> fix: put all tipset cache to metadata

- CHANGELOG.md
- pkg/chain/store.go
- pkg/constants/version.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/compatible-checks/api-diff.txt
> Release v1.8.1

- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump version to 1.9.0-rc1

- app/node/builder.go
- app/node/env.go
- app/node/node.go
- app/submodule/common/common.go
- cmd/info.go
- cmd/main.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/api/chain/v1/common.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/types/api_types.go
close https://github.com/filecoin-project/venus/issues/5367
> feat: add info command

- pkg/gen/genesis/miners.go
- pkg/genesis/genesis.go
- pkg/vm/vm.go
- pkg/vm/vmcontext/interpreter.go
- tools/conformance/driver.go
- tools/gengen/util/generator.go
- tools/gengen/util/gengen.go
close https://github.com/filecoin-project/venus/issues/5470
> chore: remove method ApplyGenesisMessage

- .github/pull_request_template.md
close https://github.com/filecoin-project/venus/issues/5333
> chore: add compatible check item in pr template

- cmd/import.go
- go.mod
- go.sum
- pkg/chain/store.go
- pkg/state/tree/state.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9741
> feat: Faster snapshot imports, zstd imports

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/actors/builtin/datacap/util.go
close https://github.com/filecoin-project/venus/issues/5514 https://github.com/filecoin-project/venus/issues/5513
> chore: update deps

- documentation/misc/release-issue-template.md
close https://github.com/filecoin-project/venus/issues/5538
> docs: update release template

- app/submodule/common/common.go
- cmd/info.go
- venus-shared/api/chain/v0/common.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/common.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
https://github.com/filecoin-project/lotus/pull/9436
> feat: Add node uptime rpc

- cmd/miner_actor.go
https://github.com/filecoin-project/lotus/pull/9572
> chore: set control address: add dump bytes option

- venus-shared/api/messager/api.go
- venus-shared/api/messager/method.md
- venus-shared/api/messager/mock/mock_imessager.go
- venus-shared/api/messager/proxy_gen.go
- venus-shared/types/messager/message.go
involve https://github.com/filecoin-project/venus/issues/5384
> Feat/tanlang/change messager api for user data isolation / 为用户数据隔离做准备修改 messager api 

- pkg/consensus/block_validator.go
- pkg/fvm/fvm.go
- pkg/messagepool/messagepool_test.go
- pkg/state/tree/state.go
- pkg/state/view.go
- pkg/statemanger/call.go
- pkg/statemanger/state_manger.go
- pkg/vm/vmcontext/invocation_context.go
- pkg/vm/vmcontext/syscallsStateView.go
- tools/conformance/driver.go
- venus-shared/actors/builtin/builtin.go
https://github.com/filecoin-project/lotus/pull/9533
> feat: allow sending from f4 addresses

- app/submodule/network/network_submodule.go
- pkg/net/peermgr/peermgr.go
close https://github.com/filecoin-project/venus/issues/5586
1. 在dht中删除bootstrap节点
2. peermgr中立即启动一次boot链接。
> fix: remove bootstrap in dht

- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_event_api.go
- cmd/eth.go
- cmd/main.go
- venus-shared/types/eth.go
> feat: Add cli to inspect Eth addresses and simulate calls

- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_event_api.go
- cmd/eth.go
- pkg/consensus/block_validator.go
- pkg/crypto/delegated/eth.go
- pkg/messagepool/messagepool.go
- pkg/state/sigval.go
- venus-shared/types/eth_transactions.go
- venus-shared/types/eth_transactions_test.go
> chore: simple some functions & fix EventFilterManager is nil

- app/submodule/mpool/mpool_submodule.go
close https://github.com/filecoin-project/venus/issues/5575
> fix:修复启动时重复注册topic的问题 / use sync once to provent join topic repeatly

- venus-devtool/api-gen/doc_gen.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/api/gateway/v0/method.md
- venus-shared/api/gateway/v1/method.md
- venus-shared/api/gateway/v2/method.md
- venus-shared/api/market/client/method.md
- venus-shared/api/market/method.md
- venus-shared/api/messager/method.md
- venus-shared/api/wallet/method.md
> feat: add namespace and curl example in jsonrpc example

- pkg/config/config.go
- pkg/consensus/block_validator.go
- pkg/consensus/expected.go
- pkg/constants/shared_vals.go
> feat: AllowableClockDriftSecs configurable

- go.mod
- go.sum
> chore: upgrade auth ref version to v1.9.0

- app/submodule/chain/chaininfo_api.go
- app/submodule/mining/mining_api.go
- cmd/chain.go
- cmd/eth.go
- cmd/state.go
- pkg/chain/testing.go
- pkg/chain/waiter.go
- pkg/chainsync/syncer/syncer.go
- pkg/chainsync/syncer/syncer_integration_test.go
- pkg/chainsync/syncer/syncer_test.go
- pkg/consensus/block_validator.go
- pkg/consensus/expected.go
- pkg/consensus/processor.go
- pkg/consensus/protocol.go
- pkg/fork/fork.go
- pkg/statemanger/state_manger.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
resolve https://github.com/filecoin-project/venus/issues/5466
> feat: add state replay rpc

- app/submodule/chain/chaininfo_api.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
> feat: add chain get events rpc

- venus-devtool/api-gen/client.go
- venus-devtool/api-gen/common/common.go
- venus-devtool/api-gen/doc_gen.go
- venus-devtool/api-gen/main.go
- venus-devtool/api-gen/mock.go
- venus-devtool/api-gen/proxy/proxy.go
- venus-devtool/util/api_meta.go
close
暴露生成 api-proxy 的方法用于别的仓库调用
> Feat/tanlang/expose api gen / 暴露生成 api-proxy 的方法

- venus-shared/types/messager/message.go
close https://github.com/filecoin-project/venus/issues/5612
> feat: rename replacedmsg to nonceconfict

- venus-devtool/api-gen/common.go
- venus-shared/api/gateway/v2/method.md
> fix: doc-gen of gateway / 正确生成gateway v2的接口文档

- app/submodule/chain/chaininfo_api.go
- app/submodule/eth/eth_api.go
- pkg/chain/store.go
- pkg/chain/waiter.go
- pkg/net/helloprotocol/cbor_gen.go
- pkg/net/helloprotocol/hello_protocol.go
- pkg/statemanger/call.go
- venus-shared/types/tipset_key.go
- venus-shared/types/tipset_key_test.go
1. StateActorCodeCIDs 接口不返回 `_manifest `
2. 调整 tipsetkey UnmarshalCBOR and MarshalCBOR 方法
3. HelloMessage 中HeaviestTipSetCids 类型由 TipSetKey 调整为 []cid.Cid
4. 修复countTipsetMsgs函数未能正确返回消息数量问题
> fix: chain eth apis

- app/node/builder.go
- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_event_api.go
- app/submodule/eth/eth_submodule.go
- pkg/config/config.go
- pkg/crypto/sigs.go
- pkg/ethhashlookup/eth_transaction_hash_lookup.go
- pkg/events/filter/mempool.go
- pkg/repo/fsrepo.go
- pkg/repo/mem.go
- pkg/repo/repo.go
- venus-shared/api/chain/v1/eth.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
- venus-shared/types/eth.go
- venus-shared/types/eth_transactions.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9965
> feat: Store mapping of eth transaction hashes to message cids

- app/submodule/mpool/mpool_api.go
- pkg/messagepool/messagepool.go
close https://github.com/filecoin-project/venus/issues/5694
> fix: not publish message

- app/node/node.go
- app/submodule/eth/eth_submodule.go
> fix: first close eth

- pkg/constants/version.go
> chore: bump version to 1.9.0

- CHANGELOG.md
- go.mod
- go.sum
- pkg/constants/version.go
https://github.com/filecoin-project/venus/issues/5651
> chore: bump version to v1.10.0-rc1

- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_docker_image.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
> chore: git action update to ubuntu-22.04

- cmd/daemon.go
- cmd/daemon_daemon_test.go
- cmd/main.go
> feat: add bootstrap peers flag

- go.mod
- go.sum
https://github.com/ipfs-force-community/go-jsonrpc/pull/18
> chore: upgrade go-jsonrpc

- app/node/node.go
- go.mod
- go.sum
> feat: add status api to detect api ready

- pkg/chain/message_store.go
> fix: fix store receipts

- CHANGELOG.md
- pkg/constants/version.go
> chore: bump version to v1.10.0-rc4

- pkg/chainsync/syncer/syncer.go
- pkg/net/helloprotocol/hello_protocol.go
close https://github.com/filecoin-project/venus/issues/5747
> fix: not sync in 2k network

- fixtures/networks/calibration.go
close
把 calibration 网络 UpgradePersianHeight 的值调整为 240
https://github.com/filecoin-project/lotus/blob/master/build/params_calibnet.go#L51
> fix: update persian height to 240

- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
> chore: cherry-pick 5773

- app/submodule/eth/dummy.go
- app/submodule/eth/eth_api.go
- venus-shared/api/chain/v1/eth.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
https://github.com/filecoin-project/lotus/pull/10343
> feat: EthAPI: Add FilecoinAddressToEthAddress

- app/submodule/chain/chaininfo_api.go
- app/submodule/mining/mining_api.go
- cmd/address.go
- pkg/chain/message_store.go
- pkg/chain/store.go
- pkg/chain/testing.go
- pkg/chain/waiter.go
- pkg/chainsync/syncer/syncer.go
- pkg/chainsync/syncer/syncer_integration_test.go
- pkg/chainsync/syncer/syncer_test.go
- pkg/consensus/block_validator.go
- pkg/consensus/expected.go
- pkg/consensus/protocol.go
- pkg/net/exchange/server.go
- pkg/state/view.go
- pkg/statemanger/state_manger.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
- venus-shared/types/api_types.go
> fix: add vmTracing for state replay

- CHANGELOG.md
- fixtures/networks/mainnet.go
- go.mod
- go.sum
- main.go
- pkg/constants/version.go
- pkg/migration/migrate.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/compatible-checks/api-checksum.txt
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
> chore: bump version to v1.10.0

- cmd/evm.go
- cmd/utils.go
> fix: fix evm cmds

- venus-shared/api/market/v0/api.go
- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v0/mock/mock_imarket.go
- venus-shared/api/market/v0/proxy_gen.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
> feat: add miner mgr api

- app/submodule/chain/chaininfo_api.go
- cmd/state.go
- pkg/statemanger/state_manger.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
> feat: add compute state api

- venus-devtool/api-gen/example.go
- venus-shared/api/gateway/v2/market_event.go
- venus-shared/api/gateway/v2/method.md
- venus-shared/api/gateway/v2/mock/mock_igateway.go
- venus-shared/api/gateway/v2/proxy_gen.go
- venus-shared/types/gateway/market_event.go
- venus-shared/types/market/piece_transfer.go
> feat: upgrade market-event api

- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
> feat: market: new api `ReleaseDeals`

- cmd/state.go
- go.mod
- go.sum
- pkg/beacon/drand.go
- pkg/chain/store.go
- pkg/consensus/block_validator.go
- pkg/events/message_cache.go
- pkg/messagepool/gas.go
- pkg/messagepool/messagepool.go
- venus-devtool/go.mod
- venus-devtool/go.sum
> feat: update cache to the new generic version

- venus-shared/api/market/v0/api.go
- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v0/mock/mock_imarket.go
- venus-shared/api/market/v0/proxy_gen.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
- venus-shared/types/market/dagstore.go
https://github.com/filecoin-project/venus/issues/5854
> feat: market: add api DagstoreDestroyShard

- venus-shared/actors/types/bigint_fil.go
- venus-shared/types/bigint_fil_test.go
> fix: use FIL pointer to unmarshaltext

- CHANGELOG.md
- pkg/constants/version.go
> chore: bump version to v1.10.2

- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_test.go
- cmd/mpool.go
- cmd/utils.go
- pkg/messagepool/config.go
- pkg/messagepool/messagepool.go
- venus-devtool/api-gen/example.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/types/mpool_config.go
- venus-shared/types/percent.go
- venus-shared/types/percent_test.go
> chore: cherry pick #5832  

- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_docker_image.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
close https://github.com/filecoin-project/venus/issues/5796
> chore: use ubuntu-20.04 in git action

- CHANGELOG.md
- Makefile
> Pre/v1.11 / 合并预发布分支

- fixtures/networks/forcenet.go
> fix: update UpgradeHyggeHeight to -21 in forcenet

- pkg/consensus/processor.go
> fix: can not replay secp message

- CHANGELOG.md
- pkg/constants/version.go
ref: https://github.com/filecoin-project/lotus/issues/10733
> Fix/veryfy window po st fail / 修复 windowPoST 验证失败的问题

- .github/workflows/common_build_upload.yml
> opt: push all tag to tianyan

- .github/workflows/common_build_upload.yml
close https://github.com/filecoin-project/venus/issues/5937
> fix: supply release id

- pkg/chain/store.go
close https://github.com/filecoin-project/venus/issues/5949
> fix: fix import when less than 900 height

- app/node/builder.go
- go.mod
- go.sum
- venus-shared/api/permission/permission.go
> opt: remove perm adapt strategy

- pkg/messagepool/selection.go
> feat: mpool: prune excess messages before selection

- .github/workflows/common_build_upload.yml
close https://github.com/filecoin-project/venus/issues/5982
> fix: fetch filecoin-ffi failed

- pkg/chain/circulating_supply.go
> feat: chain: speed up calculation of genesis circ supply

- pkg/messagepool/gas.go
> fix: gas estimation: do not special case paych collects

- app/submodule/chain/chaininfo_api.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/types/api_types.go
> feat: Network parameters add an Eip155ChainID field

- app/submodule/chain/miner_api.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/types/api_types.go
> opt: MinerInfo adds the PendingOwnerAddress field

- venus-shared/api/market/client/api.go
- venus-shared/api/market/client/method.md
- venus-shared/api/market/client/mock/mock_imarketclient.go
- venus-shared/api/market/client/proxy_gen.go
- venus-shared/api/market/v0/api.go
- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v0/mock/mock_imarket.go
- venus-shared/api/market/v0/proxy_gen.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
- venus-shared/types/market/client/deal.go
- venus-shared/types/market/storage.go
https://github.com/filecoin-project/venus/issues/5809
> feat: add batch deal for market

- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
v0 增加 lotus 有但 venus 没有的 state 接口
> fix: more chain api

- .github/workflows/common_build_upload.yml
close https://github.com/filecoin-project/venus/issues/6030
> chore: correct god eye url and prioritize ftp

- .circleci/config.yml
- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
- go.mod
- venus-component/go.mod
- venus-devtool/go.mod
> chore: update minimum Go version to 1.19

- CHANGELOG.md
- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump up version to v1.12.0

- .github/ISSUE_TEMPLATE/enhancement.yml
close https://github.com/filecoin-project/venus/issues/6043
related https://github.com/ipfs-force-community/venus-core-devs/issues/18
> Update issue template enhancement.yml

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
close https://github.com/filecoin-project/venus/issues/6043
related https://github.com/ipfs-force-community/venus-core-devs/issues/18
> Fix bug issue template

- CHANGELOG.md
- go.mod
- go.sum
- pkg/constants/version.go
> chore: merge v1.12.0 into master

- documentation/zh/config-desc.md
> add config desc / 添加config注释

- app/submodule/eth/eth_event_api.go
- app/submodule/eth/eth_submodule.go
- app/submodule/eth/eth_test.go
- go.mod
- go.sum
- pkg/chain/chain_index.go
- pkg/shardedmutex/shardedmutex.go
- pkg/shardedmutex/shardedmutex_test.go
- venus-devtool/go.mod
- venus-devtool/go.sum
close https://github.com/filecoin-project/venus/issues/6018
close https://github.com/filecoin-project/venus/issues/6020
close https://github.com/filecoin-project/venus/issues/6021
> Chore/pick 10971,10955,10934 from lotus

- app/submodule/mpool/mpool_submodule.go
- app/submodule/network/network_submodule.go
- app/submodule/syncer/syncer_submodule.go
- cmd/daemon.go
- cmd/main.go
- pkg/config/config.go
- pkg/net/gossipsub.go
close https://github.com/filecoin-project/venus/issues/6080
```
"swarm": {
"address": "/ip4/0.0.0.0/tcp/0",
"protectedPeers": null,
"connMgrLow": 150,
"connMgrHigh": 180,
"connMgrGrace": "20s"
},
"pubsub": {
"bootstrapper": false
}
```
> feat: add bootstrap

- app/node/test/builder.go
- fixtures/networks/butterfly.go
- fixtures/networks/calibration.go
- fixtures/networks/forcenet.go
- fixtures/networks/hyperspace.go
- fixtures/networks/integrationtestnet.go
- fixtures/networks/interopnet.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- fixtures/networks/wallaby.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/testing.go
> remove MinPeerThreshold in bootstrap config because it is not used /删除MinPeerThreshold字段从bootstrap配置，没有用到

- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v1/method.md
- venus-shared/types/market/assigner_type.go
close
根据扇区的生命周期过滤订单，用于 snapdeal
> feat(market): filter deals by sector lifetime

- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v1/method.md
- venus-shared/types/market/assigner_type.go
close
Cherry pick #6093 to release v1.12
> Cherry pick #6093 to release v1.12

- cmd/state.go
in  cli(compute-state)
close https://github.com/filecoin-project/venus/issues/6019
> feat: set tipset to the given epoch by default

- app/submodule/syncer/syncer_submodule.go
- pkg/chainsync/syncer/syncer_integration_test.go
- pkg/chainsync/syncer/syncer_test.go
- pkg/messagepool/messagepool_test.go
- pkg/statemanger/state_manger.go
close [#6058](https://github.com/filecoin-project/venus/issues/6058)
> Make execution trace configurable via env variable venus / 通过VENUS_EXEC_TRACE_CACHE环境变量谁知trace缓存大小

- venus-shared/actors/types/rlp.go
- venus-shared/actors/types/rlp_test.go
close [6071](https://github.com/filecoin-project/venus/issues/6071)
> fix: ethtypes: handle length overflow case / 处理rlp长度越界问题

- CHANGELOG.md
- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump up version to v1.13.0-rc1

- app/submodule/eth/eth_event_api.go
- pkg/events/filter/index.go
- pkg/events/filter/index_test.go
> fix duplicate actor events / 解决以太坊event 日志重复问题

- venus-shared/blockstore/badger.go
close https://github.com/filecoin-project/venus/issues/6108
> add check before write badger / 添加检查已经存在，在写入之前

- app/submodule/mpool/mpool_submodule.go
- pkg/messagepool/messagepool.go
> fix: add existing nonce error

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
https://github.com/filecoin-project/go-fil-markets/blob/v1.28.2/storagemarket/types_cbor_gen.go#L1713 和 https://github.com/filecoin-project/go-fil-markets/blob/v1.27.0-rc1/storagemarket/types_cbor_gen.go#L1714 MarshalCBOR 的顺序不一样导致结果也不一样 。。。。。。
> chore: update go-fil-markets to v1.28.2

- cmd/import.go
- pkg/httpreader/resumable.go
> Auto-resume interrupted snapshot imports / 自动重链快照导入失败时

- venus-shared/actors/types/rlp.go
> fix: DecodeRLP can panic

- go.mod
- pkg/chain/store.go
- pkg/fork/fork.go
- venus-shared/blockstore/copy.go
close https://github.com/filecoin-project/venus/issues/6072
> feat: vm: allow raw cbor in state and use the new go-multicodec

- pkg/chain/message_store.go
> optimize LoadTipSetMessage / 优化LoadTipSetMessage

- venus-shared/blockstore/badger.go
- venus-shared/blockstore/blockstore.go
- venus-shared/blockstore/buf_bstore.go
- venus-shared/blockstore/mem.go
- venus-shared/blockstore/net.go
- venus-shared/blockstore/syncstore.go
- venus-shared/blockstore/view_blockstore.go
> feat: Plumb through a proper Flush() method on all blockstores

- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v1/method.md
- venus-shared/types/market/storage.go
方便 droplet http 检索的时候根据 piececid 来查询是否存在 active 订单
> feat: add PieceCID to StorageDealQueryParams

- app/node/rpc.go
- app/submodule/eth/dummy.go
- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_trace.go
- app/submodule/eth/eth_utils.go
- app/submodule/eth/txhashmanager.go
- venus-shared/actors/types/eth.go
- venus-shared/api/chain/v1/eth.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
- venus-shared/types/eth.go
- venus-shared/types/exec.go
https://github.com/filecoin-project/lotus/pull/11100
> feat: eth trace api

- documentation/en/venus-market-design-roadmap.md
> fix: typos

- venus-devtool/state-type-gen/main.go
- venus-shared/types/state_types_gen.go
> opt: generate datacap types to venus-shared

- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v1/method.md
- venus-shared/types/market/cbor_gen.go
- venus-shared/types/market/storage.go
> feat: add id to MinerDeal

- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v1/method.md
- venus-shared/types/market/storage.go
ref https://github.com/ipfs-force-community/droplet/issues/439
> feat: add asc field to StorageDealQueryParams

- venus-devtool/inline-gen/main.go
> chore: remove ioutil

- fixtures/networks/mainnet.go
close https://github.com/filecoin-project/venus/issues/6079
> feat: add bootstrap for mainnet

- fixtures/networks/forcenet.go
> fix: update GenesisNetworkVersion to Version20

- pkg/migration/migrate.go
- pkg/repo/fsrepo.go
> feat: migrate boostrap for config

- app/submodule/eth/eth_event_api.go
- pkg/config/config.go
- pkg/events/filter/index.go
close
1. 调整配置文件字段的命名
2. 修复 event index 迁移较慢问题
3. 修复没有把 event 信息写到 sqlite
> fix: not save data to event table

- fixtures/networks/calibration.go
> chore: Set calibration upgrade height

- app/submodule/eth/eth_event_api.go
- go.mod
- go.sum
> chore: fix panic

- fixtures/networks/butterfly.go
> chore: reset butterflynet

- cmd/state.go
> feat: add network info command

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
> chore: update go-state-types v0.12.5

- go.mod
- go.sum
> chore: update go-jsonrpc

- venus-shared/api/market/v0/api.go
- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v0/mock/mock_imarket.go
- venus-shared/api/market/v0/proxy_gen.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
- venus-shared/types/market/storage.go
> chore: cherry pick 6197

- app/submodule/eth/eth_api.go
- pkg/fork/fork.go
- pkg/net/exchange/server.go
- venus-component/libp2p/exchange/server.go
fix https://github.com/filecoin-project/venus/pull/6209/files#diff-dfa1ccfb1f0770b3c6b568d58b8a287adcb2cec98efb0fe72e525fe33e5129f0L717
> fix: repeat append value

- CHANGELOG.md
- pkg/constants/version.go
- venus-devtool/go.mod
- venus-devtool/go.sum
> chore: bump version to v1.14.0-rc5

- pkg/fork/fork.go
https://github.com/filecoin-project/lotus/pull/11396/files
预升级时间调整为 90 分钟
> opt: migration: set premigration to 90 minute

- CHANGELOG.md
- go.mod
- go.sum
- pkg/constants/version.go
- venus-devtool/go.mod
- venus-devtool/go.sum
> chore: bump version to v1.14.0-rc6

- cmd/sync.go
- venus-shared/types/api_types.go
> fix: sync category

- pkg/fork/mock.go
- pkg/gen/genesis/genesis.go
- pkg/genesis/genesis.go
- venus-shared/blockstore/blockstore.go
> opt: remove CachedBlockstore

- venus-shared/blockstore/badger.go
> opt: update badger ValueLogLoadingMode and TableLoadingMode to MemoryMap

- venus-shared/blockstore/badger.go
…g-mode
opt: update badger ValueLogLoadingMode and TableLoadingMode to MemoryMap
close
> chore: pick 6235

- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_test.go
- app/submodule/eth/eth_trace.go
- app/submodule/eth/eth_utils.go
close https://github.com/filecoin-project/venus/issues/6220
> fix: eth: correctly encode and simplify native input/output encoding

- pkg/net/exchange/client.go
- venus-devtool/cborgen/main.go
- venus-shared/libp2p/exchange/cbor_gen.go
- venus-shared/libp2p/exchange/exchange.go
- venus-shared/libp2p/exchange/protocol_encoding.go
> fix: exchange: allow up to 10k messages per block

- pkg/net/exchange/client.go
- venus-component/libp2p/exchange/client/client.go
fix: index too large may out of range
close
> chore: pick 6258

- CHANGELOG.md
- pkg/constants/version.go
- pkg/net/exchange/client.go
- venus-component/libp2p/exchange/client/client.go
> chore: bump version to v1.14.3

- pkg/gen/genesis/miners.go
https://github.com/filecoin-project/lotus/pull/11226/files#diff-812697c17219f62902c6929d56b6505c3a786ee4bc0bdefae37cba63372e7932
> fix: generate pre sector for 2k

- pkg/chainsync/syncer/syncer.go
- venus-shared/types/tipset.go
https://github.com/filecoin-project/lotus/pull/11533
> opt: syncer: optimize syncFork for one-epoch forks

- cmd/daemon.go
- pkg/repo/fsrepo.go
> fix: use existing config

- fixtures/networks/calibration.go
https://github.com/filecoin-project/lotus/pull/11702/files
> fix: remove calibnet bootstrappers

- app/submodule/eth/eth_api.go
https://github.com/filecoin-project/lotus/pull/11696/files
> fix: api: Length check the array sent to RPC

- venus-shared/types/market/storage.go
> fix: rename DealAllocation to DealAllocated

- venus-shared/api/market/v1/method.md
- venus-shared/types/market/storage.go
> fix: add StartEpoch and EndEpoch to DirectDealParam

- cmd/import.go
> fix: not set check point when import snapshot

- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
> feat: market: update direct deal state

- go.mod
- go.sum
> chore: update go-state-types

- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
> feat: update payload size

- go.mod
- go.sum
- venus-devtool/go.mod
- venus-devtool/go.sum
> feat: update deps

- CHANGELOG.md
- pkg/constants/version.go
> chore: bump version to v1.15.2

- go.mod
- go.sum
> chore: update go-multiaddr to v0.12.3

- app/node/node.go
- app/submodule/chain/chaininfo_api.go
> chore: fix function names in comment

- pkg/wallet/dsbackend.go
- pkg/wallet/dsbackend_test.go
> Fix: concurrent map writes when delete address

- pkg/consensusfault/check.go
- pkg/messagepool/messagepool_test.go
- pkg/paychmgr/paych.go
- pkg/repo/fsrepo_test.go
- pkg/state/power_table_view_test.go
- pkg/vm/dispatch/loader.go
- pkg/wallet/key/keyinfo.go
- venus-shared/types/uuid.go
> chore: fix some typos in comments

- pkg/chain/testing.go
- pkg/chainsync/syncer/syncer_test.go
> chore: fix some function names

- fixtures/networks/mainnet.go
https://github.com/filecoin-project/lotus/pull/11983
> chore: update mainnet bootstrap

- app/submodule/eth/eth_event_api.go
> fix: api: skip evm events where we no longer have the associated txn

- pkg/chainsync/syncer/syncer.go
- pkg/migration/migrate.go
- pkg/repo/fsrepo.go
> opt: migrate config

- app/submodule/eth/eth_utils.go
- venus-shared/actors/types/eth.go
> fix: api: return the correct block gas limit in the EthAPI

- pkg/vm/vmcontext/execution.go
> opt: fvm: optimize FVM lanes a bit

- tools/conformance/driver.go
> fix: pass timestamp through ExecuteMessageParams

- fixtures/networks/calibration.go
- fixtures/networks/mainnet.go
> fix: bootstrap: Update list to support both IPv4 and IPv6

- pkg/migration/migrate.go
- pkg/repo/fsrepo.go
- pkg/repo/fsrepo_test.go
> fix: migrate config failed

- app/node/builder.go
- app/node/node.go
- app/submodule/chain/chain_submodule.go
- app/submodule/chain/miner_api.go
- app/submodule/syncer/syncer_submodule.go
- cmd/import.go
- pkg/chain/chain_reader.go
- pkg/chain/circulating_supply.go
- pkg/chain/circulating_supply_mock.go
- pkg/chain/store.go
- pkg/chain/store_test.go
- pkg/chain/testing.go
- pkg/chainsync/syncer/syncer_integration_test.go
- pkg/chainsync/syncer/syncer_test.go
- pkg/consensus/expected.go
- pkg/gen/genesis/genesis.go
- pkg/genesis/init.go
- pkg/messagepool/messagepool_test.go
- pkg/statemanger/call.go
- pkg/statemanger/state_manger.go
- tools/conformance/driver.go
- tools/gengen/util/generator.go
> feat: Ignore market balance after nv23

- app/submodule/chain/miner_api.go
- pkg/state/view.go
- venus-devtool/api-gen/example.go
- venus-devtool/state-type-gen/main.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/types/state_types_gen.go
> chore: use v9 miner types

- pkg/events/filter/index.go
> fix: events: sqlite db improvements

- fixtures/networks/butterfly.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/compatible-checks/api-checksum.txt
- venus-shared/compatible-checks/api-diff.txt
> fix: update butterfly asset

- fixtures/networks/calibration.go
> fix: ManifestServerID is empty

- go.mod
- go.sum
- pkg/constants/version.go
- venus-devtool/go.mod
- venus-devtool/go.sum
> chore: bump version to v1.16.0-rc1

- cmd/chain.go
- cmd/state.go
> fix: conver nil to string

- pkg/constants/version.go
> chore: bump version to v1.16.1

- app/submodule/network/network_submodule.go
- fixtures/networks/butterfly.go
- fixtures/networks/calibration.go
- fixtures/networks/forcenet.go
- fixtures/networks/integrationtestnet.go
- fixtures/networks/interopnet.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- pkg/config/config.go
- pkg/vf3/config.go
> feat(f3): add a build parameter specifying F3's initial power table cid

- app/submodule/f3/f3_api.go
- fixtures/networks/integrationtestnet.go
- venus-devtool/api-gen/example.go
- venus-shared/api/chain/v1/f3.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
> feat: implement ticket based F3 participation lease

- fixtures/networks/butterfly.go
- fixtures/networks/calibration.go
> chore: update network asset

- pkg/constants/version.go
> chore: bump version to v1.17.0-rc1

- fixtures/networks/calibration.go
> chore: set Calibration upgrade epoch for nv24

- app/submodule/chain/miner_api.go
> fix: calculation miner deposit

- pkg/vf3/f3.go
- pkg/vf3/participation_lease.go
- pkg/vf3/participation_lease_test.go
> fix: determine F3 participants relative to current network name

- pkg/constants/version.go
> bump version to v1.17.0-rc2

- pkg/constants/version.go
> chore: bump version to v1.17.0

- fixtures/fortest/constants.go
- pkg/events/filter/sqlite/sqlite.go
- pkg/fork/fork.go
- pkg/net/gossipsub.go
- venus-shared/blockstore/copy.go
> Fix some typos

- app/submodule/config/config.go
- app/submodule/mpool/mpool_submodule.go
- pkg/chain/store.go
- pkg/chainsync/syncer/syncer.go
- pkg/events/events_height.go
- pkg/state/view.go
- pkg/testhelpers/net.go
- pkg/util/ulimit/ulimit.go
- pkg/vm/gas/pricelistV0.go
- pkg/vm/vmcontext/types.go
Fix some struct names and typos in comment
> Fix some struct names and typos in comment

- pkg/vf3/ec.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/actors/builtin/market/actor.go
- venus-shared/actors/builtin/market/actor.go.template
- venus-shared/actors/builtin/power/actor.go
- venus-shared/actors/builtin/power/actor.go.template
- venus-shared/actors/builtin/power/state.sep.go.template
- venus-shared/actors/builtin/power/state.v0.go
- venus-shared/actors/builtin/power/state.v10.go
- venus-shared/actors/builtin/power/state.v11.go
- venus-shared/actors/builtin/power/state.v12.go
- venus-shared/actors/builtin/power/state.v13.go
- venus-shared/actors/builtin/power/state.v14.go
- venus-shared/actors/builtin/power/state.v15.go
- venus-shared/actors/builtin/power/state.v16.go
- venus-shared/actors/builtin/power/state.v2.go
- venus-shared/actors/builtin/power/state.v3.go
- venus-shared/actors/builtin/power/state.v4.go
- venus-shared/actors/builtin/power/state.v5.go
- venus-shared/actors/builtin/power/state.v6.go
- venus-shared/actors/builtin/power/state.v7.go
- venus-shared/actors/builtin/power/state.v8.go
- venus-shared/actors/builtin/power/state.v9.go
- venus-shared/compatible-checks/api-diff.txt
> feat: optimize ForEachClaim to return only eligible claims

- .github/workflows/common_go.yml
> chore: update golangci-lint to 1.60.1

- venus-shared/api/market/client/api.go
- venus-shared/api/market/client/method.md
- venus-shared/types/api_types.go
The new pr for https://github.com/filecoin-project/venus/pull/6380
fix some comments for struct field and execute ` make api-gen`
> chore: fix some comments for struct field

- pkg/constants/version.go
> chore: bump version to 1.18.0-rc2

- pkg/constants/version.go
> Chore/bump v1.18.0

- pkg/constants/version.go
> chore: bump version to v1.18.1

- pkg/constants/env.go
- pkg/vf3/manifest.go
https://github.com/filecoin-project/lotus/pull/12920
> chore: add f3 env var

- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_docker_image.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
Ubuntu 20.04 runners are getting deprecated.
> chore: update ubuntu 20.04 to ubuntu-latest

- pkg/chain/store.go
- pkg/chainsync/dispatcher/dispatcher.go
- venus-devtool/api-gen/example.go
This PR fixes some spelling mistakes.
Corrects "unmarshaling" to "unmarshalling" in an error message in store.go.
Fixes the import alias from "atmoic2" to "atomic2" in dispatcher.go.
Fixes a typo in a variable name in example.go.
> chore: Fix some typos

- fixtures/networks/mainnet.go
https://github.com/filecoin-project/lotus/pull/13077
> feat: set initial power table for mainnet

- pkg/constants/version.go
> chore: bump version to v1.18.2

- cmd/evm.go
- cmd/f3.go
- cmd/fetch.go
This PR fixes some spelling mistakes.
Corrects "invokation" to "invocation"
Corrects "offest" to "offset"
Corrects "uncorrect" to "incorrect "
> chore: Fix typos

- app/submodule/config/config_test.go
- pkg/repo/fskeystore/fskeystore_test.go
- pkg/testhelpers/message.go
close
fix some typos in comment
> chore: fix some typos in comment
