filecoin-project/venus

- .circleci/config.yml
- build/main.go
Fixes #1911 
- bump CircleCI timeout to 30m
- bump `go test` timeout to 30m
CircleCI runs Linux builds in `xlarge` class containers. CircleCI runs OSX builds in `medium` class containers. Seal performance in the `medium` class is approximately 4x worse (slower) than `xlarge`.
To prevent tests from timing out and failing the build, we need to bump both `go test` timeout and the CircleCI no-output timeout.
Here are some timing metrics from our OSX build:
```
--- PASS: TestSectorBuilder (1489.22s)
--- PASS: TestSectorBuilder/concurrent_AddPiece_and_SealAllStagedSectors (595.14s)
--- PASS: TestSectorBuilder/concurrent_writes (483.24s)
--- PASS: TestSectorBuilder/add,_seal,_verify,_and_read_user_piece-bytes (121.69s)
--- PASS: TestSectorBuilder/sector_builder_resumes_polling_for_staged_sectors_ …
```
> bump timeouts to accommodate slow osx build container

- filnet/bootstrap.go
- filnet/bootstrap_test.go
Talking with @anacrolix it is a bad thing to kill the bootstrapping context early.  This should only go down when the node goes down.
> don't stop bootstrapping 20s in please

- README.md
Fixes #1949 
The `rust-toolchain` file (https://github.com/filecoin-project/rust-proofs/blob/master/rust-toolchain) contains `nightly-2018-12-06`.
The `nightly-2018-12-06` version corresponds to Rust 1.31.0 (https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1310-2018-12-06).
The `install-rust-proofs.sh` script invokes `cargo`, which should read the contents of `rust-toolchain` file to download and install the appropriate version of Cargo, Rust, and so forth. It doesn't appear to be the case that this is working in @markwylde 's environment.
This PR updates the readme to point to the version of Cargo required by `nightly-2018-12-06`. This PR is a stopgap. We need to figure out why the `rust-toolchain` file was not used when @markwylde built rust-proofs.
> point to Cargo 1.31.0 in README

- chain/default_store.go
This PR adds logging around the status of loading the chain from disk, example logs produced:
```
13:14:27.994  INFO chain.stor: start loading chain at tipset: { zDPWYqFCvRYC8zKuB9enFLJhzSopGCXBBxR7y15KoerNJDUupEW3 zDPWYqFD6dmjamu4Mw4sRwFkPa7uvKYddWzmZeHE3BSqZXn2ZXSK }, height: 1597 default_store.go:119
13:14:30.374  INFO chain.stor: load tipset: zDPWYqFD4Y8kwX6k7mWyaMKV2Z8JNjRe6dAXvqMJhPuDqQfmA3We, height: 1100 default_store.go:124
13:14:31.296  INFO chain.stor: load tipset: zDPWYqFCraB24f7bfwS3jxYZ7Nd3ZC4fPuPAQ5zRz1M1ZoXLGwoj, height: 900 default_store.go:124
13:14:33.991  INFO chain.stor: load tipset: zDPWYqFD3hTcZQev2D5TpRLMQobmgKTb75BnJZw1LDTCiLFLcTSS, height: 300 default_store.go:124
13:14:34.804  INFO chain.stor: load tipset: zDPWYqFD24Wofr7F3tRTVV1UjtYV3vrCKhRthBc4dsu5CiRAY2QQ, …
```
> add logging to chain loading from disk

- .gitignore
- README.md
- scripts/install-rust-proofs.sh
Remove the need for a github token in install-rust-proofs.sh, since the
repository is now open and the token is no longer needed.
Resolves #1981
> Remove github token from install-rust-proofs.sh and change default README instructions

- commands/daemon_daemon_test.go
Closes #1972:  daemon zombies after test runs
Make sure defer daemon.ShutdownSuccess() is paired with every call to Start() -- turns out there were two that did not, and what do you know, two stray processes are left behind after each test run.
> Make sure defer daemon.ShutdownSuccess() is paired with every call to Start()

- package.json
Missing it in the manifest. Not sure if this is how GX reads it (cc @whyrusleeping), but I'm going off of [this example from @kemitchell](https://www.npmjs.com/package/dual-licensed-package).
> docs: Add dual license

- api/impl/mining.go
- config/config.go
- config/config_test.go
- mining/worker.go
- mining/worker_test.go
- node/node.go
- node/node_test.go
- node/testing.go
- repo/fsrepo_test.go
- wallet/wallet.go
Part 1 of 3 for #1054 
1. In node.CreateMiner, generate a public/private key pair.  This will be the keypair for signing blocks and tickets. Store it in node.Wallet.  Alter the node's Mining config to store the block signer address so the keyinfo can be used.
This assumes that there will be only one block miner;  if a subsequent call to CreateMiner is performed, right now it will simply generate a new key pair and overwrite the old one. I think this should be fine (?) since we will be publishing the minerAddress and its public key for verification in the block -- just not with this PR.
1. Add two parameters for a mining DefaultWorker struct and instantiation:
* `blockSigningAddr address.Address`  -- this will be the address for the keypair generated above
* `blockSigner types.Signer` -- …
> Part 1/3 Tickets --> Signed tickets #1054

- build/main.go
- chain/default_store_test.go
- chain/default_syncer_test.go
- chain/get_ancestors_test.go
- chain/power_table_view_test.go
1. Fixes #1828 , flaky `TestTipSetWeightDeep` in default_syncer_test.go
1. puts chain tests into their own package so they can be run individually simply with 
`go test <filename>`
or even specify a single test case like a civilized person such as
`go test <filename> -run <simple regex>"` 
This is another argument in favor of not making tests part of the package they are testing.
1. Also adds another build command, "fbuild" which forces a build of everything (including deps), which I added while debugging unrelated environment issues.
> Bugs/flaky testtipsetweightdeep #1828

- api/impl/client.go
This should make importing data much, much faster.
Fixes https://github.com/filecoin-project/go-filecoin/issues/1222
> client import: Use BufferedDAG

- README.md
I have also updated https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started with a note about runtime generation of these parameters if missing.
Closes #2008.
> Add note to README about slow proof parameter download or generation in deps.

- .gitignore
- build/main.go
- scripts/install-rust-proofs.sh
has `deps` use `paramfetch` to pull any predefined parameters from ipfs before generating any missing ones with `paramcache`
> use paramfetch before paramcache

- Dockerfile
`libfilecoin_proofs.so` and `libsector_base.so` have not been produced by the build for a while now.
> #2009: remove COPY statement for files that are no longer used

- .circleci/config.yml
- Dockerfile.ci.base
- Dockerfile.ci.faucet
- Dockerfile.ci.filecoin
- Dockerfile.ci.genesis
Opened in favour of https://github.com/filecoin-project/go-filecoin/pull/1992 to create a cleaner commit history. Contains same changes
---
* add an extra step in circle config to generate faucet and genesis-file-server and persist to workspace
* attach workspace and param cache to build_docker_img
* COPY binaries and params to docker image
* build go-filecoin container last to avoid adding params to faucet and genesis-file-server docker context
* make build_docker_img dependent on build_faucet_and_genesis
* remove rust dependencies from base docker image
the intention of these changes is to speed up the docker build time and make the docker image smaller
---
Passing build with these changes https://circleci.com/workflow-run/02b50237-2046-4aa3-86a0-53f16f10b43d
> Circle docker enhancements v2

- Dockerfile.ci.filecoin
prevents docker build from throwing an error if symlink already exists.
also see https://github.com/filecoin-project/go-filecoin/issues/2013
> force params.out symlink to filecoin-proof-parameters

- scripts/copy-groth-params.sh
currently, if the symlink already exists, it throws an error.
see https://github.com/filecoin-project/go-filecoin/issues/2013
> force symlink in copy_groth_params

- plumbing/ps/testing.go
- porcelain/mpool_test.go
Inspired by @travisperson's [patch](https://gist.github.com/travisperson/58535622ee84517fb4b5cb77495ef9f0). This resolves a race to post the second pubsub message (to an unbuffered channel) against inspection of `MessagePoolPending` and polling the first message from that channel. Also adds another test exercising a second possible interleaving.
Closes #2059. Obviates #2088.
@acruikshank please commandeer/merge immediately so we can un-flake the tests if this looks ok to you. cc @phritz in case you want to review and merge before AC starts work.
> Fix race in TestMessagePoolWait.

- .circleci/config.yml
run lint step after installing dependencies and saving them to cache.
gometalinter is installed by dependencies step so this step can't be any earlier
> perform lint step before build and test steps

- scripts/install-rust-fil-proofs.sh
Closes https://github.com/filecoin-project/go-filecoin/issues/2083.
(Stopping the script is the right thing to do but I need to be more careful in checking how does that interact with the rest of the setup. Doing a quick revert now to unblock @laser, a better solution can be figured out later.)
> Revert "rust: stop install script if anything fails"

- scripts/install-bls-signatures.sh
- scripts/install-rust-fil-proofs.sh
Fixes #2081.
The two install scripts `git submodule update init` _all_ submodules instead of the minimum required by the script.
> scope submodule update init to relevant subdirectories

- core/message_pool.go
- core/message_pool_test.go
- mining/block_generate.go
- mining/block_generate_test.go
- mining/worker.go
This is a prefactor for work on #1751 ordering by gas price. I've moved OrderMessagesByNonce next to its only caller.
In the long term, we may want to move sophisticated message queueing inside the messages pool, but until performance requires it, let's keep the pool simple.
> Move core.OrderMessagesByNonce to mining.SelectMessagesForBlock and simplify tests.

- api/address.go
- api/impl/address.go
- commands/address.go
- commands/address_daemon_test.go
- gengen/main.go
- testhelpers/iptbtester/genesis.go
- tools/fast/action_wallet.go
This PR aligns the type `go-filecoin wallet export --enc=json` returns and the type `go-filecoin wallet import` expects. 
#2024 was caused by the `export` command returning:
`{"privateKey":"xVHXgLfpcJ6kisQONRelKHA5DuY+cpIvTTK9K3utxDI=","curve":"secp256k1"}`
And the `import` command expexting:
`{"KeyInfo":[{"privateKey":"xVHXgLfpcJ6kisQONRelKHA5DuY+cpIvTTK9K3utxDI=","curve":"secp256k1"}]}`
closes #2024
> correctly export wallet data

- .circleci/config.yml
- proofs/sectorbuilder/testing/interface_test.go
Skip the slow proofs tests, only running them 4x times a day on CI.
Resolves #1976
> Skip slow proofs tests, only run 4x a day

- .circleci/config.yml
- proofs/sectorbuilder/testing/interface_test.go
We only run proofs tests 4x a day, since they takes much much longer
than the rest of the test suite.
To run them, one can set the `FILECOIN_RUN_SECTOR_BUILDER_TESTS`
environment variable to `"true"`.
> Only run proofs text 4x a day

- commands/address.go
- commands/address_daemon_test.go
Resolves #2004 
The `wallet export` command with `--enc=json` will still only return the private key and the curve used, since this command is designed to write files suitable for consumption by the `wallet import` command, and isn't really designed for human use.
The `wallet export` command with no encoding specified will still return address, private key, and curve, but the private key will have the same output format as the one used for `--enc=json`.
Some examples:
```
$ ./go-filecoin wallet export fcqtu6574lys8nwsc39h4vpa4k0v7vnyj0xzzhsue
Address:	fcqtu6574lys8nwsc39h4vpa4k0v7vnyj0xzzhsue
PrivateKey:	ehfp0DiWZBqlYK4oBVUIBoAVIPJok4e/SVb5RPpL57E=
Curve:		secp256k1
```
and
```
$ ./go-filecoin wallet export fcqtu6574lys8nwsc39h4vpa4k0v7vnyj0xzzhsue --enc=json | json_pp
{
"KeyInfo" : [
{ …
```
> Make private key output consistent

- api/impl/mining.go
- chain/default_store_test.go
- chain/default_syncer_test.go
- chain/testing.go
- commands/miner_daemon_test.go
- commands/mining_daemon_test.go
- commands/payment_channel_daemon_test.go
- consensus/expected_test.go
- consensus/genesis.go
- consensus/processor.go
- consensus/processor_test.go
- mining/block_generate.go
- mining/worker.go
- mining/worker_test.go
- node/block_propagate_test.go
- node/node.go
- plumbing/msg/waiter_test.go
- porcelain/wallet_test.go
- testhelpers/consensus.go
- testhelpers/core.go
closes #1844
For some time now, we have been paying block rewards and gas payments to the miner actor. These payments should be going to the account actor listed as the miner actor's owner.
This PR switches the address to which the processor directs payments to that of the miner's owner.
The major complication with this is that blocks contain only the miner's address. The miner owner must be queried from the miner actor. This has the additional complication that all test code that attempts to validate a block must have an actor with an owner in state for the miner address specified in the block. Most of the changes in this PR are related to that.
> Pay miner owner instead of miner

- commands/mpool.go
- commands/mpool_daemon_test.go
- core/message_pool.go
- core/message_pool_test.go
- plumbing/api.go
I emulated the output format from `block show`.
```Message Details
To:        fcqp606qfk5gwmq6ac24g4mhv3cr8zzf67vqkpulh
From:      fcq6k3r52n89c0m0nd8sm8cf27srpgephkqkrc9nj
Nonce:     102
Value:     100000
Method:    createChannel
Params:    glYAANrn4y/rt8o+bnah3odFEv661KJWQ+KXAg==
Gas price: 0
Gas limit: 300
Signature: Pzn2NWyHjcO7gc4denBVC64nBb/n7otlEmyyC2g1vHJhM3yufdVl07FmCugC4mQihu5302vxU3SPU3eBDKI5xgA=
Message Details
To:        fcq423mk77skf2tg2542ku6skje9859ecu3z7dmha
From:      fcqunwslgsaa52xuqxlxvpx4km8h2erprz9trc4l3
Nonce:     2
Value:     0
Method:
Params:
Gas price: 1000
Gas limit: 1000
Signature: U3V2tqwZfa5KxH//GdapekmG5icglvddij7S0yR20iVGWGMfbo3hpo8LVbwJcmXe9sj+jpI5bvZSzon427alGgE=
```
Params are "too hard" to decode here without more work. My understanding is that …
> Add mpool show command to show an unmined message detail.

- commands/log.go
This PR add commands:
```
go-filecoin log level <subsystem> <level> - Change the logging level.
go-filecoin log ls                        - List the logging subsystems.
```
Prior art here: https://github.com/ipfs/go-ipfs/blob/master/core/commands/log.go
> add level and ls command to log

- consensus/processor.go
- consensus/validation.go
I updated comments a bit, but there's no semantic change. This unfortunately exposes that there are no unit tests for this code directly (it's exercised
indirectly through processor tests).
This is prework for #1934.
> Extract validator from processor.go to a new validation.go.

- README.md
Some community users running filecoin on AWS instances with 4GB of RAM notice that the daemon will run out of memory. Upping the memory to 8GB resolves the problem, so we are adding this in as a system requirement.
> Add RAM Requirements to README

- actor/builtin/paymentbroker/paymentbroker_test.go
- api/impl/actor_test.go
- api/impl/daemon.go
- api/impl/id_test.go
- api/impl/ping_test.go
- commands/env_test.go
- consensus/expected_test.go
- consensus/genesis.go
- core/testing.go
- node/block_propagate_test.go
- node/init.go
- node/message_propagate_test.go
- node/node_test.go
- node/testing.go
- plumbing/msg/testing.go
- The mockMineMode arg to MakeNodesUnstarted was always true, or could be set true (it installs a fake proof verifier).
- Removed MakeNodesStarted in favour of moving an existing StartNodes where it could be reused.
- Renamed InitGenesis to DefaultGenesis after I finally understood what it did.
This is prework to some more complicated in-process integration test setup I need for #2139.
> Remove unused mockMineMode arg and simplify integration test genesis and node init.

- README.md
- util/version/version.go
- util/version/version_test.go
Filecoin doesn't work with go 1.12 right now: #2167, so we update the
README and version checking code to require the go version to be < 1.12
> Update required go version for filecoin

- commands/message_daemon_test.go
- consensus/validation.go
- node/message_propagate_test.go
- node/node.go
- node/node_test.go
- plumbing/msg/sender.go
- plumbing/msg/sender_test.go
- plumbing/msg/testing.go
- plumbing/msg/waiter_test.go
This is most of the work for #1934 (there are some cases the validator doesn't yet check).
I intend to rebase on #2136 and #2138 before merging, resolving some duplicated actor loading.
>  Plumb message validator to sender and validate outgoing messages before adding them to mpool.

- abi/abi.go
- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- proofs/interface.go
- proofs/rustverifier.go
- proofs/sectorbuilder/interface.go
- proofs/sectorbuilder/rustsectorbuilder.go
- proofs/sectorbuilder/testing/interface_test.go
- proofs/types.go
- protocol/storage/miner.go
- testhelpers/consensus.go
This PR fixes the go-filecoin side of [this rust-fil-proofs issue](https://github.com/filecoin-project/rust-fil-proofs/issues/505).
- modify go-filecoin to conform to [the spec](https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost), which shows `submitPoSt` message receiving multiple PoSt proofs
- modify `generate_post` and `verify_post` CGO calls to return/accept variable number of PoSt proofs
> integrate go-filecoin with new variable proof-producing generate_post and variable proof-consuming verify_post CGO calls

- scripts/install-rust-fil-proofs.sh
fixes: https://github.com/filecoin-project/go-filecoin/issues/2134
just updates the submodule for both local/remote installs
> update submodule when installing rust-fil-proofs

- chain/bad_tipset_cache.go
- chain/default_syncer.go
We mark a chain as bad in the event that a syncOne call on a tipset
returns an error.
Part of resolution of #2155 .
> Mark chain as bad if syncing fails

- commands/main.go
- commands/stats.go
- commands/stats_daemon_test.go
- node/node.go
- node/node_test.go
- plumbing/api.go
- plumbing/ntwk/ntwk.go
In working on figuring out why filecoin is using such an absurd amount of bandwidth (hint: it rhymes with fee age tree), i wrote this to expose libp2p bandwidth metrics.
> add command to track bandwidth usage

- api/client.go
- api/impl/client.go
- commands/client.go
- commands/client_daemon_test.go
- node/block_propagate_test.go
- node/node.go
- node/node_test.go
- plumbing/api.go
- plumbing/strgdls/store.go
- plumbing/strgdls/store_test.go
- porcelain/api.go
- porcelain/storagedeals.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/storage_protocol_test.go
- protocol/storage/storagedeal/state.go
- protocol/storage/storagedeal/types.go
- tools/fast/action_client.go
- tools/fast/series/series_importandstore.go
- tools/fast/series/series_waitfordealstate.go
- tools/fast/tests/retrieval_test.go
We coalesce the the storage of storage deals for both storage miners and storage clients into a single datastore with a single namespace. This allows easy querying of storage deals, regardless of whether one is a miner or client. This also easily allows a miner to obtain vouchers for storage deals that have been successfully executed, thus enabling miner payments with minimal hoop-jumping.
Resolves #1433
> Miner payment management

- actor/actor.go
- actor/builtin/account/account.go
- consensus/processor.go
- consensus/validation.go
An empty actor may be initialised by sending FIL to an address. The actor is not recognized as
an account actor until a message is sent from it's address, at which point it is transparently
upgraded in processing. This change updates the validation logic to reflect that.
I re-ordered the validation and upgrade blocks in the processor to exercise the code. This PR is unfortunately not accompanied by a regression test, which is a bit difficult to construct. I intend to follow up with some plumbing such that an in-process integration test (c.f. `message_propagate_test`) can mine a block and we can test the sequence of sending FIL to a new address, then a message from that address.
Fixes #2184.
> Allow actors with undefined code to send messages.

- repo/fsrepo.go
Resolves #2162
If a user's computer runs out of diskspace while a badger datastore is being written, the datastore will become corrupted. The user can no longer start filecoin with the same repo, as badger will report
```
Error: failed to open datastore: Value log truncate required to run DB. This might result in data loss.
```
and fail to load the datastore.
We use the `Truncate` option for badger datastores so that, in the event a value log corruption occurs, when badger starts up and reads the datastore, it will remove the corrupted value log entry and any data that follows. This allows badger to load the remaining datastore without issue.
If an advanced user restarts a node after a datastore has been corrupted, they will not be able to manually remove the corrupted value log entry and …
> Always use truncate option for badgerds

- crypto/crypto_test.go
We make all entries distinct in the byte array used in the test. This
means the shuffle will (practically) always mutate the message in some
way.
Resolves #2217
> Prevent transient failures of TestGenerateKey

- functional-tests/lib/helpers.bash
- functional-tests/retrieval
Given that the miner's node has already started mining:
```
echo ""
echo "miner node starts mining..."
./go-filecoin mining start \
--repodir="$MN_REPO_DIR" \
```
...all of these calls to `mining once` are superfluous.
> mining once not needed - miner node already started mining

- crypto/crypto_test.go
We need to make all slice entries distinct, not just the first one.
> Fix fix of transient test failure

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- api/impl/mining.go
- chain/default_store.go
- chain/default_syncer.go
- chain/get_ancestors.go
- chain/store.go
- consensus/expected.go
- consensus/processor.go
- exec/exec.go
- node/node.go
- plumbing/api.go
- plumbing/msg/waiter.go
- porcelain/api.go
- porcelain/chain.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- sampling/chain_randomness.go
- sampling/chain_randomness_test.go
- testhelpers/consensus.go
- testhelpers/mining.go
- vm/context.go
- vm/context_test.go
Fixes #1996 
Fixes #1302 
- PoSt generation and verification require a challenge seed
- challenge seed must be created from shared source of randomness (blockchain)
- we need some way to sample randomness from seed from both inside and outside state machine
- provide mechanism for sampling chain randomness from outside state machine (for PoSt generation)
- use chain randomness to generate challenge seed for PoSt verification and generation
- Lookback parameter was once a field on the VM context. It isn't anymore. It's not clear to me why it was both a package variable `LookbackParameter` and also part of the VM context. I can be convinced to put it back to the way that it was.
- If chain randomness sampling height minus lookback results in a null block, we fault. *It's not clear to me …
> PoSt generation and verification should use same challenge seed

- chain/default_store.go
- core/message_pool.go
- core/message_pool_test.go
- mining/worker_test.go
- node/node.go
- plumbing/msg/sender.go
- plumbing/msg/sender_test.go
- testhelpers/core.go
closes #2133
The message pool currently has no invalidation mechanism. Temporary failures and other issues can cause a message to remain in the message pool indefinitely. This also means there's no clean recovery mechanism when several messages are sent and the first message fails.
Add  a timeout mechanism to the message pool. The mechanism involves the following steps:
1. Store `timedMessages` instead of just messages. `timedMessages` are a message plus a block height.
2. On `UpdateMessagePool`, search `MessageTimeOut` tipsets back in the chain to get the timeout block height.
3. Remove every message in the `pending` map that has a block height below the timeout.
It's important that the timeout block height be based on the number of tipsets seen, rather than a specific block height. It's …
> Timeout messages from message pool

- core/message_queue.go
- core/message_queue_test.go
This is the core of #2146.
This is not yet integrated into the message sender plumbing, which will provide values for chain height,
or chain syncing, which will remove/expire messages.
> Initial implementation of outbound message queue, including expiry mechanism

- api/impl/daemon.go
- build/main.go
- config/config.go
- config/config_test.go
- node/node.go
- protocol/hello/hello.go
- protocol/hello/hello_test.go
- repo/fsrepo_test.go
A way less crazy way to resolve #2182 
Users can easily join the user devnet with the wrong version of the filecoin codebase
Require a specific code version for user devnet in the hello protocol. This version specifier is capable of being overwritten during build time if a developer needs to test something with a different code version.
Additionally:
- Clean up some redundant or repetitive code in daemon.Init
- Bolster checks for using multiple `devnet` flags at once
> Simple way to guard user devnet

- .circleci/config.yml
config validator started complaining and build error appearing seemingly randomly
$ circleci config validate
Error: ERROR IN CONFIG FILE:
[#/parameters/sector_builder_tests_param] 3 schema violations found
1. [#/parameters/sector_builder_tests_param] required key [default] not found
2. [#/parameters/sector_builder_tests_param] required key [type] not found
3. [#/parameters/sector_builder_tests_param] extraneous key [sector_builder_tests] is not permitted
s/parameters/params/ fixes error so assuming parameters has become a reserved top level key
relates to https://github.com/filecoin-project/go-filecoin/issues/2275
> change parameters yaml key to params

- Dockerfile.ci.faucet
- Dockerfile.faucet
Add missing dynamic libraries to faucet image. 
Still investigating why these weren't needed until now, but this should unblock nightly deployments https://github.com/filecoin-project/go-filecoin/issues/2283
> include required libs in faucet image

- node/node.go
https://github.com/filecoin-project/go-filecoin/commit/11c3025255f75defe5950262e48948ce112b78ae removes chainReader and uses chainStore instead.
replaces deprecated chainReader reference with chainStore
likely caused by master merge contention
> chainReader should be chainStore

- commands/chain_daemon_test.go
- types/uint64.go
- types/uint64_test.go
This reverts commit 4940e56f5124b51d87c2662ff3fcffbca6dc9129.
This fixes failure of `TestChainDaemon/chain_ls_--long_with_JSON_encoding_returns_integer_string_block_height_and_nonce`, added in this commit, that's currently failing on master.
cc @mslipper @travisperson I'm not sure what happened here
> Revert "Serialize Uint64 to string in JSON (#2229)"

- chain/traversal.go
- chain/traversal_test.go
- core/message_pool.go
- core/message_pool_test.go
- core/message_queue.go
- node/node.go
- types/sorted_cid_set.go
My primary goal here is to factor chain traversal out of the MessageQueue so I can re-use
logic for collecting new/old messages in the case of a re-org and expire messages in the
outbound queue. I'm informed the iterators may be useful elsewhere too.
> Implemented chain tipset and block iterators.

- chain/default_store.go
- chain/default_syncer.go
- chain/default_syncer_test.go
- chain/get_ancestors_test.go
- chain/store.go
- net/bootstrap.go
- net/fetcher.go
- net/fetcher_test.go
- net/testing.go
- node/block.go
- node/node.go
- protocol/block/api.go
- protocol/block/api_test.go
- types/message.go
did some refactoring and cleanup on the chain sync/store code to make it use bitswap sessions.
As currently written in master, we request every block from every person we are connected to, resulting in an obscene amount of bandwidth overhead. We need to fix that ASAP.
This PR improves it a bit, further improvements may be needed.
> Use bitswap sessions for block fetching

- commands/address.go
- commands/address_daemon_test.go
- commands/miner_daemon_test.go
- functional-tests/faucet_test.go
- testhelpers/commands.go
Gone!:
```console
$ ./go-filecoin wallet --help
USAGE
./go-filecoin wallet - Manage your filecoin wallets
SYNOPSIS
./go-filecoin wallet
SUBCOMMANDS
./go-filecoin wallet balance <address>     - 
./go-filecoin wallet export <addresses>... - 
./go-filecoin wallet import <walletFile>   - 
Use './go-filecoin wallet <subcmd> --help' for more information about each command.
```
resolves #1693
> refactor: remove wallet addrs command

- .circleci/config.yml
- scripts/build-bundle.sh
- scripts/publish-release.sh
Implements https://github.com/filecoin-project/go-filecoin/issues/2171
- Include `paramfetch` binary and `parameters.json` in the GH bundle
- Update WIKI to reflect changes: https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-binary
> include paramfetch and parameters.json in GH release bundle

- api/client.go
- api/impl/client.go
- commands/client.go
- porcelain/api.go
- porcelain/client.go
- porcelain/client_test.go
- state/tree.go
- tools/fast/series/create_miner_with_ask.go
- tools/fast/series/import_and_store.go
- tools/fast/series/set_price_ask.go
We want to remove the `api` directory, but Client ListAsks is part of it
Moved Client ListAsks to porcelain
Resolves #1802
> Moved Client ListAsks from node api to porcelain

- api/client.go
- api/impl/client.go
- commands/client.go
- plumbing/api.go
- plumbing/dag/dag.go
We want to remove the `api` directory, but `Client().Cat()` is part of it.
Move `Client().Cat()` to DAG plumbing, where it makes sense.
Resolves #1955
> Moved Client Cat from node api to plum pork

- Dockerfile
- Dockerfile.faucet
- Dockerfile.genesis
- package.json
Update Dockerfiles to use go 1.12.1 because a previous PR has upgraded
the version of go required to build.
Resolves #2322
> Update Dockerfiles to use go 1.12.1

- abi/abi.go
- actor/builtin/miner/miner.go
- functional-tests/lib/helpers.bash
- functional-tests/retrieval
- proofs/sectorbuilder/testing/interface_test.go
- protocol/storage/miner.go
Fixes #1586 
1. Consume new version of rust-fil-proofs which performs real PoSts!
1. Expose bootstrap actor-boolean outside of the state machine so that bootstrap miners don't try to generate PoSts over fake commitments (created by gengen in genesis block).
1. Modify retrieval test such that it exercises seal proof verification, PoSt generation, and PoSt verification.
1. We want storage miners to exercises the PoSt generation and verification code
1. We want some automated tests exercising the PoSt generation, PoSt verification, and seal proof-verification code (modifications to retrieval test)
```
-----------------------------------------------
commit 002597027d8e720cb8010919915d704b97740e5d
Author: Erin Swenson-Healey <l@s3r.me>
Date:   Mon Mar 18 05:32:16 2019 -0700
Feat/gf1586 …
```
> integrate go-filecoin with real PoSt generation and verification routines

- tools/fast/bin/localnet/main.go
Accidentally snuck a `address.Address{}` in.
> localnet: Use a defined address for sector builder

- api/client.go
- api/impl/client.go
- commands/client.go
- plumbing/api.go
- plumbing/dag/dag.go
We want to remove the `api` directory, but `Client().ImportData()` is a part of it.
Move `Client().ImportData()` to DAG plumbing, where it makes sense.
Resolves #1956
> Moved Client ImportData from node api to plum pork

- core/chains.go
- core/message_pool.go
Part of #2146.
This code is now testable in isolation, but only exercised via mpool tests. I'd love to add more tests soon, but on a deadline for re-using this code in the outbound queue.
> Factor out message pool traversals to extract re-usable logic for the outbound queue

- .circleci/config.yml
using git, clone go-filecoin-badges and update appropriate badge.
requires FILECOIN_BINARY_VERSION environment variable to be set in job context
> badge_update command to update go-filecoin-badges on nightly release

- chain/testing.go
- chain/traversal_test.go
- core/chains.go
- core/message_queue.go
- core/message_queue_test.go
- core/policy.go
- core/policy_test.go
- node/node.go
- types/testing_messages.go
Note that the sender does not yet put messages in the outbox, so the queue is always empty at the moment.
I think we can do better than "policy" for that object, but want the name to stay somewhat meaningful (not "manager"). Suggestions welcome.
Closes #2209.
> Hook up expiry of messages from the outbound queue (outbox)

- .circleci/config.yml
fails to install otherwise.
see failing build https://circleci.com/gh/filecoin-project/go-filecoin/12815
> HOTFIX: need sudo to install jq and git and circle build step

- types/block_test.go
- types/message.go
- types/message_test.go
- types/metered_message.go
- types/metered_message_test.go
- types/signed_message.go
- types/signed_message_test.go
- types/testing.go
I need this for runtime checks that messages mined into blocks are identical to the message sent by a node.
I could alternatively use `CID()` for the inner Message, but it looks like that would be slower with adding extra complexity to cache the CID etc.
CC @whyrusleeping
> Implement Equals() method for Message, MeteredMessage and SignedMessage

- core/policy.go
- core/testing.go
- node/node.go
- node/node_test.go
- plumbing/msg/sender.go
- plumbing/msg/sender_test.go
The sender now uses the outbound queue for nonce calculation. Inbox/outbox terminology suggested by @rosalinekarr, and I think we could push it further. Closes #2146.
@acruikshank this about finishes the hookup of the outbound queue (still to add a status command and msgwait equivalent). Not for this PR, but we can discuss more cohesion with the message pool.
- I think the `Sender` is doing too much work for a bit of plumbing and could be factored out next to the message pool/queue implementations
- I would also extract UpdateMessagePool next to the the outbound queue expiry policy thingy
> Hook up message sender to put messages in outbound queue

- plumbing/dag/dag.go
In #2321, I removed a TODO comment by mistake.
Add it back with an additional link to it's associated github issue.
> Re-added TODO comment removed from plumbing DAGCat

- chain/default_syncer.go
- functional-tests/lib/helpers.bash
- functional-tests/retrieval
Fixes #2315 
Fixes #2348 
- modify chain synchronizing code to write to logger instead of stdout
- add timeout (seconds) to `wait_for_message_in_chain_by_method_and_sender` function
- query chain using single `jq` invocation on entirety of NDJSON response instead of one query per line
- fix bug in `wait_for_message_in_chain_by_method_and_sender` which caused it to ignore tip sets containing a block with a `null` `messages` property
> Bugs/2315-and-2348 fix retrieval script + remove fmt.Printf

- commands/client_daemon_test.go
- testhelpers/commands.go
Resolves #1873 
Test would fail with "ask not found" when the storage client would attempt to propose a storage deal
Wait for the storage client node to see the AddAsk message generated by the storage miner node before making the storage deal proposal.
> Fix Flaky TestStorageDealsAfterRestart

- .circleci/config.yml
- DEPLOY.md
re-uses circleci commands introduced by new nightly deploy process.
uses git tag for docker image and deploy docker tag to devnet.
makes user/test devnet deploy be triggered by git tag
> Temporarily target test rather than user devnet to dry run parameterized deploys

- commands/retrieval_client.go
- node/node.go
- protocol/retrieval/api.go
- protocol/retrieval/retrieval_protocol_test.go
Closes #2304 : remove the dependency on porcelain and add the miner peerid as a parameter to retrievalAPI.RetrievePiece. Opted to leave the API there instead of getting rid of it since we will likely add other functions, and also because symmetry.
> remove dependency on porcelain for retrieval protocol api

- .circleci/config.yml
if any file sets xtrace, fail the build to prevent accidentally leaking credentials
tested regex like this:
```
$ echo "set -x" | grep '^set\ \-\w*[x]\w*' && echo "fail" || echo "pass"
set -x
fail
$ echo "set -ex" | grep '^set\ \-\w*[x]\w*' && echo "fail" || echo "pass"
set -ex
fail
$ echo "set -xtrace" | grep '^set\ \-\w*[x]\w*' && echo "fail" || echo "pass"
set -xtrace
fail
$ echo "set -e" | grep '^set\ \-\w*[x]\w*' && echo "fail" || echo "pass"
pass
```
> check if xtrace is enabled in bash scripts

- tools/fast/bin/localnet/README.md
- tools/fast/bin/localnet/main.go
Add support to specify the `go-filecoin` binary that will be used instead of requiring the user to build. However, for easy of use for developers, localnet will default first to the binary in the project directory, then fallback to searching the $PATH.
The binary that will be used will be printed as the default.
_binary built in the go-filecoin project_
```
Usage of ./localnet:
-binpath go-filecoin
set the binary used when executing go-filecoin commands (default "/home/travis/src/github.com/filecoin-project/go-filecoin/go-filecoin")
```
_binary **not** built in the go-filecoin project, but found in path_
```
Usage of ./localnet:
-binpath go-filecoin
set the binary used when executing go-filecoin commands (default "/home/travis/bin/go-filecoin")
```
_no binary found anywhere. Running …
> localnet: Binary flag and README

- .circleci/config.yml
otherwise the circleci build fails on the second checkout
> fetch all tags in build_faucet_and_genesis step

- chain/default_store_test.go
- chain/default_syncer_test.go
- chain/get_ancestors_test.go
- chain/reorg_test.go
- chain/traversal_test.go
- core/policy_test.go
- node/node_test.go
- plumbing/msg/waiter_test.go
- testhelpers/chain.go
This unblocks me from completing #2371 , to wit:
```
can't load package: import cycle not allowed
package github.com/filecoin-project/go-filecoin/porcelain
imports github.com/filecoin-project/go-filecoin/plumbing
imports github.com/filecoin-project/go-filecoin/chain        <---|
imports github.com/filecoin-project/go-filecoin/testhelpers  <---|  grrrrrrr
imports github.com/filecoin-project/go-filecoin/net
imports github.com/filecoin-project/go-filecoin/commands
imports github.com/filecoin-project/go-filecoin/node
imports github.com/filecoin-project/go-filecoin/porcelain
import cycle not allowed
```
After seeing this deep import cycle error, I got fed up and moved chain/testing.go to the testhelpers package.  We already have multiple test packages which import `testhelpers`, so there is …
> move chain/testing.go to testhelpers/chain.go 

- commands/chain.go
- commands/chain_daemon_test.go
The way this PR currently stands with commit 07f31c225fdafc6a497f3189ddf062c11ca56410 we get the following outputs:
```
frrist@pine ~/s/g/f/go-filecoin (feat/fix-chain-head-2392)> ./go-filecoin chain head
zDPWYqFCrMH36tQoVUiLrAaC4GCwK4KefHL9JZXxGkcDZq3gTKLt
frrist@pine ~/s/g/f/go-filecoin (feat/fix-chain-head-2392)> ./go-filecoin chain head --enc=json
[{"/":"zDPWYqFCrMH36tQoVUiLrAaC4GCwK4KefHL9JZXxGkcDZq3gTKLt"}]
```
The JSON encoding will fail if round tripped -- `[{"/":"zDPWYqFCrMH36tQoVUiLrAaC4GCwK4KefHL9JZXxGkcDZq3gTKLt"}]` isn't valid json
I propose that instead of returning a slice of CID's we return a slice of tipsets, gut check says this was the original behaviour, although I am not seeing that change reflected in the git history, was in a bit of a hurry could have missed it.
lets …
> fix chain head

- README.md
Since Go 1.11, it's possible to [pass a directory name to go run](https://golang.org/doc/go1.11#run). Use this terser syntax in the installation instructions.
> Use terser go run directory name in README

- .circleci/config.yml
combining publish and deploy workflow reduces duplicated build_linux jobs running, increasing execution time.
allow targetting test-devnet OR user-devnet to add permanent test-devnet Continuous Deployment capabilities
> Combine publish and deploy workflow; add test-devnet target

- .circleci/config.yml
the  prefix was optional, a regression from yesterday's refactor adding test-devnet as a permanent deploy target
> fix test-devnet workflow tag filtering

- functional-tests/retrieval
Currently, the timeout for waiting for commitSector/SubmitPoSt messages in the retrieval script is 120 seconds. This is not adequate when the script is configured to use normal-sized sectors instead of small ones. @laser has said that a timeout of 3600 should be adequate. We modify the retrieval script to use this timeout when the script is configured to use normal-sized sectors.
Resolves #2415
> Different Timeout for Normal-Sized Sectors in Retrieval Script

- .golangci.yml
- README.md
- build/main.go
- consensus/expected_test.go
- metrics/heartbeat_test.go
- porcelain/miner_test.go
- porcelain/mpool_test.go
- porcelain/wallet_test.go
- proofs/sectorbuilder/testing/interface_test.go
- repo/fsrepo_test.go
- tools/fast/series/connect.go
- tools/iptb-plugins/filecoin/docker/iptb_metrics.go
- tools/iptb-plugins/filecoin/util.go
This also switches to a single lint stage because the linters run in ~10s (on my machine, at least).
fixes #2207 
(currently based off #2305)
> build: switch to golangci-lint

- README.md
We add documentation for the FILECOIN_OVERRIDE_BUILD_SHA environment
variable that can be used during build time to allow a filecoin node
with different code to join the user or test devnet.
This is partially in response to questions prompted by #2462.
> Document FILECOIN_OVERRIDE_BUILD_SHA

- build/main.go
Fix the install command in the build script, as it currently:
- Doesn't work at all
- Won't include the code version during the build process
This may help resolve issues like #2458 in the future.
> Fix install command in build script

- chain/default_syncer.go
- chain/default_syncer_test.go
- chain/syncer.go
- node/block.go
- node/node.go
closes #2424
We currently only wait for 1 second before timing out when fetching a block for chain syncing. This is a network call and should be increased on principle. We have observed many of these timeouts when bringing up the new user net, so we now know it should be longer.
Increase the timeout to 30 seconds. We don't know of any reason why this should not be 30 times longer and it should greatly reduce these timeouts.
> extend block retrieval timeout

- proofs/sectorbuilder/bytesink/fifo.go
- proofs/sectorbuilder/bytesink/interface.go
- proofs/sectorbuilder/interface.go
- proofs/sectorbuilder/rustsectorbuilder.go
- proofs/sectorbuilder/testing/harness.go
- proofs/sectorbuilder/testing/interface_test.go
- protocol/storage/miner.go
- tools/fast/tests/retrieval_test.go
Fixes #2463 
**This PR cannot be merged until [this upstream rust-fil-proofs PR is merged](https://github.com/filecoin-project/rust-fil-proofs/pull/580)**!
1. `SectorBuilder#AddPiece` now provisions named pipe and passes path to CGO call.
1. Rust function (CGO call) now opens path and streams bytes from file to its preprocessor
Previously, go-filecoin would copy piece-bytes from block store into buffer, then allocate buffer in Rust heap, then copy from Go heap into Rust heap, then make CGO call. That took a lot of RAM.
- Running through the add-piece flow (via `client propose-storage-deal`) for a 254MiB piece would cause the storage miner process to spike RAM to ~1260MiB on my laptop.
- With streaming in place, that number reduces to ~800MiB.
- My idle miner consumes ~600MiB (by …
> Streaming add piece through FFI

- commands/main.go
- commands/version_daemon_test.go
Currently, `go-filecoin version` command has to run after daemon has
started.
This is undesirable.
> make version command not depend on daemon

- tools/iptb-plugins/filecoin/local/copy_file.go
- tools/iptb-plugins/filecoin/local/copy_file_linux.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
When using FAST sometimes an error will be returned about a binary being busy. This appears to be related to a bug being tracked in golang (https://github.com/golang/go/issues/22315) due to an issue around file descriptors being held onto longer than needed inside of threads.
This fix uses the `cp` binary to due the copying in linux.
> IPTB: Work around for golang bug #22315

- commands/payment_channel.go
- tools/fast/action_paych.go
Exports the payment channel types so we can parse the command responses in FAST.
None Goal: support preview.
> Export payment channel result types

- .github/ISSUE_TEMPLATE/bug_report.md
When bugs deal with building a lot of the time the build errors are due to incorrect versions of dependencies, and requests for this information is commonly the first comment. To help reduce the time to resolving the issue I think we should request this information up-front in the issue template.
Another common issue is around connecting to the network, and most issues do not properly fill out the steps to reproduce. I've added explicit request for the `init` and `daemon` commands in the steps.
Are there any additional information we would like to add to the bug report form to help reduce the time to resolve issues?
/cc @anorth @laser @mishmosh
> Update bug report template to include version info request

- tools/fast/bin/localnet/main.go
- tools/fast/series/ctx_mining_once.go
- tools/fast/series/ctx_sleep_delay.go
- tools/fast/series/send_filecoin_from_default.go
- tools/fast/series/set_price_ask.go
- tools/fast/series/setup_genesis_node.go
- tools/fast/tests/retrieval_test.go
FAST is design to be a multi-purpose library for controlling Filecoin daemon for use in automation and testing. When writing some test we need explicit control over when mining occurs. To enable the use of series across synchronous and asynchronous mining (`mining start` vs `mining once`) we need to be able to call `mining once` inside of series when a block is required to be mined.
This PR supports this by providing a way for consumers to set a function on a context which when called will mine a block. Series can use the `MiningOnceFromCtx` to ensure that a block is mined when required.
> FAST: support synchronous mining in FAST series

- actor/builtin/miner/miner.go
- go.mod
- node/node.go
- proofs/interface.go
- proofs/rustverifier.go
- proofs/sectorbuilder/rustsectorbuilder.go
- proofs/sectorbuilder/testing/builder.go
- proofs/sectorbuilder/testing/harness.go
- proofs/sectorbuilder/testing/interface_test.go
- tools/fast/bin/localnet/main.go
Makes incremental progress towards #2530.
- rename "SectorStoreType" to "ProofsMode"
- the old name didn't make sense
> rename "sector store type" to "proofs mode"

- chain/default_store.go
- chain/store.go
- consensus/validation.go
- consensus/validation_test.go
- core/message_pool.go
- core/message_pool_test.go
- core/testing.go
- mining/worker_test.go
- node/message.go
- node/node.go
- plumbing/msg/sender.go
- plumbing/msg/sender_test.go
- testhelpers/core.go
- types/helpers.go
- types/testing.go
closes #2517
partially addresses #2500
closes #2256
We have no pre-validation on the message pool. This means any random message can land in the message pool and waste space. Because there are several types of message error that prevent us charging gas, an attacker can easily spam the message pool with message that they know will never cost any Filecoin.
Add validation to the message pool. This:
1. Limit total number of messages allowed in message pool at any time.
2. Drop messages sent to self.
3. Drop messages with gas limit greater than block limit.
4. Drop messages where actor has insufficient funds to cover gas.
5. Drop messages with invalid actor cid.
6.  Drop messages without valid signatures.
7. Drop messages with duplicate nonce.
8. Drop messages with delta between nonce and …
> Add pre-validation to message pool

- address/address_test.go
- commands/address_daemon_test.go
- consensus/processor_test.go
- functional-tests/faucet_test.go
- testhelpers/testflags/flags.go
This PR adds 3 flags that may be used to control when certain categories of tests run.
- `-functional`: used to run tests like the Retrieval test
-  `-integration`: used to run tests like `*test_daemon.go` or faucet tests
-  `-unit`: used to run tests like `address_test.go`. The `-short` flag may be used interchangeably here.
There are 4 methods that may be called from a test that allow it to run when one of these flags is passed.
- [`FunctionalTest`](https://github.com/filecoin-project/go-filecoin/pull/2542/files#diff-1333f33210e4ae54e705a0b204ce2632R21)
- [Example Usage](https://github.com/filecoin-project/go-filecoin/pull/2542/files#diff-798479df3f7c6278d71f2744dd572c03R32)
- [`IntegrationTest`](https://github.com/filecoin-project/go-filecoin/pull/2542/files#diff-1333f33210e4ae54e705a0b …
> Add Functional Integration and Unit test flags

- config/config.go
- config/config_test.go
- consensus/validation.go
- consensus/validation_test.go
- core/message_pool.go
- core/message_pool_test.go
- mining/worker_test.go
- node/node.go
- plumbing/msg/sender_test.go
- repo/fsrepo_test.go
- testhelpers/core.go
This PR is a follow on to https://github.com/filecoin-project/go-filecoin/pull/2522, it allows the message pools max size to be set via the configuration file.
> message pool max size config based

- .circleci/config.yml
- CODEWALK.md
- README.md
- gengen/util/gengen_test.go
- proofs/sectorbuilder/testing/interface_test.go
- testhelpers/testflags/flags.go
This PR disable `integration` and `functional` tests by default, updates CI to pass the required flags, and updates the documentation on testing flags.
> update docs on testing flags pass in CI

- Dockerfile
- Dockerfile.ci.base
- Dockerfile.ci.filecoin
- copy test and live genesis files to final image
- add build-time args (default to yes) for using precompiled rust-fil-proofs and bls-signatures
- reuse groth params if already downloaded under `$SRC_DIR/tmp/filecoin-proof-parameters
- don't build faucet and genesis-file-server since those have their own Dockerfile
> Dockerfile genesis fix and tweaks

- functional-tests/faucet_test.go
having the binary check in an init function resulted in errors when '-functional=false' in 'go test'
> move binary check to test function

- README.md
no longer needed since making repository open-source
> remove circleci api token from status badge

- actor/builtin/paymentbroker/paymentbroker.go
- actor/builtin/paymentbroker/paymentbroker_test.go
- commands/client.go
- commands/payment_channel.go
- commands/payment_channel_daemon_test.go
- plumbing/strgdls/store_test.go
- porcelain/api.go
- porcelain/payment_channel.go
- porcelain/payment_channel_test.go
- porcelain/payments.go
- porcelain/payments_test.go
- protocol/storage/api.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- protocol/storage/miner_test.go
- protocol/storage/storage_protocol_test.go
- protocol/storage/storagedeal/types.go
- types/payment_voucher.go
- types/payment_voucher_test.go
**What's in this PR?**
move paymentVoucher to /types
modify all paymentbroker.PaymentVoucher to types.PaymentVoucher in all files
create a simple test for PaymentVoucher which encodes then decodes a PaymentVoucher and check 
if it is equal to the original one
> Payment Vouchers should be a first class type issue#2527

- commands/daemon.go
- repo/fsrepo.go
- repo/fsrepo_test.go
Closes #2587 
A lot of this was already done.
This PR simply improves error messages in the case the version is invalid for a given binary.
(It also does some unrelated cleanup)
> Improve repo version checking

- abi/abi.go
- actor/builtin/paymentbroker/paymentbroker.go
- actor/builtin/paymentbroker/paymentbroker_test.go
- commands/payment_channel.go
- porcelain/api.go
- porcelain/payment_channel.go
- porcelain/payment_channel_test.go
- porcelain/payments.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- types/payment_voucher.go
- types/payment_voucher_test.go
In general the payers of payment channels should be able to make payments conditional on something provable on chain. In specific clients need to make payments to miner conditional on whether miners are storing their files.
This PR lays the groundwork for conditional vouchers by introducing a `condition` field to payment vouchers. It saves testing conditions and creating meaningful conditions for future work.
All of the domain specific work of proving storage will happen in the miner actor, so the payment broker (and payment voucher) don't need to know any of the details about storing files. The payment voucher just needs to contain enough information so that the payment broker can send a message to another actor (the miner.Actor) and get a true/false value back to let it know if the …
> Add condition to payment voucher

- Dockerfile.ci.faucet
- Dockerfile.ci.genesis
as part of the recent refactor, the faucet and genesis CI job was eliminated, as the binaries were already in 'tools' directory.
update Docker files accordingly.
> [DOCKER] copy binaries from tools directory

- .circleci/config.yml
- scripts/update-badge.sh
Moves badge update functionality to a bash script and re-orders CircleCI jobs. See commit messages and linked issue for details.
> Badge update shouldn't be point of failure in CircleCI

- Dockerfile.ci.faucet
- Dockerfile.ci.genesis
otherwise one gets permission denied errors in genesis-file-server and faucet docker images
> make binaries executable

- commands/init.go
- commands/main.go
- node/testing.go
- testhelpers/commands.go
Our tests are all writing sector and sector metadata to `~/.filecoin/sectors` in spite of the fact that the test daemons are being initialized with unique repo directories. 
This bug prevents me from updating the rust-fil-proofs submodule. The new head of rust-fil-proofs contains commits which replace the JSON/filesystem sector builder metadata store with a RocksDB metadata store. The RocksDB metadata store writes a `LOCK` to the directory into which it was initialized, and since all go-filecoin test daemons were using the same directory, most go-filecoin tests fail after the update.
Allow callers of `init` to pass `--sectordir` flag which specifies the directory into which sealed and staged sector data will be written (and sector builder metadata, too).
This changeset is deliberately …
> init takes --sectordir flag

- abi/abi.go
- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- commands/schema/filecoin_block.schema.json
- gengen/util/gengen.go
- mining/worker.go
- proofs/interface.go
- proofs/rustverifier.go
- proofs/sectorbuilder/interface.go
- proofs/sectorbuilder/rustsectorbuilder.go
- proofs/sectorbuilder/testing/interface_test.go
- proofs/sectorbuilder/transforms.go
- proofs/sectorbuilder/utils.go
- proofs/transforms.go
- testhelpers/chain.go
- testhelpers/consensus.go
- types/commitments.go
- types/porep_proof_partitions.go
- types/post_proof_partitions.go
- types/proofs.go
- types/sector_class.go
- types/sector_size.go
- types/testing.go
Blocked by [this upstream rust-fil-proofs PR](https://github.com/filecoin-project/rust-fil-proofs/pull/623).
Fixes #2591.
Miners can choose proof partitions in order to trade off between RAM usage and on-chain proof size. What this means for go-filecoin is that the number of bytes in a PoSt or PoRep proof is no longer fixed.
- Make PoSt and PoRep (seal) proofs `[]byte` instead of `[192]byte` and `[384]byte`
- **BREAKING CHANGE**: JSON encode the `types.PoStProof` in the `types.Block`, using [the default encoder](https://golang.org/pkg/encoding/json/#Marshal). This will produce a base64-encoded string (or null) instead of a JSON array.
> support variable length PoSt and PoRep proofs

- go.mod
- go.sum
- tools/migration/internal/repo_fs_helpers.go
- tools/migration/internal/repo_fs_helpers_test.go
- tools/migration/internal/repo_fs_wrangler.go
- tools/migration/internal/repo_fs_wrangler_test.go
- tools/migration/internal/runner.go
- tools/migration/internal/runner_test.go
- tools/migration/internal/utils.go
- tools/migration/internal/utils_test.go
- tools/migration/main.go
- tools/migration/main_test.go
Closes #2643 
This updates and adds more file system wrangling functionality to `RepoFSWrangler`:
* Changes `MakeNewRepo` to do the actual copying and permissions setting on the new repo.
* Adds `InstallNewRepo` which renames the old repo and symlinks the new repo to the old repo dir.  The new name for the old repo dir is returned so that it can be logged.
* Updates the require/assert usage to stop calling `New`
* changes some of the unit tests to use different functions for file system operations
* deletes the `ExpandHomedir` function since it's not used any more, because the `--old-repo` CLI param is required now.
Open questions:
* @ZenGround0 and I tried to come up with less vague names than `RepoMigrationHelper` and `RepoFSWrangler` is what we "settled" on as good enough for now. It …
> Repo migration functionality: Copy old repo, install new repo #2643

- commands/daemon.go
- commands/init.go
- commands/main.go
- node/node.go
- paths/paths.go
- repo/fsrepo.go
- repo/fsrepo_test.go
- repo/mem.go
- repo/repo.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
#2689 
This also closes out #2680 ( I shut down the already reviewed solution in #2682) in favor of this because these changes remove a gnarly CI-only IPTB cleanup failure during the retrieval test)
This gets rid of the homedir concept while keeping the default sector directory out of the repo as part of compromise 2c laid out here #2687.  
@travisperson I went ahead and defaulted IPTB sector directory storage to be within the repo underneath `sectors` just as it was before I started these changes (we're not migrating these repos so putting sectors inside them is nice and doesn't cause problems).  I don't know my way around the filecoin IPTB plugin well so please alert me if the way I did this is ugly / not the right way.
@shannonwells I don't expect this to get in the way of the other …
> Remove homedir

- .golangci.yml
- build/main.go
- commands/address_daemon_test.go
- config/config.go
- config/config_test.go
- metrics/heartbeat_test.go
- net/pinger.go
- paths/paths.go
- plumbing/api.go
- porcelain/api.go
- porcelain/protocol.go
- proofs/sectorbuilder/bytesink/fifo.go
- repo/fsrepo.go
- repo/fsrepo_test.go
- state/tree_test.go
- testhelpers/core.go
- tools/fast/environment_memory_genesis_test.go
- tools/fast/fastesting/basic.go
- tools/fast/fastesting/log_writer_test.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
- tools/iptb-plugins/filecoin/mock/mockfilecoin.go
- tools/migration/internal/repo_fs_helpers.go
- tools/migration/internal/runner.go
- tools/migration/main.go
- types/porep_proof_partitions.go
- types/post_proof_partitions.go
- types/sector_size.go
- wallet/dsbackend_test.go
golangci-lint chooses to ignore a few linter errors by default. One of these was the doc comments from golint which is why we haven't seen these issues fail ci. This PR disables this configuration and doesn't silent any linter errors.
There are a things that still need proper comments, I've noted these with a `TODO(author)`. Comment on the line with whatever I should replace the placeholder with and I'll update the PR.
> Do not exclude any linter errors

- node/node.go
- proofs/sectorbuilder/interface.go
- proofs/sectorbuilder/rustsectorbuilder.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/storagedeal/types.go
Closes #2571
There is currently no mechanism for miners to send piece inclusion proofs back to clients. As a convenience, we would also like storage miners to communicate the message cid of the `commitSector` message used to commit the sector containing the client's piece, so that the client can more easily track when the commitment lands on their own chain.
This PR adds the inclusion proof and the commit message cid to the ProofInfo in the deal response sent back to the client. The piece inclusion proof is currently faked pending the availability real proofs from rust proofs (#2629).
> add piece inclusion proofs to deals

- Dockerfile.ci.faucet
- Dockerfile.ci.genesis
Ran into permission issues with these docker files, turns out we were coping a directory instead of the binary.
> Docker faucet and genesis server binary coping

- functional-tests/lib/helpers.bash
- functional-tests/retrieval
Fixes #2723 
- "sector dir" is created as a sibling of "repo dir"
- retrieval/bash test's repo dirs are siblings
- sector dirs for each repo overlapped, causing sled lock-acquisition failure
- initialize repo dirs such that they're not siblings
> Bugs/2723 retreival/bash test repo dir initialization

- proofs/sectorbuilder/rustsectorbuilder.go
- proofs/sectorbuilder/testing/interface_test.go
Fixes #2722 
One of the sector builder tests creates a sector builder and uses it to add a piece. It then creates a new sector builder pointed at the same metadata directory and expects it to behave as if the user shut the first sector builder down and then resumed (with the second) where it left off.
The problem with the existing implementation is that the first sector builder was never properly destroyed. We didn't notice this until recently, because the first and second sector builders could easily share a metadata directory (no locking took place). Recent changes (namely the sled-backed Rust metadata store) added a lock to the metadata database file, and this lock isn't released until the sector builder is destroyed.
- properly destroy the sector builder when someone calls …
> Close() should free the sector builder memory and release its locks

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- actor/builtin/storagemarket/storagemarket.go
- chain/default_syncer_test.go
- commands/protocol.go
- consensus/genesis.go
- functional-tests/lib/helpers.bash
- functional-tests/retrieval
- node/node.go
- plumbing/msg/waiter_test.go
- porcelain/api.go
- porcelain/miner.go
- porcelain/miner_test.go
- porcelain/protocol.go
- porcelain/protocol_test.go
- proofs/interface.go
- proofs/rustverifier.go
- proofs/sectorbuilder/testing/builder.go
- proofs/sectorbuilder/testing/harness.go
- proofs/sectorbuilder/testing/interface_test.go
- proofs/testing.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- testhelpers/core.go
- testhelpers/mining.go
- tools/fast/bin/localnet/main.go
- types/sector_class.go
- types/sector_size.go
Makes incremental progress on #2530 
A storage miner operator needs to be able to select a sector size when pledging. This sector size becomes an immutable property of their storage miner actor. This PR makes incremental progress to that end by creating a miner with a sector size (derived from the proofs mode) and persisting that choice to the miner's storage.
- remove notion of test sector class
- replace SectorSize enum with BytesAmount to [conform to spec](https://github.com/filecoin-project/specs/blob/master/actors.md#createstorageminer)
- modify the `protocol` command such that it reports writeable (pre bit-padding) and non-writable ("sector size") in its output
- modify storage market actor `CreateMiner` command to select a sector size for miner based on proofs mode
The `miner …
> pin a miner to a sector size when creating

- chain/default_store.go
- chain/default_store_test.go
- chain/default_syncer.go
- chain/default_syncer_test.go
- chain/get_ancestors.go
- chain/store.go
- chain/tip_index.go
- node/block_propagate_test.go
- node/node.go
- node/node_test.go
- plumbing/bcf/blockchain_facade.go
- plumbing/msg/previewer.go
- plumbing/msg/queryer.go
- plumbing/msg/sender.go
- plumbing/msg/waiter.go
- plumbing/msg/waiter_test.go
- protocol/block/mining_api.go
My first try for this issue.
I think that there are some question remain:
1. How to name abbreviate tipsetstateroot?
I see that most of tipset in code is named ts, so I name tipsetstateroot tssr, but it seems weird. So maybe something like tsStateRoot?
2.At [here](https://github.com/jscode017/go-filecoin/blob/34c19cb529fb27c26aad974f3897ee4462f77f80/chain/tip_index.go#L79) What I did in chain/tip_index.go is that the Get() function remains and write to new methods to access Get() function then access TipSet and TipSetStateRoot respectively, I'm not sure is this appropriate?
> issue-2553 GetTipSetAndState should be split into two methods v0

- .circleci/config.yml
Commit `#8ade4b` switched the rust-fil-proofs submodule SHA to an older version of rust-fil-proofs than was intended. SHA `#8ade4b` includes RocksDB, which has a dependency on libstdcpp, which we don't want.
This PR updates the rust-fil-proofs SHA to the current HEAD of the `master` branch, which puts go-filecoin in a good state yet again.
> update submodule SHA to consume head of rust-fil-proofs

- .circleci/config.yml
this will let us build the github release and docker image and give notice to community that they should upgrade their node before triggering user devnet deploy
> add an approval step to user devnet deploy

- tools/iptb-plugins/filecoin/local/filecoinutil.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
This removes the possibility of collision between files in the repo and anything else placed
in the IPTB directory (log files, pidfiles etc). This is a prefactor for #2701, which tightens
the go-filecoin init checks to require the prospective repo directory to be absent or empty.
> Change localfilecoin IPTB plugin to nest the repo and sector dirs inside the IPTB dir.

- commands/client_daemon_test.go
- commands/retrieval_client_daemon_test.go
- tools/fast/environment_memory_genesis_test.go
- tools/fast/fastesting/assertions.go
- tools/fast/fastutil/debug_utils.go
- tools/fast/process.go
Closes #2611 , providing an easy way to check the StdErr of the Output from running a given FAST command.
> expose StdErr() from iptb.Output with a dump function

- chain/get_ancestors.go
- chain/get_ancestors_test.go
- core/chains.go
- core/message_pool_test.go
This adds a correct FindCommonAncestor utility and updates the message pool to use it.  Tests still WIP
> Fix/message pool update 0.2.0

- commands/client_daemon_test.go
- commands/inspector_daemon_test.go
- commands/payment_channel_daemon_test.go
- commands/retrieval_client_daemon_test.go
These deadlines could expire on a loaded machine or when test parallelism was set too high.
This resolves at least some of the issues reported in #2711.
I don't think test code can make reliable deadline estimates–they depend too much on the environment. Instead we should rely on the externally-injected `-timeout` (which I will shorten separately).
> Remove arbitrary context deadlines from daemon tests.

- tools/migration/internal/logger.go
- tools/migration/internal/runner.go
- tools/migration/internal/runner_test.go
- tools/migration/internal/test_helpers.go
- tools/migration/main.go
- tools/migration/main_test.go
- logfile closed when main exits
- correct flags during file open to enable logging
- correct usage of global log in runner
> Fix migration logging

- .circleci/config.yml
- build/main.go
The specified parallelism of 8 was counter-productive on machines with fewer cores, and the
hardcoded flag was impossible to override from the outside. This now uses the Go default
of GOMAXPROCS (which is #cores). The CI config sets parallelism explicitly to suit container
size.
The specified timeout was also impossible to override when a shorter value was wanted for development. The CI config now sets the 30m value, but this is much more than we currently need.
I think these issues contributed to #2711.
> Replace hardcoded test timeout and parallelism flags with defaults.

- plumbing/strgdls/store_test.go
- protocol/storage/deals_awaiting_seal.go
- protocol/storage/deals_awaiting_seal_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/storagedeal/types.go
This PR is a refactor that ballooned out of #2693 into enough work for a new PR.
dealsAwaitingSeals is burried within protocol/storage/miner. I found its logic confusing and under-tested. 
This PR streamlines the logic, moves it to its own file with a separate file for tests, and adds testing for its features.
> Refactor deals awaiting seals into its own file.

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- actor/builtin/storagemarket/storagemarket.go
- chain/default_syncer_test.go
- chain/power_table_view_test.go
- commands/miner.go
- commands/miner_daemon_test.go
- consensus/expected.go
- consensus/expected_test.go
- consensus/power_table_view.go
- consensus/testing.go
- fixtures/constants.go
- fixtures/setup.json
- gengen/main.go
- gengen/util/gengen.go
- gengen/util/gengen_test.go
- mining/testing.go
- node/block_propagate_test.go
- node/testing.go
- testhelpers/chain.go
- testhelpers/consensus.go
- testhelpers/iptbtester/genesis.go
- tools/fast/environment_memory_genesis.go
- types/bytes_amount.go
Fixes #2601 
This PR brings the go-filecoin implementation a bit closer to the spec w/respect to how miner power is tracked. Today, miner power is recorded in the number of sectors which they have committed to the network. With the multiple sector sizes feature, miners X, Y, and Z on the same network may be committing sectors of different sizes and the power table needs to accommodate for that. 
This PR modifies the power table and EC code and storage market actor (and tests, and ...) to track miner power in bytes amount instead of number of sectors committed to the network. Total storage is also tracked by bytes amount.
Now that miner power (and total storage capacity) is measured in bytes, we can loosen the restriction that prevents a single network from supporting more than one sector …
> A storage miner's power should be measured in an amount of bytes contributed to the network, not number of sectors

- proofs/sectorbuilder/testing/interface_test.go
Fixes: #2820 
The new piece packing algorithm changed the way that pieces fit into a sector. For more information, read the body of #2820.
To ensure that both pieces are packed into the same sector, reduce their size to one byte each. This will cause them to be padded to 127 bytes, and 2 * 127 < size(sector).
> add single byte piece to ensure both pieces are packed into same sector

- chain/default_store_test.go
- chain/default_syncer_test.go
- chain/get_ancestors_test.go
Closes #2116. All `*Test` methods initialize a struct that contains the syncer params, which is in turn passed to all the other initialization/`require*` methods. Let me know if there's an alternative approach you'd like me to implement.
> Use a struct over global vars in default_syncer_test

- actor/builtin/miner/miner_test.go
- actor/builtin/miner_redeem_test.go
- actor/builtin/storagemarket/storagemarket.go
- actor/builtin/storagemarket/storagemarket_test.go
- chain/default_syncer_test.go
- commands/client_daemon_test.go
- consensus/processor_test.go
- gengen/util/gengen.go
- node/testing.go
- porcelain/miner.go
- testhelpers/commands.go
- tools/fast/bin/localnet/main.go
- tools/fast/series/create_miner_with_ask.go
- tools/fast/tests/retrieval_test.go
Fixes #2807.
The [spec](https://github.com/filecoin-project/specs/blob/master/actors.md#createstorageminer) shows a `CreateStorageMiner` method, but our implementation uses `CreateMiner`.
This PR simply changes the name of the message/method to conform to the spec.
> rename createMiner to createStorageMiner to conform to spec

- porcelain/payments.go
- porcelain/payments_test.go
- protocol/storage/client.go
- protocol/storage/client_test.go
closes #2705
Storage clients need to ensure they can recover their money once they discover that a miner is not storing their piece. They can do that by adding conditions to payments that ensure the miner is storing the piece at the time of payment.
Have the client add a 'verifyPieceInclusion' condition to each payment except the last. The last payment should not have a condition so the miner can recover funds without posting a piece inclusion proof at the end of the deal.
The `verifyPieceInclusion` method on miner requires a `CommP` as it's first parameter. We currently do not have the ability to generate `CommP` so we create a fake one in this PR (by using the CID of the piece) and leaving CommP integration as future work (#2792). 
The PR tests that the conditions are created correctly. …
> client adds conditions to payments

- config/config.go
- core/inbox.go
- core/inbox_test.go
- core/message_pool.go
- core/message_pool_test.go
- core/outbox.go
- core/policy.go
- core/testing.go
- mining/worker_test.go
- node/message.go
- node/message_propagate_test.go
- node/msg_publisher.go
- node/node.go
- node/node_test.go
- testhelpers/core.go
- types/testing.go
With this change, the incoming and outbound message queue/pool follow a similar pattern.
They're not quite the same, since validation is performed inside the message pool but
prior to the outbound queue (which we could also align).
> Separate new tipset handling from message pool implementation, wrap in an inbox.

- tools/prerelease-tool/main.go
- tools/prerelease-tool/main_test.go
allows setting a limit of prereleases aka nightlies to keep.
requires a github api token to function.
tool is parameterized via flags otherwise
> pre-release tool to clean up old nightlies

- scripts/install-bls-signatures.sh
- scripts/install-rust-fil-proofs.sh
I oftentimes need the exact submodule SHAs built in order to fix broken builds, debug developer issues, et cetera.
This PR adds the submodule SHA for bls-signatures and rust-fil-proofs to build output.
> output submodule SHAs when building

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- commands/miner.go
- commands/miner_daemon_test.go
- tools/fast/action_miner.go
Makes incremental progress towards #2530.
The `GetPledge` method does [not exist in the spec](https://github.com/filecoin-project/specs/blob/master/actors.md#code-cid-3), and is used only in tests.
This PR deletes the `GetPledge` method and corresponding CLI command.
> remove unspecified GetPledge method

- chain/default_store.go
- chain/default_store_test.go
- chain/default_syncer.go
- chain/default_syncer_test.go
- chain/get_ancestors.go
- chain/tip_index.go
- chain/traversal.go
- commands/chain.go
- consensus/expected.go
- consensus/expected_test.go
- consensus/processor.go
- consensus/testing.go
- core/inbox_test.go
- core/outbox_test.go
- core/testing.go
- metrics/heartbeat_test.go
- mining/scheduler.go
- mining/scheduler_test.go
- mining/testing.go
- mining/worker.go
- mining/worker_test.go
- node/node.go
- plumbing/cst/chain_state.go
- plumbing/msg/waiter.go
- plumbing/msg/waiter_test.go
- types/block.go
- types/tipset.go
- types/tipset_test.go
Block ticket is the canonical traversal order when a tipset is processed. This changes the critical traversal in consensus/expected.go to match that (previously iterated in sorted CID order). This is most of the resolution to #2310. See also https://github.com/filecoin-project/specs/issues/285
The representation is more memory efficient and can be iterated without allocating an intermediate slice. An empty/undefined tipset is now harder to construct and explicitly undefined; a few methods now always return nil error and I intend to remove the error return value from them in a follow-up.
SortedCidSet remains as the "key" type for a tipset. In a follow-up, I intend to also upgrade this to an immutable structure.
> TipSet orders blocks by ticket, is immutable value type

- actor/builtin/miner/miner.go
- consensus/expected.go
- protocol/storage/miner.go
Fixes #2839 
A miner actor's proving period is a function of the miner's selected sector size. Small sectors take less time to prove than larger sectors do, so proving period blocks should be a function of sector size. This is consistent with the [spec](https://github.com/filecoin-project/specs/blob/master/actors.md#commitsector).
Make proving period blocks a function of sector size. This is currently a constant function. Make `AncestorRoundsNeeded` rely on the maximum value which `ProvingPeriodDuration` can return.
> compute proving period as a function of sector size

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- consensus/expected.go
Fixes #2840 
The specification shows, in pseudocode, that generate attack threshold is a function of sector size.
Introduce `GenerationAttackTime` (constant) function which returns, for the largest sector size, the number of blocks after a proving period P ends after which a delinquent miner (i.e. they haven't yet posted a `submitPoSt` message for P) is subject to storage fault slashing.
> generation attack threshold is a function of sector size

- actor/builtin/miner/miner_test.go
- actor/builtin/storagemarket/storagemarket.go
- actor/builtin/storagemarket/storagemarket_test.go
- chain/default_syncer_test.go
- chain/power_table_view_test.go
- commands/miner.go
- commands/miner_daemon_test.go
- gengen/main.go
- gengen/util/gengen.go
- gengen/util/gengen_test.go
- node/testing.go
- porcelain/api.go
- porcelain/miner.go
- porcelain/miner_test.go
- testhelpers/iptbtester/genesis.go
- tools/fast/environment_memory_genesis.go
- types/proofs_mode.go
This PR makes incremental progress on #2530.
Note that this PR is branched off of #2871. Once the upstream PR is merged, this PR will need to be rebased onto `master`. 
The specification shows that the `CreateStorageMiner` method should accept a sector size, and that the created storage miner actor must be forever pinned to that sector size.
This PR modifies the implementation to select, based on the storage market actor's proofs mode, a sector size to be passed in the `createStorageMiner` message.
I need to modify the `miner create` command (and corresponding wiki docs) to accept a sector size as input.
> [part 2] parameterize CreateStorageMiner with a sector size

- commands/miner.go
- commands/miner_daemon_test.go
- commands/opt_sector_size.go
- porcelain/protocol.go
- porcelain/protocol_test.go
Fixes #2530.
Note that this PR is based off of #2873. Once that PR is merged, this PR will need to be rebased onto `master`.
We need to give an operator a command option which lets them pick the size of the sectors which their newly-created storage miner actor will commit.
- modify `miner create` to accept an optional `sectorsize` flag
- default to whatever sector size is supported by the proofs mode
```
$ ./go-filecoin miner create 1 --sectorsize=woot
Error: invalid sector size: woot
```
```
$ ./go-filecoin miner create 1 --sectorsize=12
Error: unsupported sector size: 12 (supported sizes: 268435456)
```
> [part 3] "miner create" command must accept "sectorsize" flag

- commands/message.go
- commands/message_daemon_test.go
Add a `timeout` argument to `message wait` that accepts duration strings compatible with [`time.ParseDuration`](https://golang.org/pkg/time/#ParseDuration).
Resolves #1552
> Add a timeout option to "message wait" command

- commands/show_test.go
- tools/fast/action_show.go
- tools/fast/fastesting/basic.go
1. converts a daemon tests to FAST tests for the `show deal` command.  
1. changes the interface of the FAST `ShowDeal` function to take a deal instead of a CID
1. increases the default block time from 1ms to 50ms because this was needed to get the tests passing; otherwise there wasn't enough time to accept the deal.
The reason for changing the default time was that  I ran into a bug which, when you pass a DaemonOpt to the NewEnvironment function, for some reason the repo/api file is never created. I spent just a little time trying to figure out why but then I figured out a workaround, so for this PR I am using the workaround, as it's basically harmless anyway.  I filed an issue against this here: #2900
> Make show deal test use FAST.  Increase default FAST block time to 50 ms

- commands/outbox.go
- core/message_queue.go
- core/message_queue_test.go
- core/outbox.go
- core/policy.go
- core/policy_test.go
- plumbing/api.go
Applies to #2491 
This adds a context to the parameters of 3 MessageQueue functions. It will be followed up by at least one more PR to finish out the rest of the functions. I cut it off here to keep the PR short.  
Note no new contexts had to be created for this; this uses existing ones.
> add ctx to 3 MessageQueue functions

- chain/default_store_test.go
- chain/default_syncer_test.go
- commands/daemon.go
- consensus/expected.go
- consensus/expected_test.go
- consensus/protocol.go
- mining/worker.go
- mining/worker_test.go
- node/node.go
- plumbing/api.go
- porcelain/protocol.go
- porcelain/protocol_test.go
- protocol/block/mining_api_test.go
- protocol/retrieval/client.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- protocol/storage/miner.go
- testhelpers/chain.go
- testhelpers/mining.go
- tools/fast/series/ctx_sleep_delay.go
- This commit moves the blocktime default to the consensus package and
adds plumbing and porcelain cals to access it.
> move blocktime onto consensus and plumb

- commands/client_daemon_test.go
- commands/deals_daemon_test.go
- commands/inspector_daemon_test.go
- commands/payment_channel_daemon_test.go
- commands/retrieval_client_daemon_test.go
- commands/show_test.go
- tools/fast/bin/localnet/main.go
- tools/fast/environment/environment.go
- tools/fast/environment/environment_devnet.go
- tools/fast/environment/environment_memory_genesis.go
- tools/fast/environment/environment_memory_genesis_test.go
- tools/fast/fastesting/basic.go
- tools/fast/process.go
- tools/fast/process_stderr_recorder.go
- tools/fast/process_stderr_recorder_test.go
- tools/fast/process_test.go
- tools/fast/tests/retrieval_test.go
This PR repackages the way FAST is laid out to make it more friendly to work with deps
This PR adds `GetFunds` to the environment interface and modifies DevNet and MemoryGenesis to impl it.
> create fast environment package

- commands/deals.go
- commands/deals_daemon_test.go
- commands/show.go
- commands/show_test.go
- tools/fast/action_deals.go
- tools/fast/action_show.go
We want to reorganize several commands under a new `go-filecoin deals` subcommand.
Move `go-filecoin show deal` to `go-filecoin deals show`.
> Moved show deal command to deals show

- go.mod
- go.sum
- types/intset.go
- types/intset_test.go
`IntSet` implementation, primarily intended for manipulating and passing around groups of Sector Ids.
Supports the basic set operations: Union, Difference, and Intersection, which should take care of most of our uses cases.
This implementation pretty much follows the [design document](https://docs.google.com/document/d/1aE5a-QZojprMkig6IyYkwV1SrMDDLOnNBqNdnwpu9tk), the relevant part quoted here:
> Proposed data structure: use a golang-collections bitarray.  Don’t worry too much about efficient construction and set difference.  Most operations are fairly trivial.  We will KISS and not avoid iterating over members of the set.  We won’t do any clever run or range based operations.  This will of course change if this is seen to be a state machine processing bottleneck.
> Add IntSet implementation

- chain/syncer.go
This PR was created to help debug problems like #2903. It adds a metric called  `chain/reorg_count` to the filecoin prometheus endpoint that may be used to determine when and how frequently reorgs occur.
> add metric to count reorgs

- commands/deals_daemon_test.go
We don't know the cause of this yet. It's a significant problem (#2960) but meanwhile this flaky test prevents us from merging PRs. Leaving it disabled is a louder warning that we have a problem than relaxing it to accept a rounding error.
> Disable flaky assertion in TestDealsRedeem FAST test

- .circleci/config.yml
this is ready for showtime. I ran a test here https://circleci.com/gh/filecoin-project/go-filecoin/20271 with --dry-run flag enabled. Results are as expected.
removing --dry-run flag to enable this feature
> enable nightly prerelease cleanup

- chain/store.go
- chain/traversal.go
- chain/traversal_test.go
- core/chains.go
- core/inbox.go
- core/inbox_test.go
- core/policy.go
- core/policy_test.go
- testhelpers/chain.go
- tools/migration/migrations/repo-1-2/migration.go
@ZenGround0 suggested that the chain traversals should use a TipsetProvider rather than BlockProvider so they could hit the store's tip index.
This allows most traversals to hit the in-memory tipset cache and bypass a heap of disk access and decoding. For the traversals that can't use an index, added an adaptor that builds tipsets on the fly from a block provider (i.e. the old way).
> Change chain traversal to hit tipset cache

- consensus/validation_test.go
- core/chains.go
- core/inbox.go
- core/message_queue_test.go
- core/policy.go
- core/policy_test.go
- mining/mqueue_test.go
- node/message_propagate_test.go
- porcelain/mpool_test.go
- types/helpers.go
- types/signed_message_test.go
- types/testing.go
This is the last item in #2310, ensuring that messages are removed from the outbox in the order they were mined (i.e. correct nonce order).
Closes #2310
> Iterate messages in canonical tipset order when removing from outbox

- actor/builtin/paymentbroker/paymentbroker.go
- actor/builtin/storagemarket/storagemarket.go
- address/constants.go
- consensus/genesis.go
- core/outbox_test.go
As [specified](https://github.com/filecoin-project/specs/blob/master/actors.md#built-in-actors)
Also updated the other built-in actors to have ID-style addresses.
> Add built-in burnt funds account actor to genesis

- core/message_queue.go
- core/message_queue_test.go
- core/policy.go
Closes #2491 
This change set gets rid of the last `ctx.TODO()` call in `MessageQueue` and uses the context that the caller already has.
> add real context to last MessageQueue function

- chain/syncer.go
- consensus/processor.go
- metrics/timer.go
- metrics/timer_test.go
This is complementary to the existing timers for consensus block and message processing. This new timer captures the cost to load up all the context for that processing, in particular traversing ancestors. I expect #2879 to make a difference here.
> Add a timer for syncer.SyncOne, the duration to validate a tipset

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- types/atto_fil.go
- types/block_height.go
The fee is a proportion of pledge collateral equal to the lateness as a fraction of the maximum allowable lateness. Proofs after the generation attack threshold are rejected (the miner actor can expect to be slashed).
The worker doesn't yet compute and attach any required fee, so late proofs will continue to be rejected. Part of the work for #2942.
> StorageMiner.SubmitPoSt actor method charges late fees.

- commands/deals_daemon_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/storagedeal/state.go
- tools/fast/bin/localnet/main.go
- tools/fast/tests/retrieval_test.go
closes #2806
The names we use for deal states are inconsistent with [the spec](https://github.com/filecoin-project/specs/blob/ed6f64914edc4fef47fc287a68305b7cd1e7afb8/network-protocols.md#deal-state-values)
1. Add `Unset` state to distinguish unknown deals from deals with their state unset
2. Rename `Posted` to `Complete`.
3. Sync comments.
> rename some deal states

- main.go
- node/node.go
This PR creates a `subscriptionLogger` that `handleSubscription` uses to log warnings when its call backs (processBlock and processMessage) error. The PR then sets the default log level of the subscriptionLogger to error.
> create subscription logger, default error level

- .codecov.yml
This improves the quality of the coverage diffs, though I'm not 100% sure it's right yet.
We do have a small amount of nondeterministic coverage in node.go and hello.go, but on the order of <10 lines. 
The coverage report can be confusing while the Circle build is still running: it shows partial results when only some of the jobs have uploaded their coverage reports. It's necessary to wait until the build is finished and then reload the PR page to see a sensible report.
> Codecov requires a base report before posting a GH comment.

- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/prover.go
- protocol/storage/prover_test.go
Interesting tests will come later when some of the outstanding TODOs are addressed.
I think the boundary that I've drawn could actually be pushed a bit further, incorporating much of the logic in `Miner.OnNewHeaviestTipSet`. But right now I need to test late fee calculations.
> Factor proof calculation out of storage miner for testability.

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- actor/builtin/storagemarket/storagemarket.go
- actor/builtin/storagemarket/storagemarket_test.go
- core/testing.go
- testhelpers/consensus.go
- testhelpers/core.go
- types/bytes_amount_test.go
This PR includes tests demonstrating that UpdateStorage already accepts negative values.
It also refactors state machine test helpers so that we can effectively test UpdateStorage which previously was not tested.
Feedback welcome if leveraging possibility of negative values in `BytesAmount` is too hacky and negative values should be more explicitly created in that type.
> UpdateStorage accepts negative values

- commands/show.go
- commands/show_test.go
I think we should show messages in block when run 'go-filecoin show block', then we can know the history messages, including transaction and other messages.
```
waynewyang:go-filecoin waynewyang$ ./go-filecoin show block zDPWYqFCwxAV66BT3jnYZMVWNZvayYf95EjjK6f8n46n9AVsReSD
Block Details
Miner:  t2ej7i72xtkglfpbo7nc56pqg2fsdzlspqe63vnoq
Weight: 0.000
Height: 1
Nonce:  0
Timestamp:  0
Message:  [SignedMessage cid=[zDPWYqFCz3f9sTvKp5W1u6Vo57u2xH4T7Nicv2Xx8jz1zoQ1UL1v]: {
"meteredMessage": {
"message": {
"to": "t2ej7i72xtkglfpbo7nc56pqg2fsdzlspqe63vnoq",
"from": "t1strybge3p4daa6qgtz5jsfxalzg4mr6bix5s2ti",
"nonce": "2",
"value": "0",
"method": "updatePeerID",
"params": "gVgiEiDbXbBmGs1XgNWvOhNU42yekJfMBSr7U4fZYPsDbHxqFQ=="
},
"gasPrice": "0.000000001",
"gasLimit": "300"
},
"signature": …
```
> Show more information by '--messages' flag when show block

- abi/abi.go
- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- actor/builtin/miner/sector_set.go
- actor/builtin/miner/sector_set_test.go
- actor/builtin/miner_redeem_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- testhelpers/mining.go
- types/intset.go
- types/intset_test.go
This PR adds the NextDoneSet and ProvingSet abstractions to the miner actor.  It is best read commit by commit.  The first commit introduces a done parameter into submitPoSt.  The second adds the NextDoneSet abstraction.  The third introduces a SectorSet abstraction to keep the next commit clean.  The fourth introduces the ProvingSet.
The edge case of the ProvingSet being updated during the first commitSector message is not handled in this PR.  I'm working on this in an upcoming followup.
> Add NextDoneSet and ProvingSet abstractions to miner actor

- go.mod
- rleplus/internal/bitvector.go
- rleplus/internal/bitvector_test.go
- rleplus/rleplus.go
- rleplus/rleplus_test.go
We need a compact representation of `IntSet` for network transmission and storage.
Implementation of [RLE+](https://github.com/filecoin-project/specs/blob/master/data-structures.md#rle-bitset-encoding) encoding.
The encoding happens in [`rleplus.go`](https://github.com/filecoin-project/go-filecoin/blob/c526b748d24c062a9caa922b533db5512d76acbc/rleplus/rleplus.go) via the `Encode()` and `Decode()` functions, with an internal helper `BitVector` class.
Resolves #2868
> RLE+ encoding

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- actor/builtin/miner/sector_set.go
- chain/power_table_view_test.go
- commands/deals_daemon_test.go
- gengen/util/gengen.go
- go.sum
- types/intset.go
- types/intset_test.go
- move power and total storage updates to submitPoSt
- add power update tests
- proving set initialized to first sector on first PoSt submit
- address failures from out-dated power setting assumptions
This is based against feat/2948 in PR at #2999 and you'll need to green light it again that one merges and I change the base to master.  Might be worth waiting for #2999 to merge until you review this.
Initializing the proving set to the first committed sector during commitSector is something some might consider in scope for #2999 but I added it here.
> Update power based on previous proving set

- actor/builtin/miner/miner.go
- chain/get_ancestors.go
- sampling/chain_randomness.go
- sampling/chain_randomness_test.go
- testhelpers/mining.go
- vm/context_test.go
Fixes #3017.
Removed tests for VM context that are duplicates of tests for the actual chain sampling.
Note that we're actually supposed to be sampling tickets, which form a contiguous chain, so this will all go away when we implement ticket chains properly.
> Chain sampling for challenge seed skips over null blocks.

- bin/node_restart
When a node dies from OOM, the API file will not be cleaned up properly. This resulted in the api file check to pass with a false positive.
> Poll daemon to determine if it's ready

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
Support for #2939 
Storage fault monitor will ask a minor actor for its lateness status ("PoStState") so as to determine whether there is a fault and what type.  This leaves all the logic for determining lateness in one place -- since this is already calculated during an actual PoSt submission -- and will reduce the number of message queries to actors in order to tally unreported faults.
This PR implements the GetPoStState export in the miner actor.  Better name suggestions welcome.
> add GetPoStState for lateness determination

- core/inbox.go
- core/policy.go
This quiets the "nonce too low" validation failure that is extremely common whenever the chain head switches and the same message/s were mined in both chains.
`08:40:52.287  INFO     mqueue: validation error adding message to pool: nonce too low inbox.go:75`
@ZenGround0 if we cherry-pick anything into 0.3, I propose including this too.
> Reduce message validation failure after re-org to debug level

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_internal_test.go
- actor/builtin/miner/miner_test.go
- node/block_propagate_test.go
- node/node.go
- node/node_test.go
- plumbing/api.go
- porcelain/api.go
- porcelain/miner.go
- porcelain/sectorbuilder.go
- protocol/block/mining_api_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/prover.go
- protocol/storage/prover_test.go
- protocol/storage/testing.go
This change is in two commits. The first does the real work but introduced some messy dependency plumbing. The second re-arranges dependencies to avoid passing prover dependencies through the miner, but touches quite a few files on the way. The `CalculatePoSt` method is added to plumbing.
cc @acruikshank as this touches a few things you've edited recently.
Closes #2942
> Miner worker calculates and pays late fees when submitting PoSt

- chain/syncer.go
- net/fetcher.go
- net/fetcher_test.go
- node/node.go
- testhelpers/net.go
This PR defines a Fetcher interface and renames the original Fetcher to BitswapFetcher. The goal here is to define an interface for other types of fetchers. Some examples include a blocksync fetcher and a graphsync fetcher.
> add Fetcher interface, impl with BitswapFetcher

- actor/builtin/miner/miner_internal_test.go
- actor/builtin/miner/miner_test.go
- actor/storage.go
- chain/get_ancestors.go
- chain/init.go
- chain/store.go
- chain/store_test.go
- chain/syncer.go
- chain/syncer_test.go
- mining/worker.go
- mining/worker_test.go
- node/node.go
- plumbing/cst/chain_state.go
- plumbing/msg/waiter.go
This resolves #2636.  It removes writing blockchain data to the protected chain store.  `Load` now reads from the global IPLD store.
With this change the store's `*Block(s)` methods all no longer make sense and have been deleted.  This makes for a better interface.  Consumers should not be accessing individual blocks through the chain store, they should be accessing tipsets.  This descopes the chain store's interface to something more manageable and expected.  Consumers were already using this pattern for the most part.
> Removed duplicate block storage

- chain/syncer.go
- chain/syncer_test.go
- consensus/expected.go
- consensus/expected_test.go
- consensus/protocol.go
- node/node.go
- state/tree.go
- state/tree_test.go
Consensus already reads and writes the ipld store, with this change the syncer is no longer doing so on its behalf.
After this change, the syncer is oblivious to state representation. In unit tests, we can fake the state transition function and remove a ton of set up code. (We'll still want some integration tests that use a real consensus implementation).
This is part of #2128.
> Remove state store from syncer, limit its knowledge to state IDs

- .codecov.yml
The number we see from coverage reports are wrong. Until we can fix it, let's not post bogus numbers into PRs and train people to ignore them.
I have other work attempting to fix it.
See #2785
> Disable codecov comments on PRs until the numbers are accurate

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- actor/storage.go
- exec/exec.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- testhelpers/core.go
- vm/context.go
- vm/context_test.go
closes #3003
PoSt verification should only cover sectors in the current proving set. We are currently proving over all sectors. This includes sectors that have been added during the current proving set, which should be excluded.
Only include sectors in the proving set in verification. This involves some rather minor changes to `SubmitPoSt` and `GetSectorCommitments` (now `GetProvingSetCommitments`). The problem is the part of the code that changed in `SubmitPoSt` was not under test. This prompted a much larger refactor to make all of miner actor testable. A consequence is that all actor code will now be more testable.
Major thrusts of work are fairly well encapsulated within 6 commits:
1. Commit 1: __Send only proving set CommRs to VerifyPoSt__: This completes the verification side of the …
> Use proving set instead of sector commitments for PoSt validation

- actor/builtin/miner/miner.go
While stumbling through the code forest with @sidke this morning, we came across an extra return statement. Being good citizens, we terminated it with extreme prejudice.
Oh not much. Just deleted an extra return statement.
> terminate the extra return

- commands/main.go
- types/payment_voucher.go
closes #2909
Error messaging for redeeming a message voucher is bad. In the case of the bug, there was an attempt to redeem something other than a payment voucher, and the error mentions getting an int instead of a map in a stream. Prior to the decoding error, there was an attempt to call redeem without providing a gas-limit or gas-price, but the error only mentioned 'limit' and 'price'.
Provide error message that simply suggest indicated that the payment voucher decoding has failed. Precisely why it has failed is going to be hard to recover, and precisely where in the decoding it failed is irrelevant. Also fix the error messages for required gas price and limit.
> better error messaging for voucher decoding

- abi/abi.go
- abi/encoding_test.go
- actor/builtin/miner/miner_test.go
- actor/builtin/storagemarket/storagemarket.go
- actor/builtin/storagemarket/storagemarket_test.go
- plumbing/api.go
- testhelpers/core.go
Support for #2939 
The fault monitor needs a list of storage miners that are late. Storage miner has the list of miners and can ask each actor for its lateness. Create an export in storage market that returns a pointer to a map of address strings with PoStStates, but only if that state is late.
> storagemarket.GetLateMiners

- proofs/libsectorbuilder/cgo_bindings.go
The version of Go which we use does not require these conversions. So, we might as well delete them.
This changeset removes unnecessary type conversions in CGO.
> remove unnecessary type conversions

- commands/deals_daemon_test.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
closes #3037
We've identified a use case for miners who want to provide storage for free. In this case, the miner would provide an Ask with 0 price. The problem is that the client software will end up creating a zero FIL payment channel for the miner in this case. An empty payment channel is useless and costs the client FIL in gas charges, which defeats the whole purpose of making storage free.
If a client detects that the miner is not charging for storage, skip the payment generation process. Similarly, if the miner is not currently charging for storage, do not verify that the client has generated a payment channel and payment vouchers before accepting the storage proposal.
> skip payments for zero cost deals

- commands/main.go
- commands/version_daemon_test.go
Addresses [issue #63 in the js-filecoin-api](https://github.com/filecoin-project/js-filecoin-api-client/issues/63).
When we changed the `version` command to allow it to work without a running daemon, we ended up removing it from the HTTP API. This was unintentional.
Restore the version command to the HTTP API. The `version` CLI command does not contact the daemon, and returns the version of the CLI client. Making a request to the /api/version endpoint now works and returns the version of the daemon.
This is maybe a little hacky, but it's a simple solution that works until we get a better HTTP API.
> support version command over HTTP

- chain/init.go
- chain/store.go
- chain/store_test.go
- chain/syncer_test.go
- node/node.go
- state/tree.go
This PR defines `IpldStore` and `TreeLoader` interfaces and modifies the chain store to accept them. A goal of this PR is to ease testing of the chain store and syncer by allowing the CborIplsStore and State Tree Loading operations to be mocked/faked.
> add IpldStore and StateLoading interfaces

- chain/get_ancestors_test.go
- chain/reorg_test.go
- chain/store_test.go
- chain/syncer.go
- chain/syncer_integration_test.go
- chain/syncer_test.go
- chain/testing.go
- chain/traversal_test.go
- core/policy_test.go
Expand chain.Builder to keep track of computed state roots.
Sorry the diff here is a bit large. There is no change in syncer functionality or test coverage intended, though the tests themselves are now much shorter. The chain builder has more code in order to consistently compute state CIDs.
> Port most syncer tests to use chain.Builder and non-shared setup

- .circleci/config.yml
We don't need a docker image in test_all. The output is ignored.
Fixes #2750.
> Remove build_docker_image from test_all workflow.

- chain/get_ancestors_test.go
- chain/store.go
- chain/store_test.go
- chain/syncer.go
- chain/syncer_test.go
- chain/testing.go
- core/inbox.go
- core/inbox_test.go
- core/testing.go
- plumbing/cst/chain_state.go
- plumbing/msg/previewer.go
- plumbing/msg/queryer.go
This moves the needle on issue #3022.  PR #3061 makes state accesses within plumbing require referencing state wrt a specific tipset key.  This PR enforces the same for block heights by removing `BlockHeight` from `chain.Store`.
It also un-swallows a swallowed error in the syncer's finality calculation.
@anorth I think #3022 is broader in scope than this PR + #3061 and is only complete when *callers* of plumbing reference a specific tipsetkey.  However I wasn't sure so let me know if I am wrong and the issue is addressed here and I'll connect it to this PR / close out on merge.
> Remove chain.Store's "BlockHeight" method

- protocol/storage/client.go
The timeout context in deal proposal was being used to cover two different cases that should be handled independently.
First we need to verify that we are connected to the miner, and secondly we need to have our payment channel mined into a block. Everything else can use the regular context.
> Split deal proposal context

- abi/abi.go
- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- gengen/util/gengen.go
- go.sum
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/prover.go
- types/fault_set.go
- types/fault_set_test.go
- types/intset.go
Add a `FaultSet` type and ABI type registration.  Add a fault set as a parameter to the `SubmitPoSt` method.  Use RLE+ serialization for IntSets.
Resolves #2889
> Fault Set Type [#2889]

- scripts/install-bls-signatures.sh
resolves: https://github.com/filecoin-project/go-filecoin/issues/3120
but will be irrelevant when https://github.com/filecoin-project/go-filecoin/pull/3099 gets merged, since https://github.com/filecoin-project/go-bls-sigs/blob/master/install-bls-signatures already has this change
> fix destination file when copying libbls_signatures_ffi.a

- chain/syncer.go
- chain/syncer_integration_test.go
- chain/testing.go
- chain/util.go
- consensus/block_validation.go
- consensus/block_validation_test.go
- core/policy.go
- net/fetcher.go
- testhelpers/net.go
This PR changes the Fetcher interface to accept a callback method that can be used to halt fetching blocks.
This PR then replaces calls to `collectChain` with this method.
> add fetcher callback to halt fetching

- chain/syncer.go
- chain/syncer_integration_test.go
- chain/syncer_test.go
- chain/testing.go
- net/fetcher.go
- node/block.go
- node/node.go
- testhelpers/net.go
@hannahhoward I plumbed the peer ID down to `FetchTipSets` let me know if I should push it further into `GetBlocks`.
> Plumb peer ID to syncer's fetcher

- scripts/install-shared.bash
- condition to check that the arch is supported before trying to download a resource from github
resolves: https://github.com/filecoin-project/go-filecoin/issues/2098
> download script should fail and fallback to local on unsupported arch

- go.mod
- tools/fast/action_miner.go
- tools/fast/action_miner_test.go
FAST's `Filecoin.MinerPower`, it is borked.
Based on @travisperson 's comment I've filed an [issue to change the output of the `miner power` command](https://github.com/filecoin-project/go-filecoin/issues/3144
) -- feel free to update to your liking.
MinerPower was not updated to parse the latest output consisting of `<minerpower> / <totalpower>`.  It was missed because it hadn't been used yet. Fix this, include a regression test.
> MinerPower bug fix & test

- chain/store_test.go
- chain/syncer_integration_test.go
- chain/syncer_test.go
- chain/testing.go
- core/policy_test.go
The huge common test setup is now only required for the store tests, from which it should be pretty easy to remove.
> Rewrite syncer TestLoadFork to use chain builder and fakes

- commands/daemon.go
- mining/scheduler.go
- node/block.go
- node/node.go
- util/moresync/latch.go
- util/moresync/latch_test.go
Also cleans up some other sequencing and context in node boot.
A consequence of this is that after the chain syncer properly distinguishes between initial/trusted/bootstrap syncing and regular "caught up" syncing of close-to-head blocks (#1105), we won't see a slew of error messages from blocks that were received over pubsub but were waiting for that initial sync to complete and are now "too old". Note that since sync takes a long time, that bootstrap sync may need to be repeated a few times to get the trusted chain in range of the blocks appearing on pubsub (which would be needed anyway, not a consequence of this change).
Closes #3138.
> Defer subscription to block pubsub until after initial chain sync.

- net/peer_tracker.go
- net/peer_tracker_test.go
- node/node.go
- protocol/hello/hello.go
- protocol/hello/hello_test.go
- testhelpers/net.go
- types/chain_info.go
I changed the name from "manager" to "tracker" because our first draft of this is a passive listener to the actual management done by libp2p and the hello protocol.
> Peer Tracker #3054

- chain/store_test.go
- chain/syncer.go
- chain/syncer_integration_test.go
- chain/syncer_test.go
- node/block.go
- node/node.go
This PR can be reviewed in 2 steps:
- cd16520 adds a type called `PeerHeadInfo` that contains information about a peer, its current head state and its trustworthiness. `HandleNewTipset` is then modified to accept this type. This is a mechanical change that doesn't effect the code logic.
- bf0e2c3 does a couple things:
- replaces the syncers `syncMode` with the `Trusted` field in `PeerHeadInfo`. The syncers logic is changed to check if a TipSet exceeds finality if the peer is untrusted.
- modifies `exceedsFinalityLimit` to accept 2 Uint64's, the current head and the new Head we get from `PeerHeadInfo`. This change simplifies the Fethers callback to a single case.
- removes the `fetchCtx` as that was mode dependent.
> Replace syncing modes with trusted boolean value

- .circleci/config.yml
This is a bit of a hail-mary to move us past this current issue. We unfortunately still have no idea what is causing the panics to occur as only containers built in circleci has this issue. 
I'm hoping locking into `stretch` will fix this in the short term, as the rust proofs are built from a [`debian:stretch` base image](https://github.com/filecoin-project/rust-fil-proofs/blob/master/Dockerfile-ci#L5), and I was successful in building go-filecoin from `golang:1.12.1-stretch` and coping it into a `busybox:1-glibc` container.
The docker file I used was a slightly modified version  I created for the new k8s deployments.
https://github.com/filecoin-project/go-filecoin/blob/feat/devnet-fast-k8s/Dockerfile.devnet.base
I'm hoping because circleci uses this [same image to build their …
> Update circleci docker container to circleci/golang:1.12.1-stretch

- chain/store_test.go
- chain/syncer.go
- chain/syncer_integration_test.go
- chain/syncer_test.go
- chain/testing.go
- consensus/expected.go
- consensus/expected_test.go
- consensus/processor.go
- consensus/processor_test.go
- consensus/protocol.go
- node/node.go
- plumbing/msg/waiter.go
This follows onto PR #3168, making changes that will be needed to the consensus and processor interfaces for message separation.
Please do not review until #3168 is in as it is based on that branch.
> Prepare consensus for messages out of blocks

- Dockerfile
- Dockerfile.ci.faucet
- Dockerfile.ci.filecoin
- Dockerfile.ci.genesis
- Dockerfile.faucet
- Dockerfile.genesis
Busybox 1.31.0 was released 14 days ago which happens to coincide with these issues we are facing with nightly. After forcing an update locally I was able to reproduce the issue.
Pinning the image back to 1.30.1 fixes it. I looked through the 1.31.0 change log and did not find anything that popped out at me.
> Pin busybox to 1.30.1

- net/graphsync_fetcher.go
- net/graphsync_fetcher_test.go
Integrate the peer tracker with the graphsync fetcher to provide fallback resiliency if peer goes
offline during a fetch
- During a request:
- track which peers we've already tried to request from
- every time a request fails:
- query the peer tracker for peers we haven't tried yet
- if we find one we haven't tried, retry with that peer.  if any full tipsets were fetched, verify them and start at the first incomplete tipset
- if we exhaust all peers we know about, fail with a message about the tipset we failed on
- multiple unit tests of different potential error cases during fetching process
This is getting to be a very complicated and stateful iteration. We have to deal with:
- tracking peers we've tried
- tracking which peer we trying currently
- gradually increasing our recursion …
> Integrate PeerTracker and GraphsyncFetcher

- go.mod
- go.sum
- net/graphsync_fetcher_test.go
- node/node.go
Use Graphsync Fetcher in the rest of the project!
I decided to add some utilities to Graphsync to make it easier to setup a Graphsync loader and storer function from a blockstore -- to simplify the code in Filecoin, and cause this will probably be valuable elsewhere.
Otherwise, this just changes a few lines in the actual node constructor.
> Switch to Graphsync Fetcher

- tools/iptb-plugins/filecoin/local/filecoinutil.go
- tools/iptb-plugins/filecoin/local/localfilecoin.go
Updating the os env results in the PATH increases in size on each call
which after many calls will exceed the limit of exec resulting in an
error to execute any exec commands.
> Do not update os env with new path

- commands/message_daemon_test.go
- commands/show.go
- commands/show_test.go
- plumbing/api.go
- plumbing/cst/chain_state.go
- porcelain/api.go
- porcelain/chain.go
- tools/fast/action_show.go
- tools/fast/series/get_head_block_height.go
- types/full_block.go
- types/message_receipt.go
Closes #3196.  
Some changes since writing that issue: it makes more sense to use a separate command for the header and the full block rather than controlling with a flag because the cmds lib can only return a single type from each CLI call.  I kept `block` as the name of the full block command and now `header` is the block header show command.
Note that the old`show block` api is still broken because now the structure of the output is like 
```
{
Header {
Parents: ...
Ticket: ...
Timestamp: ...
...
}
Messages: [msg1, msg2...]
Receipts: [rcpt1, rcpt2,...]
}
```
instead of the previous:
```
{
Parents: ...
Ticket: ...
Timestamp: ...
... 
Messages: [msg1, msg2...]
Receipts: [rcpt1, rcpt2...]
}
```
> Update CLI show command

- go.mod
- go.sum
- net/graphsync_fetcher.go
- net/graphsync_fetcher_test.go
Updates to a tagged version of Graphsync that relies on a tagged version of go-ipld-prime (which is based on master, as opposed to a branch)
Update versions. One utility class -- the selector builder -- was moved to a different package so there are a couple changes.
**Why the prerelease in the version name?**
Put this there cause it seems very likely we will need to merge a few bug fixes to one of these libraries prior to release and I'd like to not have a bunch of actual version updates till we have the release -- which will be the first production release for both these libraries.
Also don't want to mess with Eric Mehre's timeline on go-ipld-prime.
> Updated to tagged graphsync

- porcelain/api.go
- porcelain/payments.go
- porcelain/payments_test.go
- protocol/storage/client.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
closes #2572
A miner does quite a bit of validation of payment data prior to accepting the deal. Unfortunately, the miner cannot confirm the client has specified the correct commitment until they are in possession of the client's data.
Once the client has exported their data, have the miner generate a piece commitment from it. Then have the miner validate all the payments go the the right method on the right miner with the right CommP and piece size.
> Have miner confirm that payment conditions are valid before continuing with payment deal

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- actor/builtin/miner_redeem_test.go
- commands/client.go
- commands/deals_daemon_test.go
- porcelain/api.go
- porcelain/client.go
- protocol/storage/client.go
- protocol/storage/storagedeal/types.go
- tools/fast/action_client.go
- tools/fast/bin/localnet/main.go
- tools/fast/series/wait_for_deal_state.go
- tools/fast/tests/retrieval_test.go
PIP generation is happening during deal creation, but it isn't being verified.
Add a new client command, `verify-deal-proposal`, that checks that the returned deal from the storage miner is in the [`Complete`](https://github.com/filecoin-project/go-filecoin/blob/fe3d41143e81d461d8f049f0ac739b391b5aa342/protocol/storage/storagedeal/state.go#L33) state, and that the PIP returned in the [`ProofInfo`](https://github.com/filecoin-project/go-filecoin/blob/fe3d41143e81d461d8f049f0ac739b391b5aa342/protocol/storage/storagedeal/types.go#L113) is valid.
This command doesn't cancel the payment channel if the PIP is invalid; the client must call `paych cancel` with the channel id, which is stored in the proposal.
Resolves #2676
> Client validates PIP

- functional-tests/retrieval
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/storagedeal/types.go
Miners and storage clients would like more data when inspecting the storage deals they are involved in.
Add `CommD`, `CommR`, and `CommRStar` to the payload returned from the `query-storage-deal` command.
(with `--enc=json`)
```json
{
"State": 7,
"Message": "",
"ProposalCid": {
"/": "bafy2bzaceadaomv5z2otqnchg5yrsckgtokcv4o5b2aks7geqycmw4neqdkti"
},
"ProofInfo": {
"SectorID": 1,
"CommD": "7y3qof2Ym+JmBL4HNsx5B4MXhszKsxzViekWs5Vl3zs=",
"CommR": "3CGQ/QY08SvqY9hHolzKk+533k2WospIhJTtPYJF/XI=",
"CommRStar": "pTZ5o4J/w+cQUPuTWyTD1fe8ptw2WP7Xa1fMFnzesU4=",
"CommitmentMessage": {
"/": "bafy2bzacedanjszzvuixgw4sykaiwficfud7c6tij3mvpvmz3bz2wdhgezjtc"
},
"PieceInclusionProof": "EAAAAAAAAABRTi4JhUuDkSEh8epLy2hzutjP+UjGTh5jiYV8PG9YAw=="
},
"Signature": "c2lnbmF0dXJycmVlZQ=="
}
```
resolve #3085
> Add CommD, CommR, CommRStar to ProofInfo

- chain/message_store.go
- chain/syncer.go
- net/graphsync_fetcher.go
- node/node.go
- types/chain_info.go
Re #3220. This doesn't actually fix anything, but points to the failure a bit better.
Result:
```
15:20:41.370  INFO net.graphs: fetching initial tipset { bafy2bzacebf4rvcnwk5e3aox4nj75sfspf3evpw3vbh4zy65so7khipy76m7w bafy2bzaceboxgks2bx3wn7wjwrsulzwnohlf27ywk3aqzpxsmogvg3aztssli } from peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY graphsync_fetcher.go:109
15:20:41.370  INFO net.graphs: fetching chain from height 7712, block bafy2bzacebf4rvcnwk5e3aox4nj75sfspf3evpw3vbh4zy65so7khipy76m7w, peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY, 1 levels graphsync_fetcher.go:145
15:20:41.370  INFO net.graphs: fetching chain from height 7710, block bafy2bzacedynkwwaywseknh5szbf5jryuiendddzvq2vcxbbrymuaosc22d6m, peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY, 4 levels …
```
> Improve logging and error messages around graphsync chain fetch.

- chain/message_store.go
- chain/syncer.go
- net/graphsync_fetcher.go
- net/peer_tracker.go
- node/node.go
- types/chain_info.go
I don't know exactly why we receive this callback for the same peer multiple times, but it's frequent and not a warning-level problem.
Closes #3128. cc @ZenGround0
> Replace warning on duplicate peer tracking with informative message.

- plumbing/strgdls/store_test.go
- porcelain/api.go
- porcelain/miner.go
- porcelain/miner_test.go
- porcelain/storagedeals_test.go
- protocol/storage/api.go
- protocol/storage/client.go
- protocol/storage/client_test.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/storagedeal/types.go
closes #1211
The storage miner's deal response has contained a `Signature` field for some time, but we've never actually populated it. It's critical that the miner signs the deal, because the response forms a contract that can be posted on chain for deal arbitration.
Sign the deal proposal when the deal is accepted, when it's rejected, and when it's updated. Also have the client check the signature whenever a deal response is received.
This PR refactors `protocols/storage/miner` to abstract just the processing of the deal. This allows us to test the deal acceptance and deal rejection.
This PR also adds porcelain to retrieve the miner worker address because that is the address used to sign the response.
> sign and verify deal response

- commands/message.go
- commands/mining.go
- commands/mining_daemon_test.go
- porcelain/api.go
- porcelain/sectorbuilder.go
- porcelain/sectorbuilder_test.go
- proofs/sectorbuilder/interface.go
- proofs/sectorbuilder/rustsectorbuilder.go
- tools/fast/action_mining.go
closes #3044 
Some storage miners are only interested in gaining mining power, and don't want to have to wait for storage deals (or fake storage deals) to start committing sectors. Currently sector sealing doesn't begin until a piece has been added to a sector.
The SectorBuilder only lets us trigger sealing on sectors that are already staged. If a miner has not accepted a storage deal, there will be no sectors to stage. We check to see if any staged sectors exist. If not, we add a 1 byte piece to the sector builder to generate a staged sector. In either case we call `sectorbuilder.SealAllStagedSectors` to trigger the sealing process.
This PR includes a functional test to demonstrate that calling `mining seal-now` results in additional storage power without a storage deal taking place.
> add seal-now command

- .circleci/config.yml
After https://github.com/filecoin-project/go-filecoin/pull/3201 we have to ensure that we are initializing everything up-front. I believe this wasn't true prior, so having the out of order actions did not matter. All other calls to `generate_rust_submodules_checksums` are proceeded by a call to `update_submodules`.
> Update submodules before generating checksums

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
`LastPoSt` is no longer being used to determine if a miner is active or not (#3195).  We are using `SectorCommitments` and `ProvingPeriodEnd` instead. 
Remove `LastPoSt` from the miner state.
Resolves #2947
> Remove LastPoSt from miner state

- commands/client_daemon_test.go
- commands/deals_daemon_test.go
- commands/mining_daemon_test.go
- tools/fast/action_client.go
- tools/fast/action_deals.go
- tools/fast/action_dht.go
- tools/fast/action_miner_test.go
- tools/fast/action_show.go
- tools/fast/bin/localnet/main.go
- tools/fast/environment/environment_devnet.go
- tools/fast/environment/environment_memory_genesis.go
- tools/fast/process_action_options.go
- tools/fast/series/create_miner_with_ask.go
- tools/fast/series/ctx_sleep_delay.go
- tools/fast/series/init_and_start.go
- tools/fast/series/wait_for_block_height.go
- tools/fast/series/wait_for_deal_state.go
- tools/fast/tests/retrieval_test.go
Set of FAST updates 
**New Actions**
- ShowMessages
- ShowReceipts
- ClientPayments
**Features**
- InitAndStart series takes a variadic set of functions to apply between `InitDaemon` and `StartDaemon`. This helps with applying configuration changes before the daemon starts.
- CtxSleepDelay now returns a channel which receives a value after the delay time. This allows the function to be more versatile allowing for use inside of `select` statements.
- CreateStorageMinerWithAsk now requires a sector size for the miner.
**Bugs**
- When tearing down processes with `TeardownProcess`, new processes will not use the same directory as a previous process.
- DHTFindProvs now returns a `*json.Decoder` so more than one value can be parsed from the LDJSON stream.
> FAST Updates

- node/node.go
Log a message when initial chain sync is finished
```
INFO node: initial chain sync complete! chain head height 0, tipset key { bafy2bzacedigwlfe3w3yixisia2cqotnvbnostc4ecssokmou6stcrclt3obe }, blocks { bafy2bzacedigwlfe3w3yixisia2cqotnvbnostc4ecssokmou6stcrclt3obe }
```
Resolves #3247
> Log a message when chain is synced

- commands/client_daemon_test.go
- commands/deals_daemon_test.go
- commands/miner.go
- commands/mining_daemon_test.go
- commands/protocol.go
- porcelain/protocol.go
- porcelain/protocol_test.go
- tools/fast/action_miner_test.go
- tools/fast/bin/localnet/main.go
- tools/fast/tests/retrieval_test.go
Moves the max piece size into the json response so that it can be used from FAST.
Resolves #3229
> Protocol command returns max piece size

- scripts/install-filecoin-parameters.sh
The submodule SHA-change brings two important features into go-filecoin:
- The `mining start` command will fail if Groth parameters and verifying keys for the sector size which a miner has selected do not yet exist in the parameter cache.
- The `paramfetch` binary now uses `ipget` to download Groth parameters and keys instead of hitting the IPFS (HTTP) Gateway. This will make `paramfetch` slower, but more reliable.
> feat(consume latest sector builder and paramfetch)

- main.go
Graphsync is very spammy with the debug logs producing 30k-60k logs in 5 minutes per host on nightly. This might indicate a larger issue but the spam is so bad that it fills our elastic search instance to the point that we can gather no logs.
We reduced bitswap to error only as well, so I believe we will want to do the same here.
Almost all of which seem to be this line: https://github.com/ipfs/go-graphsync/blob/405d87c1c392c326e529929f18fd648ab2e3d07e/requestmanager/asyncloader/responsecache/responsecache.go#L84
> Set graphsync logger to info

- functional-tests/network-deployment/README.md
- functional-tests/network-deployment/bootstrap_test.go
- functional-tests/network-deployment/logging_test.go
- functional-tests/network-deployment/miner_workflow_test.go
- functional-tests/network-deployment/relay_check_test.go
- go.mod
- go.sum
- testhelpers/testflags/flags.go
- tools/fast/action_deals.go
- tools/fast/bin/localnet/main.go
- tools/fast/environment/environment_memory_genesis.go
- tools/fast/fastesting/deployment.go
- tools/fast/process.go
- tools/fast/process_options.go
- tools/fast/series/find_deal_by_id.go
- tools/fast/series/wait_for_chain_message.go
This PR provides us a fairly simple way to write functional tests that can be run against a deployed network, and support local development.
Due to bootstrapping issues I've added a `fastesting.NewDeploymentEnvironment` which provides the barebones to support both the deployed networks as well as local development.
> Network deployment tests

- .circleci/config.yml
We no longer download the required params for mining in deps, so we must download them before we build the docker container.
> Download missing proof params for docker container

- commands/daemon_daemon_test.go
- commands/init_daemon_test.go
- commands/version_daemon_test.go
- testhelpers/commands.go
This prevents a race for the port causing flaky tests, #3145.
> Fix TestDaemon to allow the OS to allocate a port for the command API when binding.

- commands/id_daemon_test.go
- commands/ping_daemon_test.go
- commands/swarm_daemon_test.go
- testhelpers/commands.go
Along with #3291, fixes #3145.
> Defer swarm listen port allocation until binding.

- commands/daemon.go
- commands/env.go
- commands/main.go
- node/testing.go
I have upcoming changes that use this to perform CLI tests against an in-process Filecoin node.
For #3180. Also closes #2641.
> Export RunAPIAndWait for use in in-process integration tests.

- chain/store_test.go
- chain/syncer_integration_test.go
- chain/testing.go
- commands/schema/filecoin_block.schema.json
- consensus/block_validation.go
- consensus/block_validation_test.go
- consensus/expected.go
- consensus/expected_test.go
- consensus/processor_test.go
- core/policy_test.go
- gengen/util/gengen.go
- metrics/heartbeat_test.go
- mining/block_generate.go
- mining/worker.go
- mining/worker_test.go
- node/block_propagate_test.go
- plumbing/msg/waiter_test.go
- protocol/block/mining_api_test.go
- protocol/hello/hello_test.go
- sampling/chain_randomness.go
- testhelpers/chain.go
- testhelpers/consensus.go
- types/block.go
- types/block_test.go
- types/testing.go
- types/ticket.go
- types/tipset.go
- types/tipset_test.go
- wallet/wallet_test.go
Closes #2222 This is just the datastructure change from a single ticket per block to an array of tickets.  There are no updates to the way tickets are created and used here.
> Ticket array

- consensus/block_validation.go
- net/validators.go
- net/validators_test.go
- node/node.go
- testhelpers/consensus.go
This PR does the following things: 
- adds a block syntax validator to the node pubsub and closes #2783. I have created #3277 as a placeholder for bringing block validation inline with the spec.
- also adds a mockable block validator, the topic validator uses this in its unit test.
- adds an integration that could be improved in #3285 
- adds metrics to track the number of decode and syntax failures.
> register block syntax validation on pubsub

- functional-tests/lib/helpers.bash
- functional-tests/retrieval
After messages were removed from the `chain ls` output, the megascript broke.
This changeset modifies the megascript to instead use `show messages` to look for `commitSector` and `submitPoSt`.
> update megascript to use "show messages" command to look for commitSector and submitPoSt

- commands/mining.go
- commands/mining_daemon_test.go
- porcelain/api.go
- porcelain/sectorbuilder.go
- porcelain/sectorbuilder_test.go
- tools/fast/action_mining.go
To allow miners to have more control over self-sealed data, this PR breaks apart the `mining seal-now` command into two parts:
1. `mining add-piece <file>` - adds arbitrary data to a staged sector
1. `mining seal-now` - forces the sealing of any staged sectors
Previously, `seal-now` would generate a staged sector if one didn't exist; now the only way a miner can create a staged sector without accepting a deal is to use `add-piece`.
resolves #3044
> Add "mining add-piece" command

- rleplus/rleplus.go
- rleplus/rleplus_test.go
When RLE+ was implemented, the maximum run length was 16384, because of the very specific use case (fault sets) and how they were specified.  Now there is some flux in the specification of exactly what is encoded with RLE+ -- whether it is indices into a list of sector commitments or sector ids, and how many numbers can be encoded with RLE+.
Allow runs of up to `MaxUint64`.  This will cover any use cases we will likely run across with go-filecoin, and still prevents attacks by limiting the allowed size of uvarints to 10 bytes.
> Allow larger runs in RLE+

- actor/builtin/builtin.go
- actor/builtin/initactor/init.go
- actor/builtin/initactor/init_test.go
- actor/builtin/miner/miner_test.go
- address/constants.go
- chain/power_table_view_test.go
- chain/syncer_integration_test.go
- commands/actor.go
- commands/actor_daemon_test.go
- commands/miner_daemon_test.go
- commands/protocol.go
- commands/protocol_daemon_test.go
- commands/schema/actor_ls.schema.json
- consensus/genesis.go
- fixtures/setup.json
- gengen/main.go
- gengen/util/gengen.go
- gengen/util/gengen_test.go
- go.mod
- node/testing.go
- porcelain/protocol.go
- porcelain/protocol_test.go
- testhelpers/iptbtester/genesis.go
- tools/fast/environment/environment_memory_genesis.go
- types/constants.go
closes #3301 
We need a network name accessible internally go-filecoin code so a node can make decisions that depend on which network it's running on (e.g. devnet, testnet, mainnet, etc.). The primary and, perhaps, only decision nodes will need to make is when it should switch protocol versions.
For reasons described in detail here: https://github.com/filecoin-project/specs/pull/456, the network name should established at the time when the genesis block is created and stored in actor state.
This PR introduces the `InitActor` to store the network name. In the future this actor will also provide a map of public key or named addresses to id addresses. There are really three parts to this PR that roughly correspond to the first 3 commits.
1. Create the InitActor with network name in state and …
> Create Init Actor to store Network Name

- clock/clock.go
- go.mod
- go.sum
- testhelpers/clock.go
As a follow on to #3339, this PR replaces the existing clock implementation with a wrapper around [github.com/jonboulle/clockwork](https://github.com/jonboulle/clockwork). The package clockwork was chosen based on the interface's it provides and its frequent usage in the go ecosystem, a full list of importers can be seen [here](https://godoc.org/github.com/jonboulle/clockwork?importers). I wrapped this implementation instead of using it directly to make code changes easier if we decided to use something different, or write our own.
Clock interface:
```go
type Clock interface {
After(d time.Duration) <-chan time.Time
Sleep(d time.Duration)
Now() time.Time
Since(t time.Time) time.Duration
NewTicker(d time.Duration) Ticker
}
```
FakeClock interface:
```go
type FakeClock interface {
Clock
// …
```
> replace clock impl with wrapper around clockwork

- protocol/hello/hello.go
- protocol/hello/hello_test.go
This PR lays the foundation for completing #3319 and later #3268 by modifying the `SayHello` method to receive a response. The method has also been exported so that it may be called externally to receive an updated chain head from a peer.
This is not a permanent change to the hello protocol and will likely be reverted once https://github.com/filecoin-project/go-filecoin/issues/2674 is implemented.
> SayHello returns hello message from peer

- net/peer_tracker.go
- node/block.go
This is a simpler version of a change that has improved devnet forking situation.  It prevents syncing of pubsub messages that come from peers that a node does not have a connection with.
If these messages are valid heads coming in from a new peer then the parallel hello protocol will serve this head to the syncer anyway.  If that hello protocol fails then this change ensures that we don't end up blocking for a 60 second timeout on a peer that we can't connect to.
> Add Has to Peertracker, filter pubsub blocks

- mining/worker.go
- mining/worker_test.go
- node/block_propagate_test.go
- node/node.go
- node/node_test.go
- porcelain/api.go
- porcelain/miner.go
- protocol/block/mining_api_test.go
- protocol/storage/fault_slasher.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
- protocol/storage/prover.go
- protocol/storage/prover_test.go
- testhelpers/mining.go
Use the miner worker address from the miner's state in various places: ticket signing, PoSt proving, accepting proposals, etc.
Companion to PR #3261, resolves #2959
> Use miner worker address (#2959)

- commands/daemon.go
- commands/main.go
- commands/ping_daemon_test.go
- commands/protocol_daemon_test.go
- consensus/genesis.go
- main.go
- node/init.go
- node/node.go
- node/test/api.go
- node/test/builder.go
This PR introduces and demonstrates a couple of things.
`test.NodeBuilder` creates nodes configured for in-memory use. There is existing code in `node/testing.go` to create nodes, primarily `GenNode` and other methods that call into it. My goal is to replace all uses of that with this builder and extensions to it.
`test.NodeAPI` runs a real command API around an in-process node, that listens on a TCP socket. It also provides an in-process client that sends commands to that socket over the cmdkit RPC. That is, it provides both the daemon and client processes, in-process. If using the TestDaemon (deprecated) or FAST, both of those would involve forking processes, and the daemon would use an on-disk repo. The resulting tests run in ⅓ or less of the time and provide direct access to the node …
> Implement test.NodeBuilder and test.NodeAPI for in-process integration tests

- tools/fast/action_chain.go
Missed this while adding the `chain status` command, here's a fix for it.
> add chain status command to fast chain actions

- .circleci/config.yml
disables the use of paramfetch as work continues to make downloading
more consistent and reliable.
paramfetch is now used to exclusively generate Groth proof parameters
during CircleCI build.
In CircleCI docker build, a new cache is created for the larger groth
parameters required to operate docker image in devnets. Larger
parameters are no longer generated by build and testing stages
> use paramcache only, and create a circleci cache for large params

- net/address.go
- net/peer_tracker.go
- net/peer_tracker_test.go
- node/node.go
This PR extends the PeerTracker to have:
- A set of trusted peers that it my be initialized with
- An update function that may be applied to tracked peers, currently is is only exposed via `UpdateTrusted`.
- A method for setting an update function.
- A method for selecting the head with the greatest height from all tracked peers or just the trusted peers.
- Testing for the above
-  An initial set of trusted node which for now are the bootstrap nodes.
This PR makes progress towards implementing chain catch-up logic. In a follow on the trusted peers and select head logic will be used to fully sync a chain before proceeding with caught up chain sync. 
This PR is a follow on to #3327
> PeerTracker has trusted set and SelectHead logic

- .circleci/config.yml
- .codecov.yml
I'm not 100% sure this solves all our problems, but we gotta try.
There remains a few lines of non-determinism which is reproducible locally.
Closes #2785
> Set atomic coverage mode and configure CircleCI to wait for all builds before publishing coverage

- core/handler_integration_test.go
- core/message_queue.go
- core/message_queue_test.go
- core/outbox.go
- core/policy.go
Fixes #3052 (see discussion there for discussion of alternatives).
> Re-queue messages from the losing chain segment in a re-org so that nonces are consistent with the pool.

- commands/init.go
- commands/inspector_daemon_test.go
- config/config.go
- config/config_test.go
- node/builder.go
- node/node.go
- protocol/hello/hello.go
- protocol/hello/hello_test.go
- repo/fsrepo_test.go
closes #2685
Making protocol changes without an upgrade mechanism has forced us to reset the Devnet each release. Resetting the network causes problems when miners using the old code attempt to connect with nodes on the new network. As a short term fix, we added a code SHA check to the Hello protocol to ensure that miners on the network were using exactly the same version of the code. As we move to more durable networks, add protocol upgrades, and expect more customized solutions on the network, the SHA check is no longer necessary and is becomes a hindrance. We would, however, like to have some mechanism that ensures that we can reset the network without incompatible nodes attempting to communicate with each other.
#3298 introduced network name into the genesis block, and #3354 …
> Remove sha check from Hello

- net/protocols.go
- node/builder.go
closes #2509
We use a DHT to discover peers on the network. The DHT is self healing by design, so it will attempt to merge with any other DHT of the same protocol that it finds. Unfortunately, this means that the DHTs of Filecoin nodes on different networks could end up merging and the nodes will end up trying to connect to each other (unsuccessfully since they'll have different genesis nodes).
Append the network name to the DHT protocol to prevent merging.
> use network name to namespace dht

- commands/client.go
Returned a `storagedeal.SignedResponse` from `query-storage-deal`.
```json
{
"State": 7,
"Message": "",
"ProposalCid": {
"/": "bafy2bzacebwfakwyxdnhwfhtapwkerpmps4up5hkte3pmopyteoqexm6foxz4"
},
"ProofInfo": {
"SectorID": 1,
"CommD": "dZ2edPVzA1nSK0PpmFfz4DiTanhYjpchghwN8d1oeg8=",
"CommR": "OodhwUTX1buSWDjZqql0rf2DRJvRmraEbYGyHLakIGg=",
"CommRStar": "aFZOviu+UJkAuMYGLQMzjNlealquZ7BqKI3tX/2YQF4=",
"CommitmentMessage": {
"/": "bafy2bzaceaa4wo5zktetxmm5llsuqhnytsek5wcenhpums6cilovqaady3txg"
},
"PieceInclusionProof": "EAAAAAAAAABEral84RHiyMCNHov3CfFrz7fyFnBV7SIim5V6oiSdaw=="
},
"Signature": "Fl40oZ5WOpRd4sOeWqy+dnt08jkO+yLWmmnqOse100Z1IihVmWp1vUfEEreV6p1eJ2UF9hysL3A3d3baGMNjLwE="
}
```
> Return a SignedResponse from the `client query-storage-deal` command

- actor/storage.go
- state/tree.go
Lower the fanout on our HAMTs to increase performance of state transitions
- Simply use an alternate bitwidth for when creating and loading nodes in our HAMT.
- Based off testing of HAMT performance in https://github.com/ipfs/go-hamt-ipld/pull/33 - bitwidth 4 (fanout = 16) shows  very strong performance. Bitwidth 3 shows slightly stronger performance but approaches diminishing returns and my anxiety is lower than is commonly used in creating HAMTS
- Based of @acruikshank 's testing of Payment Channels however, bitwidth 5 shows the strongest performance in real world tests, so that is what we are using until we have better HAMT tests.
This is a PROTOCOL BREAKING CHANGE because the difference in storage means there will be different state CIDs. We won't be able to change it again after 0.5 …
> Change HAMT bitwidth to 5 for both global state tree and actor state

- node/node.go
- protocol/storage/miner.go
- protocol/storage/miner_test.go
This 15 is hard-coded in the name of expediency, but should be pulled out
into a configuration value, along with other policy constants.
The latch returned from OnNewHeaviestTipSet reduces the miner_test latency
from some 8 seconds to 20ms.
This is a partial solution to #3429.
> Storage miner worker waits 15 rounds before beginning PoSt computation.

- chain/get_ancestors.go
- chain/get_ancestors_test.go
- chain/syncer.go
- consensus/expected.go
- node/node.go
- plumbing/cst/chain_state.go
- plumbing/msg/waiter.go
- sampling/chain_randomness.go
- sampling/chain_randomness_test.go
Rational PoSt has no lookback, the chain is sampled at the opening of the proving window.
The spec is unclear about what to do if this is a null tipset, this PR takes the previous
non-empty tipset. This is intended to make sense along with #3450, which waits for the
chain to settle before beginning a PoSt.
This removes PoSt challenge generation from the scope of #1872.
The code that gets the blocks for sampling is all waaay more complicated than necessary now (#3025).
> Remove lookback from chain sampling for PoSt challenge seed.

- commands/log.go
closes #3435 
Related:
go-log has recently been updated to use a different backend, I am going to assume said update fixes this. This should work until we upgrade.
> Fix go-log level setting

- protocol/hello/hello.go
This will allow filecoin nodes to continue to connect to the stats dashboard and other non-hello protocol speaking services.
> do not close connection if hello not supported

- net/peer_tracker.go
- net/peer_tracker_test.go
Wrote some racy code that flaked in CI, here's a fix for it. I would be great to run go's [race-detector](https://blog.golang.org/race-detector) as a part of CI.
> fixed race in peer update

- fixtures/setup.json
- version/protocol_versions.go
This will allow us to deploy the user devnet with a network name distinct from staging.
Future work will make this more flexible.
Context in #3491.
> Change user devnet name to be distinct from staging network. Change setup.json to use go-filecoin-test.

- protocol/hello/hello.go
When a peer does not share our genesis block close the libp2p **connection** with them.
> close connection on bad genesis block hello

- commands/chain.go
- commands/utils.go
- node/builder.go
- plumbing/api.go
- plumbing/cst/chain_state.go
This PR closes #3414
Of the options discussed here: https://github.com/filecoin-project/go-filecoin/issues/3442#issuecomment-532071672, we are going with C: bouncing the node after a call to SetHead to trigger chain reprocessing.
> expose set head and sync over cli

- chain/syncer_integration_test.go
- chain/syncer_test.go
- clock/clock.go
- clock/ticker.go
- clock/timer.go
- consensus/block_validation_test.go
- mining/worker_test.go
- net/graphsync_fetcher_test.go
- net/validators_test.go
- node/block_propagate_test.go
- testhelpers/clock.go
- testhelpers/clock_test.go
Adds timer functionality to clock and fake clock, so we can use timers but still test them easily
Based off https://github.com/jonboulle/clockwork/pull/22 -- merges code in from base library and PR, so that we are not dependent on https://github.com/jonboulle/clockwork which seems to be somewhat dead.
This is a bunch of code but the vast majority of it has moved over with only minor modifications from the source library.
Here are the deltas from the source library:
- everything related to the fake clock is moved over to testhelpers
- I used the existing factory method names we were using in our code
- the tests have been updated to use testify
- I renamed "sleeper" to "timer" cause it make more sense to me
- I removed one test of a private function because we intentionally keep our tests …
> feat(clock): add timer functionality

- net/graphsync_fetcher.go
- net/graphsync_fetcher_test.go
- node/builder.go
When a peer becomes unresponsive to Graphsync Fetcher requests, fail more quickly and move on to other peers
- Timeout for a graphsync request is now based on unresponsiveness, rather than total time. IOW -- if a request stop sending data for a specific time, cancel it. 
- Because the timeout is based on unresponsiveness rather than total time, use a shorter timeout than before (10 seconds)
- Also provides variadic options struct to the fetcher to override the
unresponsiveness timeout
- Add tests of timeout behavior to verify behavior when various requests simply hangup with no further response
fix #3371
> Better shorter timeouts on Graphsync Requests

- go.mod
- go.sum
Minor bug in graphsync code was generating error messages that should not have been there. See: https://github.com/ipfs/go-graphsync/pull/38
Just updates dependency
> chore(deps): update to fix graphsync bug

- commands/daemon.go
- commands/ping_daemon_test.go
- commands/protocol_cmd_test.go
- node/block.go
- node/block_mining_submodule.go
- node/block_propagate_test.go
- node/blockstore_submodule.go
- node/builder.go
- node/chain_submodule.go
- node/fault_slasher_submodule.go
- node/hello_protocol_submodule.go
- node/helpers.go
- node/mesaging_submodule.go
- node/message.go
- node/message_propagate_test.go
- node/network_submodule.go
- node/node.go
- node/node_test.go
- node/retrieval_protocol_submodule.go
- node/sector_builder_submodule.go
- node/storage_networking_submodule.go
- node/storage_protocol_submodule.go
- node/testing.go
- node/wallet_submodule.go
- protocol/block/mining_api_test.go
- protocol/retrieval/retrieval_protocol_test.go
**Remaining work:**
**Following PRs:**
- cleanup initialization for each submodule.
- split start/stop code into pieces and move them to each submodule. 
- move submodules to their own package to force visibility issues
> refactor: cleanup node internals 

- actor/builtin/miner/miner.go
- actor/builtin/miner/miner_test.go
- testhelpers/core.go
Add the Miner [`addFaults`](https://github.com/filecoin-project/specs/blob/069882c3e0c61ff19512879a6ceb0a422835a523/actors.md#addfaults) method, and use these faults in `submitPoSt`.
The code is based on the spec and is not validating that the faulted sector ids are in the current sector commitments.  I've confirmed that the sector builder can handle bogus sector ids, but it's easy enough to add the validation if that seems prudent.
Also, [`submitPoSt`](https://github.com/filecoin-project/specs/blob/069882c3e0c61ff19512879a6ceb0a422835a523/actors.md#submitpost) no longer needs the `faults` parameter but we [still have it in the codebase](https://github.com/filecoin-project/go-filecoin/blob/2879caa02d9d9be6dbb36cae05de5b447e92ca68/actor/builtin/miner/miner.go#L273).
resolves #3425
> Miner addFaults method

- CONTRIBUTING.md
@phritz departed the project 5 months ago and dropped maintainer status, but this doc wasn't updated and may mislead people.
While we'd welcome a return, I think regaining that status would require re-nomination.
FYI @whyrusleeping
> Remove @phritz from maintainer list

- node/blockservice_submoodule.go
- node/blockstore_submodule.go
- node/builder.go
- node/chain_submodule.go
- node/helpers.go
- node/messaging_submodule.go
- node/network_submodule.go
- node/node.go
One of many PRs addressing https://github.com/filecoin-project/go-filecoin/issues/3140.
This PR attempts to cleanup the `build()` method and separate it into pieces that build each of the subsystems instead.
> refactor: cleanup node initialization 

- testhelpers/testflags/flags.go
- testhelpers/util.go
To enable running the network deployment tests during network setup we can build the tests as an executable binary using the `-c` flag of `go test`. Currently all of our tests are forced into using a binary located at the project root. This flags allows overriding the binary that will be used for tests which fork `go-filecoin`.
> Allow setting path to binary under test

- chain/message_store.go
- chain/message_store_test.go
- chain/syncer.go
- chain/testing.go
- commands/message_daemon_test.go
- commands/show.go
- commands/show_test.go
- consensus/genesis.go
- consensus/processor_test.go
- gengen/util/gengen.go
- message/inbox.go
- message/policy.go
- message/policy_test.go
- metrics/heartbeat_test.go
- mining/block_generate.go
- mining/worker_test.go
- net/graphsync_fetcher.go
- net/graphsync_fetcher_test.go
- plumbing/api.go
- plumbing/cst/chain_state.go
- plumbing/msg/waiter.go
- plumbing/msg/waiter_test.go
- porcelain/chain.go
- tools/fast/series/wait_for_chain_message.go
- types/block.go
- types/block_test.go
- types/message.go
- types/tipset_test.go
This PR is a step towards BLS message signature support.
We need to support both BLS and Secp (elliptic curve) signed messages. The mechanism for this is to maintain separate data structures for each. The BLS messages will have a single signature in the block header, while the Secp messages will each have their own signature. The spec defines a TxMeta struct to contain the keys forr both these structures that replaces a single key for the Secp messages.
This PR introduces the `TxMeta` struct in the block header. It contains a `SecpRoot` that points to the messages, and a `BLSRoot` which, for now, always points to an empty message list. All the rest of the work in this PR exists to permit access to the Secp messages through this new structure.
> Separate BLS and Secp messages in block header.

- chain/car.go
- chain/car_test.go
- commands/chain.go
- go.mod
- go.sum
- plumbing/api.go
- plumbing/cst/chain_state.go
Allow a go-filecoin node to export a chain to a [car file](https://github.com/ipfs/go-car) and import a chain from a car file.
Allow a go-filecoin node to initialize from a car file (filed #3554 to address this)
- A new file: `car.go`  was added to the chain/ package. This file contains all logic for importing and exporting a chain.
- Two new sub-commands were added to the `chain` command:
```
go-filecoin chain export <file> <TipSetKey...> - Export the chain store to a car file.
go-filecoin chain import <file> - Import the chain from a car file.
```
- Export is an operation on the chain store, it writes its internal store to a car file.
- Import is an operation on the chain store, it imports the contents of a car file into its blockstore.
#3554
#3555
> Export and Import chain to/from a .car file

- main.go
#3557 removed support for `GO_FILECOIN_LOG_LEVEL`, this adds it back. It now expects a string instead of an integer.
> add back support for GO_FILECOIN_LOG_LEVEL

- syncer/dispatcher.go
- syncer/dispatcher_test.go
This PR introduces the syncer dispatcher.
It includes a basic priority queue subcomponent for explicitly tracking target chains
This is part of bringing chain sync up to spec
Add syncer package
Add unused dispatcher abstraction
Outfit dispatcher with a nice priority queue
After this PR others will shortly follow that hook the dispatcher up to incoming network traffic and put it in charge of issuing `HandleNewTipset` calls.
Closes issue # (still haven't written it up, coming soon)
As this is pretty disconnected from existing code either @acruikshank or @icorderi are equally equipped to review.  Whoever gets to it first.
> Introduce syncer dispatcher

- internal/app/go-filecoin/internal/submodule/chain_submodule.go
- internal/app/go-filecoin/internal/submodule/discovery_submodule.go
- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/app/go-filecoin/node/block.go
- internal/app/go-filecoin/node/builder.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/discovery/bootstrap.go
We need to get syncing and bootstrapping properly ordered per new spec changes.  We should also do some cleanup along the way.
- Separate out syncer submodule from chain
- syncer dispatcher start wrapped within syncerSubmodule.Start(), chain.Load() wrapped in chainsubmodule.Start().  discovery submodule start blocks on bootstrapper start meeting security conditions.
- chain.Start --> discovery.Start --> syncer.Start
- pubsub no longer waits on first syncer invocation so remove the latch
Closes issue #3582
> Separate syncer submodule

- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/app/go-filecoin/node/builder.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/chain/syncer.go
- internal/pkg/chain/syncer_integration_test.go
- internal/pkg/chain/testing.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/chain_selector.go
- internal/pkg/consensus/weight_test.go
- internal/pkg/net/graphsync_fetcher_test.go
- internal/pkg/net/validators_test.go
We want to reset the alphanet soon.  We don't want to carry along the baggage of the old broken weighting function.
- Remove old weight function
- Remove protocol version table from code no longer checking it
- Remove tests testing for upgrade behavior
Closes issue #
> Remove protocol upgrade and deprecated Weight()

- cmd/go-filecoin/miner_daemon_test.go
- internal/app/go-filecoin/internal/submodule/chain_submodule.go
- internal/app/go-filecoin/plumbing/msg/waiter.go
- internal/app/go-filecoin/plumbing/msg/waiter_test.go
- internal/pkg/chain/car_test.go
- internal/pkg/chain/init.go
- internal/pkg/chain/store.go
- internal/pkg/chain/store_test.go
- internal/pkg/chain/testing.go
- internal/pkg/chain/tip_index.go
- internal/pkg/chainsync/chainsync.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher_test.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/chainsync/internal/syncer/syncer_integration_test.go
- internal/pkg/chainsync/internal/syncer/syncer_test.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/consensus/processor.go
- internal/pkg/consensus/protocol.go
- internal/pkg/message/handler_integration_test.go
- internal/pkg/message/inbox_test.go
- internal/pkg/message/policy_test.go
- internal/pkg/types/message.go
- internal/pkg/types/testing_messages.go
- tools/migration/migrations/repo-1-2/migration.go
We want to move from blocks that contain the state root and receipt CID AFTER applying their messages, to storing the state root and receipts cid of the tipset it is built upon.
This PR transitions message receipts from a data structure transmitted with individual blocks to a collection only generated when a Tipset is processed and stored locally. This transition has a few consequences:
1. We need to save the receipt root as well as the state root after running a state transition on a TipSet. This happens in `syncer.syncOne`. In a future PR this will be used to populate and validate the parent receipt root in block headers.
2. We stop retrieving receipts in graphsync fetcher.
3. The waiter must now locate a receipt by first locating the message by Cid and then find the receipt that …
> Stop fetching message receipts

- internal/app/go-filecoin/plumbing/msg/waiter.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/processor.go
- internal/pkg/consensus/processor_test.go
- internal/pkg/consensus/testing.go
- internal/pkg/consensus/validation.go
- internal/pkg/consensus/validation_test.go
- internal/pkg/message/outbox.go
- internal/pkg/message/testing.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/testhelpers/consensus.go
- internal/pkg/types/signed_message.go
- internal/pkg/vm/actor/builtin/miner/miner_test.go
- internal/pkg/vm/gas_tracker.go
- tools/gengen/util/gengen.go
The processor doesn't use the signatures. Signatures in a message or block must be validated before passing to the processor, as part of block syntax validation (BLS message signatures can only be validated in aggregate, not individually) or before the message pool.
This removes signatures from the processor.
Note that blocks and messages fetched by graphsync aren't validated at all! #3312 (cc @ZenGround0)
Change DefaultProcessor methods to accept `UnsignedMessage`s.
> Change ApplyMessagesAndPayRewards to accept unsigned messages

- CONTRIBUTING.md
Our contributing guide was missing some established norms around PR independence and comments.
In discussion, @icorderi and @anorth agreed on the use of `Dragons:` as a comment header marking rough code that's in the middle of being improved. This is intended as an experiment, where we will consider keeping the convention if, in a few months, there are very few uses of `Dragons:` more than two weeks old, but it has been useful during that period.
- Document guidance for separating functional changes from refactors, and landing large efforts incrementally
- Document conventions for comment headers.
> Document guidelines for comments and PRs

- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/chainsync/chainsync.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/chainsync/internal/syncer/syncer_integration_test.go
- internal/pkg/chainsync/internal/syncer/syncer_test.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/consensus/protocol.go
- internal/pkg/consensus/testing.go
- internal/pkg/mining/scheduler_test.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/sampling/chain_randomness.go
- internal/pkg/sampling/chain_randomness_test.go
- internal/pkg/testhelpers/consensus.go
We need our consensus election to look back into chain history so that our elections can prevent grinding per the spec.
Add lookback parameter to consensus election to get us up to spec.  Hardcoding to 5.  This PR involves 0 cleanup and sticks to old ugly patterns.  On the plus side it is very simple and doesn't make anything worse.
Closes issue #2223
> Election works off of a lookback hardcoded to 5

- cmd/go-filecoin/show.go
- cmd/go-filecoin/show_test.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/porcelain/chain.go
- internal/pkg/block/full_block.go
- internal/pkg/chain/testing.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/chainsync/internal/syncer/syncer_integration_test.go
- internal/pkg/chainsync/internal/syncer/syncer_test.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/consensus/processor.go
- internal/pkg/consensus/processor_test.go
- internal/pkg/consensus/protocol.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/scheduler_test.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/testhelpers/consensus.go
The spec dictates (or will dictate) that state root and receipt root in the block header reflect the result of messages processed in the parent tipset, not messages processed in the currrent  block as currently implemented.
1. Set state root and receipt root to the values saved with the parent tipset when generating a block. The block generator must still run a state transition in order to determine which messages are valid to include.
2. When validating a block, only validate that the block miner has included the correct state root and message receipts for the parent tipset. Here we stop running state transitions on individual blocks.
3. Modify the message waiter to pull receipts for an entire tipset. This involves some slightly involved logic around determining the index of a receipt …
> Block state root and receipt cid now reference result of parent tip set message processing

- internal/app/go-filecoin/internal/submodule/blockstore_submodule.go
- internal/app/go-filecoin/internal/submodule/network_submodule.go
- internal/app/go-filecoin/node/init.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/node/testing.go
- internal/app/go-filecoin/plumbing/msg/testing.go
- internal/pkg/chainsync/internal/syncer/syncer_integration_test.go
- internal/pkg/consensus/actor_state_test.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/sectorbuilder/rustsectorbuilder.go
- internal/pkg/sectorbuilder/testing/builder.go
- tools/gengen/util/gengen.go
- tools/gengen/util/gengen_test.go
Most places we instantiate a blockservice, it's "offline" and adds no value. The hamt package provides a wrapper to adapt to the required interface.
Call `hamt.CSTFromBstore` where possible.
Also remove unnecessary blockservice from sector builder.
> Remove a bunch of unnecessary block services wrapping blockstores.

- internal/app/go-filecoin/porcelain/client.go
- internal/app/go-filecoin/porcelain/client_test.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/protocol/storage/miner.go
- internal/pkg/protocol/storage/miner_test.go
- internal/pkg/vm/abi/abi.go
- internal/pkg/vm/actor/builtin/miner/miner.go
- internal/pkg/vm/actor/builtin/miner/miner_test.go
This is the only method utilizing multiple returns. Changing this will let us change the
`dispatch.FunctionSignature` to return a single value instead of array, and then propagate
this to the MessageReceipt. See #3568.
I avoided creating a custom return type for the tuple just to save on noise, but can do so if requested. This also uses uint64 instead of `types.BlockHeight` because I expect the spec to define epoch numbers to be uint64 anyway (and we can ditch the type wrapper). Retaining the `BlockHeight` would require a custom ABI type.
Return a `UIntArray` (always of 2 elements) instead of multiple values.
> Change StorageMinerActor.GetProvingWindow to return UIntArray instead of multiple returns.

- cmd/go-filecoin/actor.go
- cmd/go-filecoin/actor_daemon_test.go
- internal/pkg/consensus/genesis.go
- internal/pkg/types/constants.go
- internal/pkg/types/power_report.go
- internal/pkg/vm/abi/abi.go
- internal/pkg/vm/actor/actor.go
- internal/pkg/vm/actor/builtin/builtin.go
- internal/pkg/vm/actor/builtin/power/power.go
- internal/pkg/vm/actor/builtin/power/power_test.go
- internal/pkg/vm/address/constants.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
We need a power actor distinct from both miner actor and storage market actor per the new 
[spec](https://filecoin-project.github.io/specs/#storagepoweractor-implementation)
This PR introduces it
-Power updates can be called by anyone so totally insecure (but useful for mocking out power for tests before we have a correct miner in the state machine)
- Missing all power actor calls unrelated to table updates
- Uses old vm infrastructure and patterns, it might need to change a lot with upcoming changes
New Power Actor in state machine
Rest of system does not interact with it, that comes next
Closes issue #
> Basic Insecure Power Actor

- cmd/go-filecoin/miner_daemon_test.go
- functional-tests/faucet_test.go
- internal/app/go-filecoin/node/testing.go
- internal/pkg/consensus/genesis.go
- internal/pkg/consensus/power_table_view_test.go
- internal/pkg/testhelpers/iptbtester/genesis.go
- tools/fast/environment/environment_memory_genesis.go
- tools/gengen/main.go
- tools/gengen/util/gengen.go
- tools/gengen/util/gengen_test.go
Genesis block requires a timestamp field so that a GenesisTime value may be derived as defined in the [clock section of the spec](https://filecoin-project.github.io/specs/#systems__filecoin_nodes__clock). Further motivation may also be found here: https://github.com/filecoin-project/go-filecoin/issues/3653
Modify `GenGenesisCar`, `GenGen`, `MustGenerateGenesis`, and genesis Config to accept a timestamp for the genesis block.
When a genesis block is required for a tests its timestamp is set to `time.Unix(123456789, 0)` for consistency
When calling the gengen binary, time is accepted as a command line argument (`date +%s`) defaulting to 123456789 if no value is given for the flag.
Instead of modifying the aforementioned methods to accept a timestamp as an argument the `GenesisCfg` structure …
> Add timestamp to genesis block

- internal/pkg/vm/actor/builtin/initactor/init.go
- internal/pkg/vm/actor/builtin/miner/miner.go
- internal/pkg/vm/actor/builtin/miner/miner_test.go
- internal/pkg/vm/actor/builtin/paymentbroker/paymentbroker.go
- internal/pkg/vm/actor/builtin/paymentbroker/paymentbroker_test.go
- internal/pkg/vm/actor/builtin/power/power.go
- internal/pkg/vm/actor/builtin/storagemarket/storagemarket.go
- internal/pkg/vm/actor/storage.go
- internal/pkg/vm/actor/testing.go
- internal/pkg/vm/internal/dispatch/dispatch.go
- internal/pkg/vm/internal/exitcode/exitcode.go
- internal/pkg/vm/internal/pattern/pattern.go
- internal/pkg/vm/internal/result/result.go
- internal/pkg/vm/internal/runtime/runtime.go
- internal/pkg/vm/internal/vmcontext/actor_state_handle.go
- internal/pkg/vm/internal/vmcontext/actor_state_handle_test.go
- internal/pkg/vm/internal/vmcontext/export.go
- internal/pkg/vm/internal/vmcontext/export_test.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- internal/pkg/vm/internal/vmcontext/vmcontext_test.go
- internal/pkg/vm/testing.go
Spec changed. We need to make several changes to get closer to the spec.
We have an opportunity to make some refactors.
(see https://github.com/filecoin-project/go-filecoin/pull/3636 for conv with the spec team)
- split the existing Runtime into two abstractions a `Runtime` which represents the VM and an `InvocationContext` that is tied to the current executing method.
- New `ActorStateHandle`, still in conv with spec on some details. 
- actors are not using new `ActorStateHandle` to retrieve state, followup PR 
- VMContext implementation is still one monolith, followup PR 
- `Storage` visibility is not clear until new actors pseudocode lands.  
- Left gas, message, and address calls in place until we delete the actors using them.
> feat: new vm runtime

- internal/app/go-filecoin/plumbing/api.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/consensus/actor_state.go
- internal/pkg/consensus/power_table_view.go
- internal/pkg/consensus/testing.go
- tools/fast/action_miner_test.go
- tools/fast/tests/retrieval_test.go
- tools/gengen/util/gengen.go
- Power table is backed by power actor
- `miner power` command is backed by power actor
- gengen setup only goes through power actor, not storagemarket actor, sector commitment, submitpost flow
- power table test helpers updated
NOT CHANGED
- deprecated storage market actor still backs create storage miner (most skipped tests from #3642 will now fail)
> Power calculated by power actor

- internal/pkg/chain/store.go
- internal/pkg/chainsync/chainsync.go
- internal/pkg/chainsync/internal/dispatcher/dispatcher.go
- internal/pkg/chainsync/internal/dispatcher/dispatcher_test.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/chainsync/internal/syncer/syncer_integration_test.go
- internal/pkg/chainsync/internal/syncer/syncer_test.go
The syncer needs to be able to transition between catchup and follow states based on gaps in tipset epochs and only set chain heads during the follow state.
* Introduce a transitioner type and new dispatcher data and logic calling it to manage chain sync transitions 
* Reintroduce the boolean into HandleNewTipSet so that the caller can differentiate modes to control head setting
* Expose a method on the syncer for directly setting the staged head to call during transitions 
* Cleanup syncer by removing unused lock (all calls to syncer are serialized through the dispatcher's event loop)
Closes issue #3666
Testing this is going to be quite challenging.  I'm working on something I'd like to include in this PR but wanted to surface this work first.  In the interest of moving faster I might …
> Catchup Follow transitions

- cmd/go-filecoin/daemon.go
- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/app/go-filecoin/node/block_propagate_test.go
- internal/app/go-filecoin/node/builder.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/chain/store.go
- internal/pkg/clock/chainclock.go
- internal/pkg/clock/chainclock_test.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/expected.go
- internal/pkg/testhelpers/chainclock.go
- tools/fast/series/ctx_sleep_delay.go
[Spec Clock](https://filecoin-project.github.io/specs/#systems__filecoin_nodes__clock)
- Implement the ChainEpoch clock on the Node as described in the spec exposing it as an interface wrapping the existing System Clock.
- Pass the ChainEpoch clock to the syncer module as it will be used during block validation later.
Closes issue #3652
> Implement ChainEpochClock similar to spec definition 

- cmd/go-filecoin/address.go
- internal/app/go-filecoin/plumbing/api.go
Allow creation of BLS addresses through command line.
New option for `go-filecoin address new --type=[bls|secp256k1]` with default value `secp256k11`.
Closes issue #
> Added command line option for creating bls addresses.

- internal/pkg/consensus/genesis.go
- internal/pkg/consensus/processor.go
- internal/pkg/vm/actor/builtin/initactor/init.go
- internal/pkg/vm/actor/builtin/miner/miner.go
- internal/pkg/vm/actor/builtin/miner/miner_test.go
- internal/pkg/vm/actor/builtin/paymentbroker/paymentbroker.go
- internal/pkg/vm/actor/builtin/power/power.go
- internal/pkg/vm/actor/builtin/storagemarket/storagemarket.go
- internal/pkg/vm/actor/storage.go
- internal/pkg/vm/actor/storage_test.go
- internal/pkg/vm/actor/testing.go
- internal/pkg/vm/internal/exitcode/exitcode.go
- internal/pkg/vm/internal/runtime/runtime.go
- internal/pkg/vm/internal/storagemap/storagemap.go
- internal/pkg/vm/internal/storagemap/storagemap_test.go
- internal/pkg/vm/internal/vmcontext/actor_state_handle.go
- internal/pkg/vm/internal/vmcontext/actor_state_handle_test.go
- internal/pkg/vm/internal/vmcontext/export.go
- internal/pkg/vm/internal/vmcontext/export_test.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- internal/pkg/vm/internal/vmcontext/vmcontext_test.go
- internal/pkg/vm/testing.go
- internal/pkg/vm/vm.go
The new spec defines methods to result either in a success with a value returned or they Abort. 
- This PR renames the old Send to `LegacySend` while
- Adds a new `Send` with a single value being returned. 
See #3681.
> feat: new Send api to match spec

- internal/app/go-filecoin/node/block_propagate_test.go
- internal/app/go-filecoin/node/message_propagate_test.go
- internal/app/go-filecoin/node/node_test.go
- internal/app/go-filecoin/node/test/builder.go
- internal/app/go-filecoin/node/testing.go
- internal/pkg/protocol/mining/mining_api_test.go
- internal/pkg/protocol/retrieval/retrieval_protocol_test.go
As part of ongoing work to move integration tests to an in-process framework it's in our best interest to simplify that framework.  This PR does so by removing a legacy function `GenNode` with the similar new `node/test.Builder` abstraction
All calls to `GenNode` call the node test builder
Node test builder takes in node builder options (need to check in with @anorth about this one)
Move some things around to remove cyclic dependencies.  Mostly achieved by moving our node tests to the `node_test` package from the `node` package(!!)
Closes issue #3484
> Node test builder simplification

- cmd/go-filecoin/actor_daemon_test.go
- cmd/go-filecoin/address_daemon_test.go
- cmd/go-filecoin/bootstrap_daemon_test.go
- cmd/go-filecoin/chain_daemon_test.go
- cmd/go-filecoin/config_daemon_test.go
- cmd/go-filecoin/dag_daemon_test.go
- cmd/go-filecoin/dht_daemon_test.go
- cmd/go-filecoin/id_daemon_test.go
- cmd/go-filecoin/leb128_test.go
- cmd/go-filecoin/main.go
- cmd/go-filecoin/message_daemon_test.go
- cmd/go-filecoin/mining_daemon_test.go
- cmd/go-filecoin/mpool_daemon_test.go
- cmd/go-filecoin/outbox_daemon_test.go
- cmd/go-filecoin/show_test.go
- cmd/go-filecoin/stats_daemon_test.go
- cmd/go-filecoin/swarm_daemon_test.go
- internal/app/go-filecoin/node/message.go
- internal/app/go-filecoin/node/test/api.go
- internal/app/go-filecoin/node/testing.go
- internal/app/go-filecoin/porcelain/api.go
- internal/app/go-filecoin/porcelain/message.go
- internal/pkg/message/pool.go
- internal/pkg/testhelpers/output.go
Follow on to #3712, see that PR for motivation
More changes to tests removing dependence on test daemon
Minor improvements to testing infrastructure to enable tests, particularly fixing Run and RunFail to correctly test failed runs.
Closes issue #
> Move daemon integration tests to in process node tests

- go.sum
- internal/app/go-filecoin/node/node.go
- internal/pkg/block/block.go
- internal/pkg/block/block_test.go
- internal/pkg/block/ticket.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/testing.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/scheduler_test.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/testhelpers/consensus.go
We need to move go-filecoin to election post.  To do this we will need to communicate data about the post process between validators and block producers using header data fields.
- Added Deprecated to the name of electionProof field that election post will make obsolete
- Add needed fields to the block header for election post
- Ensure lengths of variable length post data fields are consistent during syntax validation
Note: I've put several fields as top level slices in the block header.  Originally I had a single slice of PoStCandidates in the block header closer to the spec's data format.  I moved to this layout to get around complications with the refmt cbor encoding.  I would have had to define a custom encoding for how to (un)marshal this struct.  Since our encoding is going to …
> Election PoSt prefactor: header data changes

- internal/pkg/consensus/election.go
- internal/pkg/consensus/expected.go
- internal/pkg/proofs/election_poster.go
To implement Election post we need a new set of election machine endpoints to create and verify filecoin block elections.  This PR introduces these new endpoints.
Add epost endpoints.  Correctly preprocess data from election machine function calls to provide to the epost interface.  The ticket winning condition is now up to spec.
I've been assessing how close to spec our randomness drawing and VRF generation is and it is pretty lacking.  I'm saving that change for a follow on.
I'm saving election machine unit testing until the behavior is up to spec, likely in the same followup with correct crypto operations.
> Election machine functionality for epost

- internal/pkg/block/block.go
- internal/pkg/block/block_test.go
- internal/pkg/block/epost_info.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/election.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/testing.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/proofs/election_poster.go
- internal/pkg/testhelpers/consensus.go
On the road to spec compatibility we need to reckon with our encoding.  For our encoding to match the specs we need to embed the Election PoSt information in a set of datastructures matching those specified.  This PR accomplishes that work.
This has the added benefit of helping clean up EPoSt code by passing around logically connected data in a struct.
Note: I hadn't done this before because I had trouble with the refmt encoder.  After spending a little more time with encoding in previous work it turned out that I was badly informed and this is actually trivial!  So this work did not require switching base encodings first.
Closes issue #
> Election Post Header Data to Spec

- go.mod
- go.sum
- internal/app/go-filecoin/internal/submodule/storage_protocol_submodule.go
- internal/app/go-filecoin/plumbing/cst/chain_state.go
- internal/app/go-filecoin/storage_market_connector/client.go
- internal/app/go-filecoin/storage_market_connector/common.go
- internal/app/go-filecoin/storage_market_connector/provider.go
- internal/pkg/cborutil/ipld.go
- internal/pkg/chain/car_test.go
- internal/pkg/chain/message_store.go
- internal/pkg/chain/store.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher.go
- internal/pkg/consensus/genesis.go
- internal/pkg/types/message.go
- internal/pkg/vm/actor/storage.go
- tools/gengen/util/gengen.go
Upgrade to the new hotness.
This required fixing up the storage market connector to traverse the tree-structured state. This in turn requires read access to the state store. It was hard to work out the "best" way to do this: it's new here because previously we used the full query method execution machinery to access state. We can probably make this more obvious and straightforward later.
FYI @acruikshank , @ZenGround0
> Upgrade specs-actors, hamt, and amt

- cmd/go-filecoin/show.go
- cmd/go-filecoin/show_test.go
- internal/app/go-filecoin/plumbing/api.go
- internal/app/go-filecoin/plumbing/cst/chain_state.go
- internal/app/go-filecoin/plumbing/msg/waiter.go
- internal/app/go-filecoin/plumbing/msg/waiter_test.go
- internal/app/go-filecoin/porcelain/chain.go
- internal/pkg/block/block.go
- internal/pkg/block/block_test.go
- internal/pkg/block/tipset_test.go
- internal/pkg/chain/car.go
- internal/pkg/chain/car_test.go
- internal/pkg/chain/message_store.go
- internal/pkg/chain/testing.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher_test.go
- internal/pkg/chainsync/fetcher/graphsync_helpers_test.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/consensus/genesis.go
- internal/pkg/message/inbox.go
- internal/pkg/message/policy.go
- internal/pkg/metrics/heartbeat_test.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/worker_test.go
- internal/pkg/types/message.go
- tools/fast/series/wait_for_chain_message.go
- tools/gengen/util/gengen.go
We read the spec wrong a while back and put the txmeta datastructure directly in the header instead of a cid to it.  This PR moves the datastructure to a cid.
Move txmeta to cid, modify message store interface slightly for convenience, modify graphsync fetcher behavior to handle new subcomponent of full blocks, fix up some trailing ipld-cbor encoding dependencies in the messaging system.
> Messages field moves to cid from TxMeta

- internal/pkg/block/tipset_key.go
Get our encoding up to spec
Our tipsetkey's zero value is kept as nil rather than the empty slice.  This is a good thing for internal reasons but it causes a minor discrepency in encoding that keeps us from being able to write the spec compliant `0x80` bytes for an empty tipset key, instead writing `0xf6`.  This PR tweak our encoding to handle the zero value correctly.
> Tipset key encoding tweak

- cmd/go-filecoin/address.go
- cmd/go-filecoin/miner.go
- cmd/go-filecoin/miner_daemon_test.go
- cmd/go-filecoin/mining.go
- cmd/go-filecoin/mining_integration_test.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/plumbing/api.go
- internal/app/go-filecoin/porcelain/api.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/state/testing.go
- internal/pkg/state/view.go
- tools/fast/action_miner.go
- tools/fast/action_miner_test.go
- tools/fast/series/set_price_ask.go
Replacing use of query messages with state inspection, via the state view type. The porcelain pattern had left us with tons of boilerplate code for fetching individual bits of state. I centralised it, while maintaining indirection from the concrete state types.
> Replace a bunch of verbose miner status plumbing with a single state-view based access

- cmd/go-filecoin/miner.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/plumbing/api.go
- internal/app/go-filecoin/porcelain/api.go
- internal/app/go-filecoin/porcelain/chain.go
- internal/app/go-filecoin/porcelain/protocol.go
- internal/app/go-filecoin/porcelain/protocol_test.go
- internal/pkg/protocol/storage/client_test.go
- internal/pkg/state/testing.go
- internal/pkg/testhelpers/consensus.go
Remove the final uses of query-message so that the new VM is simpler to integrate.
> Replaced all remaining uses of query-message

- internal/pkg/consensus/expected.go
- internal/pkg/proofs/election_poster.go
Two imperfections perfected --
1. We were filtering sectorinfos before passing into the gen and verify post ffi methods.  This works fine now but not with a real election poster
2. We were not filtering duplicate challenge indexes which is needed to prevent replaying partial tickets for more rewards
Closes issue #
> Small Epost fixes

- go.mod
- go.sum
- internal/app/go-filecoin/storage_miner_connector/connector.go
None of our getter methods accepted a state identifier; they were all implicitly scoped to the chain head. See [this convo](https://filecoinproject.slack.com/archives/CPLLE0ZQX/p1582128754110800?thread_ts=1582128521.110500&cid=CPLLE0ZQX) for more background information.
- add an implementation-nonspecific, opaque `TipSetToken`, used to identify a TipSet
- add `TipSetToken` parameter to `GetSealTicket` and `GetSealedCID` and `GetMinerWorkerAddress`
- add `GetChainHead` method
- drop address parameter from `GetMinerWorkerAddress`
The go-filecoin node controls the lifecycle of the go-storage-miner `Miner` struct (which is provided a value which satisfies its "node API" interface). The node passes the `Miner` constructor the miner address X, so it is in a good position (in its connector code) …
> go-storage-miner should pass state identifiers to methods which access chain state

- cmd/go-filecoin/address.go
- cmd/go-filecoin/address_integration_test.go
- fixtures/constants.go
- internal/app/go-filecoin/node/init.go
- internal/app/go-filecoin/plumbing/api.go
- internal/pkg/consensus/election_test.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/consensus/testing.go
- internal/pkg/crypto/crypto.go
- internal/pkg/crypto/crypto_test.go
- internal/pkg/crypto/keyinfo.go
- internal/pkg/crypto/keyinfo_test.go
- internal/pkg/types/helpers.go
- internal/pkg/types/testing.go
- internal/pkg/vm/testing_messages.go
- internal/pkg/wallet/backend.go
- internal/pkg/wallet/dsbackend.go
- internal/pkg/wallet/wallet.go
- internal/pkg/wallet/wallet_test.go
- tools/fast/action_wallet.go
- tools/gengen/main.go
- tools/gengen/util/gengen.go
- tools/gengen/util/gengen_test.go
Miner workers must use BLS keys in order to produce VRFs, and the miner actor now enforces this.
Change gengen to use BLS keys. This unfortunately causes them to be non-deterministic due to an unfriendly BLS interface in filecoin-ffi (see #3781)
I made the crypto interface a bit easier to use with some renames and returning KeyInfo from the crypto methods. This required moving some things to break a circular dependency.
> Use BLS for miner worker key in genesis

- go.mod
- go.sum
- internal/app/go-filecoin/internal/submodule/storage_mining_submodule.go
- internal/app/go-filecoin/porcelain/api.go
- internal/app/go-filecoin/porcelain/piecemanager.go
- internal/app/go-filecoin/storage_market_connector/provider.go
- internal/app/go-filecoin/storage_miner_connector/connector.go
- internal/pkg/piecemanager/interface.go
- internal/pkg/piecemanager/storage_miner_back_end.go
Today, the self-deal start and end epochs are set to constants - and the wrong constants, at that.
This changeset pushes the choice of self-deal start and end-epochs into go-storage-miner, who uses existing deal information to choose self-deal start and end epochs (in the event that a to-be-sealed sector contains client data) or the provided "proving delay" and "duration" values otherwise.
> plumb start and end epochs for self-deal to DealProposal

- internal/pkg/vm/internal/vmcontext/testing.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
applyMessage usage of miner address is incorrect.
remove miner address from internal messages and from applymessage parameters.
> remove miner from internal msg and apply msg logic

- internal/app/go-filecoin/internal/submodule/chain_submodule.go
- internal/app/go-filecoin/plumbing/api.go
- internal/app/go-filecoin/plumbing/cst/chain_state.go
- internal/app/go-filecoin/storage_miner_connector/connector.go
- internal/pkg/chain/sampler.go
- internal/pkg/chain/sampler_test.go
- internal/pkg/consensus/genesis.go
- internal/pkg/consensus/processor.go
- internal/pkg/consensus/testing.go
- internal/pkg/crypto/randomness.go
- internal/pkg/poster/poster.go
- internal/pkg/sampling/chain_randomness.go
- internal/pkg/sampling/chain_randomness_test.go
- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
- internal/pkg/vm/internal/vmcontext/testing.go
- tools/gengen/util/gengen.go
The new specced randomness generation routines should replace our prior chain sampling mechanisms.
Replace all uses of `sampling/SampleChainRandomness` with new randomness. Along the way changed the interface to randomness consumed by the processor to enable sharing implementation.
Note that the election ticket generation is done differently and still needs to be reconciled with this approach.
> Hook up new randomness to seals and proofs

- cmd/go-filecoin/miner_daemon_test.go
- cmd/go-filecoin/protocol_cmd_test.go
- fixtures/setup.json
- internal/app/go-filecoin/node/test/builder.go
- internal/app/go-filecoin/node/testing.go
- internal/pkg/net/validators_test.go
- internal/pkg/testhelpers/iptbtester/genesis.go
- internal/pkg/version/protocol_version_table.go
- internal/pkg/version/protocol_version_table_test.go
- internal/pkg/version/protocol_versions.go
- tools/fast/environment/environment_memory_genesis.go
- tools/gengen/util/gengen_test.go
fixes #3496
We need to spin up networks on a nightly basis for validation. We do not want these networks to communicate with each other. We also do not want to require new protocol versions on a nightly basis for each network.
This PR introduces the ability to specified a dot delimited network (e.g. "nightly.2019-10-8") in the genesis block. For the purposes of determining the protocol version, only the part before the dot "nightly" will be considered. So "nightly.2019-10-8" and "nightly.2019-10-9" will get the same protocol table (so long as the nightly protocol table hasn't changed in code).
The full name in genesis ensures nodes on different networks won't be able to sync with each other. It also ensures that nodes on different networks won't be able to communicate on the same …
> key protocol versions off network name prefix

- internal/app/go-filecoin/internal/submodule/chain_submodule.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/consensus/genesis.go
- internal/pkg/consensus/processor.go
- internal/pkg/mining/worker_test.go
- internal/pkg/testhelpers/consensus.go
- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
- internal/pkg/vm/internal/vmcontext/syscalls.go
- internal/pkg/vm/internal/vmcontext/testing.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- internal/pkg/vm/vm.go
- internal/pkg/vmsupport/syscalls.go
- internal/pkg/vmsupport/testing.go
- tools/gengen/util/generator.go
Some syscall implementations depend on chain state (to resolve addresses), the blockchain itself (consensus fault slashing) etc. Rather than expose the VM to all of these, the syscall implementations are abstracted behind an interface. This also allows the syscalls to be faked for testing (@frrist you'll need this).
The VM defines a new interface as a parameter to `NewVM` which abstracts the actual syscall implementations. The new interface has additional parameters such as the current epoch, which are implicit in the Runtime interface called by actors.
Follow-up PRs will actually implement them.
Question:
- I put this in a new `vmsupport` package so that the `vm` package as a whole doesn't need new imports. Is there anywhere better?
- Any better names than I've chosen?
> Add interface for external injection of VM syscall implementations

- internal/pkg/block/epost_info.go
- internal/pkg/block/ticket.go
- internal/pkg/chain/sampler_test.go
- internal/pkg/chain/testing.go
- internal/pkg/chainsync/fetcher/graphsync_helpers_test.go
- internal/pkg/consensus/election.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/testing.go
- internal/pkg/crypto/randomness.go
- internal/pkg/crypto/vrf.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
Moving the type here allows using it for better safety in the crypto randomness methods.
Note: we can probably move types.signer here too later.
> Move VRFPi type from block to crypto package

- internal/pkg/block/block_test.go
- internal/pkg/block/epost_info.go
- internal/pkg/consensus/expected.go
- internal/pkg/mining/worker_test.go
- internal/pkg/testhelpers/consensus.go
This is slightly less confusing.
This changes the JSON representation, but I'm not too concerned about that right now. Lotus has different names anyway.
> Rename EPoStInfo.PoStRandomness to VRFProof

- go.mod
- go.sum
Due to my oversight, the go-storage-miner Git SHA which appears in our go.mod file corresponds to the head of a (now-merged) feature branch in go-storage-miner.
This changeset updates go.mod to consume the head of the master branch in go-storage-miner (which contains the now-merged go-storage-miner SHA previously referenced in go-filecoin's go.mod).
> point to master branch of go-storage-miner

- internal/pkg/vmsupport/syscalls.go
Simple hookup of a function call through to sectorbuilder.
Note that this also wants #3834 in order to have the full functionality of handling non-full sectors, but the changes are independent.
> Hook up ComputeUnsealedSectorCID VM syscall

- internal/pkg/vm/internal/vmcontext/runtime_adapter.go
- internal/pkg/vm/internal/vmcontext/syscalls.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- internal/pkg/vmsupport/syscalls.go
- internal/pkg/vmsupport/testing.go
- tools/gengen/util/generator.go
The signature verification syscall must resolve account actor ID addresses to their signing keys. This lookup needs to be done in the state at the time of the call, which might be mid-tipset. 
Implement an account resolution method on the runtime itself, which can inspect the current state, and provide it to the syscall wrapper.
An alternative, which I first tried, is providing a state view from the outside, keyed by epoch or tipset key or something, but that cannot reference state that hasn't been committed to storage yet (which happens only at the end of tipset processing).
The tests will pass after updating specs-actors to include https://github.com/filecoin-project/specs-actors/pull/232
We'll need a different mechanism for verifying block and message signatures, probably state-view …
> Resolve signer address in VM signature verification syscall.

- internal/pkg/crypto/crypto.go
Found this bug causing all bls aggregate sigs to be invalid during integration testing.  Since that effort is uncovering other issues and this bug will block the devnet from sending bls messages I'm PRing this independently.
> Fix tricky BLS bug

- internal/app/go-filecoin/node/node_test.go
- internal/app/go-filecoin/plumbing/msg/waiter_test.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/testhelpers/core.go
- tools/gengen/util/testing.go
Testhelpers is an ugly dumping ground and causing circular dependency problems. 
I've moved one thing out of it to reduce the number of unwanted deps that come from using some of the more primitive things in the package.
> Move DefaultGenesis from testhelpers/core to gengen

- go.sum
- internal/pkg/block/tipset.go
- internal/pkg/block/tipset_key.go
- internal/pkg/block/tipset_key_test.go
- internal/pkg/block/tipset_test.go
- internal/pkg/chain/car_test.go
Get our tipset keys up to spec and ready for interop
Callers now maintain sorting convention.  I've also removed the duplicate filtering because it has low value now that callers need to be careful about what they pass in.  I have kept the constructor that errors if there are duplicates.
Closes issue #3840
> Tipset Key change

- build/main.go
- fixtures/genesis-sectors/README.md
- parameters.json
The parameters.json is no longer obtained through a git submodule, for now I think we need to copy it from https://github.com/filecoin-project/rust-fil-proofs/blob/master/filecoin-proofs/parameters.json.
The dev sector size is now 2048 bytes.
> Update parameters.json for v23, download new 2KiB params for dev

- go.sum
- internal/app/go-filecoin/internal/submodule/storage_mining_submodule.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/poster/poster.go
The poster and message handling are currently using the chain.HeaviestTipsetCh which means one or the other will not see tipset events.
Introduce a HandleNewHead method on the storage mining submodule and the poster to replace the channel listening go routine previously in poster. This method is called by `node.handleNewChainHeads`.
Closes issue #3867
> use handler method instead of channel to check PoSt

- cmd/go-filecoin/init.go
- cmd/go-filecoin/init_daemon_test.go
- cmd/go-filecoin/main.go
- functional-tests/mining_chain_test.go
- internal/app/go-filecoin/node/init.go
We currently have no way to specify proof types for sectorbuilder when importing presealed sectors. Registered proof types can be derived from sector size, but we also do not have the sector size. In functional tests, we can easily get the default miner's sectors size from genesis. Unfortunately this is rather complicated in the init command so we'll need to supply a new command option.
* Add a sector size parameter when calling `ImportPresealedSectors`.
* Add a parameter to the init command to specify sectors size.
* Use `miner.SectorSize` to import sectors in functional tests.
Closes issue #3876
> parameterize sectorsize when importing presealed sectors

- go.mod
- go.sum
- internal/app/go-filecoin/connectors/retrieval_market/client.go
- internal/app/go-filecoin/connectors/retrieval_market/client_test.go
- internal/app/go-filecoin/connectors/retrieval_market/common.go
- internal/app/go-filecoin/connectors/retrieval_market/provider.go
- internal/app/go-filecoin/connectors/retrieval_market/provider_test.go
- internal/app/go-filecoin/connectors/storage_market/client.go
- internal/app/go-filecoin/connectors/storage_market/common.go
- internal/app/go-filecoin/connectors/storage_market/provider.go
- internal/app/go-filecoin/internal/submodule/storage_protocol_submodule.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/paymentchannel/manager.go
- internal/app/go-filecoin/paymentchannel/manager_test.go
We need to provide a tipset identifier to chain-querying methods to ensure a consistent view of the chain across queries.
This PR updates go-fil-markets to use the latest and greatest, which also necessitates a few tipset token changes.
> add tipset identifier to more chain-querying methods

- internal/pkg/types/message.go
Data format up to spec.  This was preventing full block sync.  It was so small it was worth just PRing and not spinning off into an issue
Flip field order in txmeta
Closes issue #
> TxMeta Order

- internal/app/go-filecoin/node/node.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/consensus/chain_selector.go
- internal/pkg/consensus/expected.go
We currently set the weight of the genesis block to 0 rather than adding the power of the block to a genesis parent weight of 0.  Making this change gets us up to parity with lotus.  
This is somewhat speculative since this is inadequately speced (added to spec todo list) but it is arguably more sensible than what we do now (and easy to revert) so adding to master
Closes issue #
> Fix genesis weight calculation

- internal/pkg/block/block.go
- internal/pkg/block/block_test.go
- internal/pkg/chain/testing.go
- internal/pkg/chainsync/fetcher/graphsync_helpers_test.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/expected.go
- internal/pkg/mining/block_generate.go
- internal/pkg/net/validators_test.go
- internal/pkg/slashing/check.go
- internal/pkg/testhelpers/consensus.go
- tools/gengen/util/generator.go
To interop with lotus we need to sign and verify consistent block bytes.
There is some unspecced (issue forthcoming) ambiguity in how to serialize the bytes for signing and verifying.  We are adopting lotus's strategy of serializing sig field as null because it makes a bit more sense than our current strategy
- Turn sig field into pointer so that we can use the block datastructure to get this encoding automatically (could use a different structure if reviewers prefer)
- Add non-nil sig validation to syntax val to prevent users from crashing nodes
Closes issue #
> Serialize signable block data with proper dummy value for signature 

- internal/pkg/util/hasher/hasher.go
We were misaligned with spec on how to hash partial tickets.  We need to use sha instead of blake
Hasher type which is only used by challenge ticket generation moves from blake to sha
Closes issue #
> Partial tickets hashed with sha not blake

- tools/gengen/util/generator.go
This causes a panic in actors when processing sector termination
> Fix initialisation of fault info in genesis sectors

- .github/pull_request_template.md
The word "issue" between "closes" and the number stops GitHub actually closing it.
> Change PR template so that auto-closed issue will work

- internal/app/go-filecoin/node/block.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/net/blocksub/topic.go
- internal/pkg/net/blocksub/validator.go
- internal/pkg/net/blocksub/validator_test.go
Issue #3882 calls for including the included message CIDs in the block-pubsub ("blocksub") message payload. 
This hooks up the encoding and decoding of the message CID lists in the publisher, subscriber, and validator. The CID lists are not validated (since we ignore them), #3903.
Closes #3882.
> Include message CIDs in block pubsub payloads.

- internal/pkg/vm/internal/vmcontext/actor_state_handle.go
- internal/pkg/vm/internal/vmcontext/actor_state_handle_test.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
A nested call must observe state changes from prior transactions, including from outer calls in order to build on them. An outer call cannot track the state head in a variable, but must load it each time in case an inner call changed it.
This change lets us pass the test proposed in https://github.com/filecoin-project/chain-validation/pull/122
Remove in-memory tracking of actor head state CID, loading it from storage every time. Update the head on every transaction.
> Move actor state head update to end of transaction rather than end of message send.

- go.mod
- go.sum
- internal/pkg/vm/internal/vmcontext/testing.go
- internal/pkg/vm/internal/vmcontext/validation_test.go
The tipset tests still use hardcoded and out-of-date gas expectations.
> Update chain validation tests. Enable gas validation on message (but not tipset) tests.

- functional-tests/mining_sync_test.go
- internal/pkg/consensus/genesis.go
- tools/gengen/util/generator.go
Apparently undefined addresses are not supposed to be serializable, so Lotus can't parse our block header. Also filled out all the other block header fields to be explicit.
This header should pass block validation as specified, except that the spec requires >0 EPoSt candidates, which should change to accept 0 when height = 0.
Set genesis miner to the System actor address. Add explicit zero/empty values for other fields.
FYI @whyrusleeping
> Fill out genesis block header, especially setting miner to system address.

- internal/pkg/vm/internal/vmcontext/validation_test.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
Sending to self shouldn't magically create money!
Persist the debit account before loading the credit account, in case they are the same actor.
> Fix VMContext transfer to persist debit when receiver is sender.

- functional-tests/common.go
- functional-tests/mining_chain_test.go
- functional-tests/mining_sync_test.go
- functional-tests/plege_sector_test.go
We have not, up until now, tested that windowed PoSt's generated by the poster will actually be accepted by the miner-actor. The new-ish in-process test framework makes this relatively trivial.
1. Write TestBootstrapWindowedPoSt functional test as an in-process test.
2. Refactor some common functional test functions into a common.go file.
> rewrite windowed post test as in-process test (that works)

- go.mod
- go.sum
- internal/pkg/vm/internal/vmcontext/vmcontext.go
We implemented this correctly from the spec but Lotus took this latter approach. It shouldn't matter in the final state, but per-message chain validation tests inspect this state so the difference caused tests to fail.
Transferring direct to the reward actor saves a transfer per block.
Stage gas prepayments in the reward actor rather than the burnt funds actor.
> Change per-message gas transfer to go direct to reward actor rather than staging in burnt funds.

- internal/pkg/block/ticket.go
- internal/pkg/block/tipset.go
- internal/pkg/block/tipset_test.go
The ticket ordering was changed in the (not-yet-merged) https://github.com/filecoin-project/specs/pull/883/files#diff-440d67a4748619ac846e6d07011156a7
@sternhenri also changed Lotus to do this at the same time.
Order blocks by ticket digest bytes.
> Order blocks by min ticket digest, rather than ticket raw VRF proof.

- internal/app/go-filecoin/connectors/storage_market/provider.go
- internal/app/go-filecoin/node/message_propagate_test.go
- internal/app/go-filecoin/paymentchannel/manager.go
- internal/app/go-filecoin/paymentchannel/testing/fake_init_actor_util.go
- internal/app/go-filecoin/paymentchannel/testing/fake_mgr_api.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/validation.go
- internal/pkg/consensus/validation_test.go
- internal/pkg/message/outbox.go
- internal/pkg/message/outbox_test.go
- internal/pkg/mining/block_generate.go
- internal/pkg/types/atto_fil.go
- internal/pkg/vm/internal/gascost/gascost.go
Message syntax validation to match the spec. This was specifically motivated by changing the min gas cost to allow zero (allowed by the spec), which is most useful for testing and debugging.
See #3312 (which is really about using this in graphsync).
Message validation to match [the spec](https://filecoin-project.github.io/specs/#systems__filecoin_vm__message).
See also https://github.com/filecoin-project/specs/issues/906
> Spec-compliant message syntax validation.

- build/main.go
- fixtures/genesis-sectors/unsealed/.gitkeep.go
- fixtures/setup.json
- functional-tests/mining_sync_test.go
- internal/app/go-filecoin/node/init.go
- internal/pkg/consensus/election.go
- internal/pkg/consensus/testing.go
- internal/pkg/mining/worker.go
- tools/gengen/util/generator.go
- tools/gengen/util/gengen.go
- tools/gengen/util/testing.go
Almost all non-interop testing for go-filecoin to date has been using the development 2KiB sector size for proofs. This branch reflects bug fixes required to get 512MiB sector election and windowed PoSt generation and verification to work in a one-off test (which is not included in this PR for size and test performance reasons).
see inline comments.
> bug fix 512 mib sectors

- fixtures/setup.json
- internal/pkg/consensus/expected.go
- tools/gengen/util/generator.go
The prealloc values in setup.json are tiny when evaluated as attofil, very hard to use with non-zero gas prices.
Give the reward actor a representative balance, and pre-alloc accounts 1mm FIL each.
> Fix genesis reward actor initial balance, interpret prealloc values as whole FIL

- cmd/go-filecoin/show.go
- cmd/go-filecoin/show_test.go
- internal/app/go-filecoin/plumbing/api.go
- internal/app/go-filecoin/plumbing/cst/chain_state.go
- internal/app/go-filecoin/porcelain/chain.go
- internal/pkg/block/full_block.go
During debug it has become increasingly obvious that our inability to inspect bls messages in blocks without going through dag get and reading amt data makes operation of a node inefficient enough that was worth taking the time now to do this.
Quick non-pretty adding of BLS messages to show block and show messages commands.  No json encoding, nothing fancy just extending our existing approach the bare minimum so that I can inspect bls messages from the cli.
Closes #
> Add BLS to cli message output

- internal/app/go-filecoin/connectors/storage_miner/connector.go
- internal/app/go-filecoin/internal/submodule/chain_submodule.go
- internal/app/go-filecoin/internal/submodule/storage_mining_submodule.go
- internal/app/go-filecoin/node/node.go
- internal/pkg/chain/store.go
- internal/pkg/chainsampler/height_threshold_listener.go
- internal/pkg/chainsampler/height_threshold_listener_test.go
- internal/pkg/chainsampler/height_threshold_scheduler.go
Fewer channels = fewer problems. All the asynchrony here was unnecessary. This fixes a few bugs.
- the context being passed to Start() was not long-running, so the scheduler's goroutine exited immediately
- after the goroutine exited, the module HandleNewHead blocked on the unbuffered heaviestTipSet channel
- the argument to HandleNewTipSet was named and treated as the previous head, rather than new head; the chain store was inspected for head which might race with other writes to it
- CancelListener iterated over an empty slice and always forgot all listeners
I have no idea how things worked at all here.
This will probably fix issue #3959, but I'll wait to close it until we observe better behaviour in devnets.
Remove all the channel control flow from HeightThresholdScheduler along with …
> Remove channels and goroutine from HeightThresholdScheduler and storage mining module.

- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
Except for not-found, failure is probably not reproducible across impls.
Inspect error for ErrAddrNotFound before returning false. Otherwise panic.
> Halt execution if address resolution fails for a reason other than not-found

- internal/app/go-filecoin/node/test/setup.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/message/outbox.go
- internal/pkg/state/view.go
The miner create is the first real step towards creating functioning non-bootstrap miner. Unfortunately, it hasn't been working since the move to specs actors.
This PR resolves it's issues and adds an integration test. In the process, it introduces some new test infrastructure, `MustCreateNodesWithBootstrap`, that makes it simple to create a new in-process integration test that allows a node to send messages and receive mined blocks containing their receipts.
The bug fixes are:
1. The test needs to send sufficient gas.
2. CreateMiner is an operation on the power actor, but we were sending the message to the market actor.
3. The CreateMiner return type is now a struct containing the miner id address and the robust address instead of a single address.
I wanted to test that the miner's state …
> restore miner create

- cmd/go-filecoin/client.go
- cmd/go-filecoin/daemon.go
- cmd/go-filecoin/miner.go
- cmd/go-filecoin/miner_integration_test.go
- internal/app/go-filecoin/porcelain/api.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/protocol/storage/api.go
We're trying to build the UI back up to a working storage and retrieval flow.  This PR restores the set-price and list-asks command using the corresponding go-fil-storagemarket operations.
1. Add storage provider API to storageAPI for commands.
2. Implement `set-price` and `list-asks' commands, modifying parameters to fit the expectations of the storage provider methods (asks no longer go on chain and don't need, say, a gas price).
3. Move miner integration test from porcelain to commands.
4. Add a miner set-price integration test.
> set-price and list-asks commands

- cmd/go-filecoin/client.go
- cmd/go-filecoin/client_integration_test.go
- cmd/go-filecoin/daemon.go
- cmd/go-filecoin/main.go
- cmd/go-filecoin/main_test.go
- cmd/go-filecoin/miner_integration_test.go
- go.mod
- go.sum
- internal/app/go-filecoin/connectors/storage_market/client.go
- internal/app/go-filecoin/connectors/storage_market/common.go
- internal/app/go-filecoin/connectors/storage_market/provider.go
- internal/app/go-filecoin/internal/submodule/storage_protocol_submodule.go
- internal/app/go-filecoin/node/builder.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/node/test/setup.go
- internal/pkg/protocol/storage/api.go
- internal/pkg/state/view.go
Although the storage market has been integrated into go-filecoin, it has not been fully tested because the CLI commands have never been connected and the necessary chain interactions have only recently been completed. This PR restores the `client propose-deal` and `client query` commands and fixes multiple minor issues with the integration so that storage miners and storage clients can now make deals.
1. Restore the `client propose-deal` and `client query` commands.
2. Introduce a new integration test to test this functionality. This is an in-process test that tests a deal proposal from first contact, through multiple actor interactions up to the point where the client sees the miner has accepted the deal. This test actually works through staging and sealing until the deal is active, but …
> client propose-deal

- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/app/go-filecoin/porcelain/api.go
- internal/pkg/chainsync/internal/syncer/syncer_integration_test.go
- internal/pkg/consensus/chain_selector.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/consensus/power_table_view.go
- internal/pkg/consensus/power_table_view_test.go
- internal/pkg/consensus/testing.go
- internal/pkg/consensus/weight_test.go
- internal/pkg/mining/worker.go
- internal/pkg/poster/poster.go
- internal/pkg/state/testing.go
- internal/pkg/state/view.go
- internal/pkg/testhelpers/mining.go
- internal/pkg/types/testing.go
Power calculations need to handle the case where consensus faults have slashed a miner in between the current head and power table lookback.
Power table now takes in two different state view and checks that a miner exists in the new `faultsState` before returning the power claim in the power state.  
Closes #3976
> Power Table handles consensus faults

- internal/pkg/block/block.go
- internal/pkg/block/block_test.go
- internal/pkg/block/epost_info.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/election.go
- internal/pkg/consensus/expected.go
- internal/pkg/crypto/vrf.go
- internal/pkg/drand/drand.go
- internal/pkg/drand/drand_grpc.go
- internal/pkg/drand/testing.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/testhelpers/consensus.go
- tools/gengen/util/generator.go
The first commit simply removes the (now unused) ElectionPoSt field.
The second commit does the following:
- Puts the `ElectionProof` bytes in a struct (this is what Lotus does, and is preferred for future changes)
- Simplifies the signature field in Drand entries to just be a byte array (since I believe Drand is using a different version of BLS than "everything else", and so it isn't meaningfully associated with type BLS anyway).
With this, Lotus and go-filecoin agree on the serialisation of the new block headers.
> Make the block structure compatible with Lotus

- internal/pkg/drand/drand_grpc.go
Found a tiny bug where drand doesn't write back new values to the config 
Closes #
> Write new drand vals to config

- fixtures/setup.json
- internal/app/go-filecoin/node/block_propagate_test.go
- internal/app/go-filecoin/node/message_propagate_test.go
- internal/pkg/consensus/power_table_view_test.go
- tools/gengen/util/generator.go
- tools/gengen/util/gengen.go
- tools/gengen/util/gengen_test.go
- tools/gengen/util/testing.go
My goal here was to set up quality-adjusted power (which depends on verified deals) properly gengen. I discovered so much wrong with how genesis state was being constructed that it resulted in rather a large change. I don't think this is yet capable of producing a mainnet-ready genesis state.
Related to #4011
- Install verified deal registry built-in actor
- Include verified deal flag in deal configs
- Compute QA and raw byte power
- Accumulate network total power so pledge amounts can be calculated properly
- Transfer the right pledge value from miner owner to actor (pending updated pledge calculations in actors)
- Fix up invalid genesis configs that didn't pre-allocate any/sufficient value to the miner owner to cover initial pledge
> Update gengen with quality-adjusted power and verified deals actor

- internal/pkg/consensus/election.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/power_table_view.go
- internal/pkg/consensus/testing.go
- internal/pkg/mining/worker.go
Miner power is no longer a simple function of sector size and count. See #4011.
Reads the power from the power table directly. This would be an improvement even if the underlying computation wasn't becoming more complicated.
This is a peer of #4027 and will have a small conflict in the naming of power table functions.
> Use power table miner power rather than computing from sector size and count

- cmd/go-filecoin/mining_integration_test.go
- functional-tests/mining_sync_test.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/consensus/chain_selector.go
- internal/pkg/consensus/election.go
- internal/pkg/consensus/expected.go
- internal/pkg/consensus/power_table_view.go
- internal/pkg/consensus/power_table_view_test.go
- internal/pkg/consensus/testing.go
- internal/pkg/consensus/weight_test.go
- internal/pkg/mining/worker.go
- internal/pkg/state/testing.go
- internal/pkg/state/view.go
- internal/pkg/testhelpers/mining.go
- tools/fast/action_miner_test.go
- tools/gengen/main.go
- tools/gengen/util/generator.go
- tools/gengen/util/gengen.go
There are now two notions of power, raw and quality adjusted.
This plumbs the distinction through most of the code and uses QA power for the election power table.
This is most, but not all, of #4011.
> Plumb QA power through the power table

- internal/pkg/consensus/election_test.go
- internal/pkg/consensus/power_table_view_test.go
- internal/pkg/crypto/crypto.go
- internal/pkg/mining/worker_test.go
- internal/pkg/types/testing.go
- internal/pkg/wallet/dsbackend.go
- tools/gengen/util/generator.go
- tools/gengen/util/gengen_test.go
Determinism by default, for stability of testing. Randomness optional, most specifically for the wallet backend.
Closes #3781
> Deterministic BLS key generation

- internal/pkg/block/block.go
- internal/pkg/block/block_test.go
- internal/pkg/mining/block_generate.go
lotus special cases election proof serialization as null in the genesis block and this matches their serialization.
If we don't do this we get different data when deserializing and serializing lotus genesis blocks with their current protocol implementation
Closes #
> Make election proof a pointer to match lotus

- cmd/go-filecoin/client_integration_test.go
- cmd/go-filecoin/miner.go
- cmd/go-filecoin/miner_integration_test.go
- internal/app/go-filecoin/connectors/fsm_node/connector.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/porcelain/api.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/state/testing.go
- internal/pkg/state/view.go
As far as possible, code should not depend directly on the on-chain state structures. Such deps will be massively painful if the structure changes in a protocol migration. The state view exists specifically to abstract such details.
This doesn't solve the whole problem, see #4025 for the rest.
Replace some uses of the MinerStatus (which embeds a miner.Info state object) with existing state view methods.
FYI @ZenGround0 so you're also aware and can maintain this boundary.
> Remove some unnecessary coupling to miner info chain state structures.

- internal/pkg/vm/internal/vmcontext/invocation_context.go
- internal/pkg/vm/internal/vmcontext/validation_test.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
The actor state references held by `invocationContext` were outdated after calls to transfer. This prevented reward funds from being distributed to miners by the reward actor.
> fix: update invoke actor state after transfer

- cmd/go-filecoin/client.go
- cmd/go-filecoin/miner.go
- cmd/go-filecoin/miner_daemon_test.go
- fixtures/setup.json
- functional-tests/plege_sector_test.go
- go.mod
- go.sum
- internal/app/go-filecoin/connectors/fsm_node/connector.go
- internal/app/go-filecoin/internal/submodule/storage_mining_submodule.go
- internal/app/go-filecoin/node/init.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/node/test/setup.go
- internal/app/go-filecoin/node/testing.go
- internal/app/go-filecoin/porcelain/api.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
- internal/pkg/consensus/power_table_view.go
- internal/pkg/consensus/power_table_view_test.go
- internal/pkg/constants/sector_size.go
- internal/pkg/state/testing.go
- internal/pkg/state/view.go
- internal/pkg/testhelpers/iptbtester/genesis.go
- internal/pkg/vm/internal/vmcontext/vmcontext.go
- tools/fast/environment/environment_memory_genesis.go
- tools/gengen/util/generator.go
- tools/gengen/util/gengen.go
- tools/gengen/util/gengen_test.go
This is fairly painless. Tests won't pass until https://github.com/filecoin-project/chain-validation/pull/179 lands and this PR also consumes the appropriate chain validation tests.
It would be beneficial to also consume compatible upstream repos at the same time, though in this case I think the changes are small enough that it's also safe not to.
> Upgrade to specs-actors v0.3.0

- go.mod
- internal/app/go-filecoin/connectors/retrieval_market/client.go
- internal/app/go-filecoin/connectors/retrieval_market/client_test.go
- internal/app/go-filecoin/connectors/retrieval_market/common.go
- internal/app/go-filecoin/connectors/retrieval_market/fake_api.go
- internal/app/go-filecoin/connectors/retrieval_market/provider_test.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/paymentchannel/integration_test.go
- internal/app/go-filecoin/paymentchannel/manager.go
- internal/app/go-filecoin/paymentchannel/manager_test.go
- internal/app/go-filecoin/paymentchannel/testing/fake_init_actor_util.go
- internal/app/go-filecoin/paymentchannel/testing/fake_mgr_api.go
- internal/app/go-filecoin/paymentchannel/testing/fake_paych_actor_util.go
The latest go-fil-markets utilizes non-blocking creation of payment channels and adds two wait functions for creating a new payment channel and adding funds.
Closes #3988 
Alters GetOrCreatePaymentChannel to meet new functionality requirements
Implements new Wait* API functions
Adds thread-safety to payment channel store
Updates integration test to include adding funds and uses wait functions
Please see #4045 , #4046 , and there is an upcoming proposal to decide how to address message wait vs. get state for the new go-fil-markets retrieval api.
> Feat/retrieval market #3988

- internal/pkg/chain/testing.go
- internal/pkg/mining/block_generate.go
- tools/gengen/util/generator.go
Lotus cannot deserialise blocks with nil arrays, so we're effectively elevating this to a spec requirement in order to achieve interop.
With this change, Lotus is able to import blocks generated by gengen. 
Outside of tests, only create blocks with empty arrays for `BeaconEntries` and `PoStProofs`.
Closes #
> Prevent arrays in blocks from being nil

- internal/app/go-filecoin/plumbing/cst/chain_state.go
- internal/pkg/chain/sampler.go
- internal/pkg/chain/sampler_test.go
- internal/pkg/consensus/election.go
- internal/pkg/consensus/testing.go
Randomness is underspecced and ambiguous
Through agreement with lotus gfc is moving to lotus's current strategy of taking undigested ticket bytes as input to the randomness mixer.  Tests against latest lotus interopnet confirm this passes validation.
Slight refactor to sample ticket rather than mixed ticket.  Turned out to be pretty simple because of the previous change giving the ticket machine direct access to chain sampler.
Closes #
> rand bytes should match

- internal/pkg/drand/drand_grpc.go
If you call `drand configure` on a daemon and do not restart it the first filecoin round property of the in memory drand grpc construct does not get properly reset so the first filecoin round value gets set to a very high number which makes mining fail. 
To fix this we do the calculation along with other resets after fetching the config.  We take advantage of this PR to abstract that ffr calculation and setting to a subfunction of drand grpc.
Closes #
> update ffr after live config

- tools/gengen/util/generator.go
Small change that shouldn't affect much.  This way gengen puts something in the drand entries field to keep lotus happy during interop.  Gfc won't ever read this value because it special cases genesis when handling drand.
Closes #
> Add dummy drand entry to genesis block in gengen

- cmd/go-filecoin/client.go
- cmd/go-filecoin/client_integration_test.go
- internal/app/go-filecoin/connectors/storage_market/client.go
Our client propose-storage-deal command errors with an unhelpful message when the peer id option is not provided.
Fix this and restore the propose-storage-deal integration test (which appears to be working fine).
> Error in propose-storage-deal when peer id option is not provided

- internal/pkg/vm/internal/storage/storage.go
- internal/pkg/vm/internal/vmcontext/actor_store.go
- internal/pkg/vm/internal/vmcontext/actor_store_test.go
- internal/pkg/vm/internal/vmcontext/invocation_context.go
Technically, serialization is part of the actor code and the VM puts/gets bytes. Our runtime API is at a slightly higher level of abstraction for convenience, but serialization failures, which actor's can definitely cause, should not halt execution. E.g. when we have user contracts, serialization will live in that contract code.
See a similar change in Lotus: https://github.com/filecoin-project/lotus/pull/1627
Wrap and identify errors from the encode/decode call, then abort rather than panic in that case.
FYI @arajasek @magik6k
> Abort with ErrSerialization when storage de/serialization fails.

- go.mod
- go.sum
proof parameters are no longer pinned to IPFS public gateways, but on collab IPFS Cluster instead
change default gateway url to proofs.filecoin.io
> fetch groth parameters from proofs.filecoin.io

- functional-tests/common.go
- functional-tests/plege_sector_test.go
The pledge sector functional test had been skipped because a bug in specs-actors code kept it from passing. That problem has been resolved in new specs-actor code so this PR un-skips the test.
The changed that fixed the actor issue, created a new problem with pledge collateral, so this PR also give the miner some collateral before starting the test.
Restore `TestMiningPledgeSector`
> give miner collateral in pledge sector test

- functional-tests/common.go
- functional-tests/drand_test.go
- functional-tests/faucet_test.go
- functional-tests/mining_chain_test.go
- functional-tests/plege_sector_test.go
- internal/app/go-filecoin/node/block_propagate_test.go
- tools/faucet/main.go
I decided to bring back some tests. I chose this one because it's the last thing pinning `testhelpers/iptbtester`, which we can delete after this PR in favour of in-process or daemon tests.
Rewrite faucet test as in-process.
> Restore faucet test as an in-process integration test

- cmd/go-filecoin/init.go
- cmd/go-filecoin/main.go
- internal/app/go-filecoin/node/builder.go
This option removes operator complexity into the code.  There is now an init option that initializes the config.
`go-filecoin init --drand-config-addr=<drand addr>` will populate the config with a drand network's info.
We reuse the drand api's configure method.  Along the way we extract a small set of default drand setup calls into a free function in builder.  We also do a little bit of type massage to handle the drand api's dependence on plumbing.  We give fewer options to the user configuring on init.  In particular we only let users specify one address and force the `drand configure` defaults for transport layer security (we require it) and fetched address overwriting (we do not do it).  If users want more options they can hold off and configure drand with the fully expressive daemon …
> drand-config-addr init option

- internal/pkg/config/config.go
- internal/pkg/config/config_test.go
- internal/pkg/repo/fsrepo_test.go
Logs spam error `message pool is full` regularly because our default is below what typically occurs on a devnet.
Increase the limit
Closes #
> Max mpool count *= 100

- internal/pkg/drand/drand.go
- internal/pkg/drand/drand_grpc.go
- internal/pkg/drand/testing.go
- internal/pkg/mining/scheduler.go
- internal/pkg/mining/worker.go
We observed panics from concurrent map access coming from `GRPC.updateLocalState`, which writes to a cache. These are ultimately caused by the mining worker invoking `Mine` concurrently, but exacerbated by the context being ignored by the drand client library and our wrapper.
Skip updating local state if the context has been cancelled.
This is a work-around, but not complete fix, for #4065
> Work around re-entrancy and cancellation ignorance in drand fetch

- cmd/go-filecoin/daemon.go
- internal/pkg/config/config.go
- internal/pkg/config/config_test.go
- internal/pkg/config/testing.go
- internal/pkg/repo/fsrepo_test.go
The network parameters defined in specs-actors are not currently configurable. In lieu of some real configurability, this allows a node to override the parameters for test networks.
Note that this mechanism won't work to affect genesis state construction.
New config for overriding ConsensusMinerMinPower
> Config support for monkey-patching constants in specs-actors at daemon boot

- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher_test.go
- internal/pkg/chainsync/fetcher/graphsync_helpers_test.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/testing.go
- internal/pkg/consensus/validation.go
- internal/pkg/consensus/validation_test.go
- internal/pkg/message/outbox.go
- internal/pkg/message/pool.go
- internal/pkg/message/testing.go
- internal/pkg/net/msgsub/validator.go
- internal/pkg/testhelpers/core.go
We need to reject blocks that have messages with invalid syntax.  cc @arajasek 
Add message syntax validation during graphsync fetching and propagate changes.
Closes #3312
> Add msg syntax validation during sync

- internal/pkg/types/message.go
Lotus sends some messages with this gas limit, and we're not confident that 10m is high enough to not cause problems until we work out what a good value is.
This is only used as a message syntax validation check. Neither go-filecoin nor Lotus actually enforce a block-level gas limit.
Set BlockGasLimit to 100 million.
> Set gas limit to 100mm

- cmd/go-filecoin/init.go
- cmd/go-filecoin/main.go
- internal/pkg/message/pool_test.go
- internal/pkg/testhelpers/test_daemon.go
Some changes in the way we initialize the node broke the `default-address` init option. The address would still be set in config, but it would be immediately overridden by the address of a new key generated by the node. There are really a few problems:
1. `default-address` is ignored.
2. A new key pair is generated whether or not key files are imported.
3. The new key pair address is always the default address.
I started down the path of fixing `default-address` by tying it to an imported key pair and ensuring it gets set in config, but `default-address` has a few problems:
1. It makes no sense to set a default address that isn't tied to an imported key.
2. It's not easy to determine the default address from a key file prior to node initialization.
3. Addresses, especially BLS addresses, …
> derive default address from first imported key

- tools/gengen/util/generator.go
These entries are now importable, so use the shared ones.
> Init cron actor table from specs-actors

- fixtures/networks/testnet.go
This is unfortunate but needed.  Bootstrap logic is so borked that having non-zero min peer hangs the node for ever.  Actual fix on its way but not going to make it for launch.  We are handling this by instructing users to connect directly to bootstrap peers.
need to merge now but fyi @anorth 
Closes #
> No bootstrap connections in default config

- README.md
- Updates the stuff after the `init` command
- Adds back the manual bootstrapping steps I removed in #4120, including more details and moving it to the correct section (thx @ZenGround0)
Please review lines 140-169 very carefully, including punctuation.
> Add Testnet connection steps to README

- cmd/go-filecoin/init.go
- fixtures/networks/interop.go
- fixtures/networks/testnet.go
- functional-tests/network-deployment/relay_check_test.go
- internal/pkg/drand/drand_grpc.go
The `init` command was writing null `drand.distKey` causing an index out of bounds panic when verifying a drand entry.
Re-work network parameters to avoid being static at all so I don't have to think about it.
> Work around go static initialization confusion for network configs

- cmd/go-filecoin/client.go
The propose-deal command had been passing in a test registered proof type. This proof only specified the proof version (StackedDRG) so the piece commitment could be calculated correctly. This looks wrong, and it would be wrong once the network supports different proof versions.
Use the miner's registered proof type for piece commitment calculation, which ensures they will be in sync.
Closes #4127
> make inaccurate prooftype look less wrong

- functional-tests/common.go
- functional-tests/plege_sector_test.go
- internal/app/go-filecoin/internal/submodule/storage_mining_submodule.go
The storage FSM uses an ID derived from the miner's address to locate sectors. This fails if the miner id is not an ID address (i.e. when it's the robust address returned from the miner create command). We need to convert this address before passing it to the fsm.
1. Resolve miner address before passing it on to storage FSM.
2. Modify pledge-sector test so that it creates a miner and sets robust address in config to replicate failure prior to change.
Closes #4126
> resolve miner id addres before passing to storage fsm

- go.mod
- go.sum
- internal/app/go-filecoin/connectors/storage_market/client.go
- internal/app/go-filecoin/connectors/storage_market/common.go
- internal/app/go-filecoin/connectors/storage_market/provider.go
- internal/app/go-filecoin/internal/submodule/storage_protocol_submodule.go
Update to latest go-fil-markets and make sure we have no issues arising from having a single host
- Update fil-markets to v0.2.5
- Use facilities in v0.2.5 to share a data-transfer instance between mining and client (I suspect this would have caused making deals as a client from a node running as a miner to break -- not sure that anyone has run this)
- Add some nice event logging for what's going on with deals (storage module has a subscribable interface for getting events on deals -- this could be hooked into an actual command line or HTTP api but here it's just used to make some nice logs)
- Remove an expired TODO (this was addressed a long time ago)
Closes #
> Update go-fil-markets & solve single host data transfer issues

- cmd/go-filecoin/client.go
- cmd/go-filecoin/deals.go
- cmd/go-filecoin/deals_daemon_test.go
- cmd/go-filecoin/deals_integration_test.go
- internal/pkg/protocol/storage/api.go
Flesh out deals command line
- Implement two new commands, write integration test for deals list
- add methods to StorageAPI to get Client & Miner deals
- haven't implemented verify-deal integration test cause at the moment, we have no way to get deal to completion
Closes #
> Implement deals list & client verify-deal

- cmd/go-filecoin/daemon.go
- cmd/go-filecoin/main.go
- functional-tests/drand_test.go
- functional-tests/faucet_test.go
- functional-tests/mining_chain_test.go
- functional-tests/plege_sector_test.go
- go.mod
- go.sum
- internal/app/go-filecoin/node/block_propagate_test.go
- internal/app/go-filecoin/node/builder.go
- internal/app/go-filecoin/node/node_test.go
- internal/app/go-filecoin/node/test/setup.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher_test.go
- internal/pkg/clock/chainclock.go
- internal/pkg/clock/chainclock_test.go
- internal/pkg/clock/testing.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/consensus/expected_test.go
- internal/pkg/mining/scheduler.go
- internal/pkg/mining/scheduler_test.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/net/blocksub/validator_test.go
Our scheduling for block mining is a bit off. Miners are allowed to send blocks as soon as the epoch begins, which means they should mine the block in the previous epoch. Since mining requires parent blocks to arrive from other miners, we need a configurable propagation delay to trade off between waiting long enough for all the blocks to arrive and providing sufficient time to mine the block
We also had a problem where mining in the scheduler was run in a go routine. This would allow overlapping attempts to mine when the timing is off. This potentially causes a panic.
1. Schedule mining synchronously.
2. Add propagation delay parameter alongside related block delay parameter
3. Give chain clock ability to wait for epoch + propagation delay
4. Modify scheduler to wait for propagation …
> mine block before epoch

- cmd/go-filecoin/message.go
- cmd/go-filecoin/message_integration_test.go
- internal/app/go-filecoin/node/test/setup.go
- internal/app/go-filecoin/plumbing/api.go
- internal/app/go-filecoin/porcelain/message.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/app/go-filecoin/porcelain/miner_test.go
We have changed the behavior of message wait so that it will, by default, only look back a couple of tipsets for messages that have landed on chain. This makes it a lot safer, but it means that we no longer have anyway to search for messages that we know have landed on chain more than a couple tipsets back. This PR adds a `lookback` parameter to the message wait command so users can search for messages before waiting. We may want a variant that searches and does not wait, but this parameter is useful nonetheless.
This parameter needed to be tested, but our message wait integration tests were skipped. This PR also does some infrastructure work to get those tests working with new testing patterns and unskips the tests.
1. Introduce new `lookback` parameter to `message wait` command.
2. …
> add lookback parameter to message wait command

- functional-tests/common.go
- internal/app/go-filecoin/internal/submodule/block_mining_submodule.go
- internal/app/go-filecoin/node/block.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/node/test/setup.go
- internal/pkg/mining/block_generate.go
- internal/pkg/mining/scheduler.go
- internal/pkg/mining/scheduler_test.go
- internal/pkg/mining/testing.go
- internal/pkg/mining/worker.go
- internal/pkg/mining/worker_test.go
- internal/pkg/protocol/mining/mining_api.go
Block mining used to occur within nested goroutines. This was causing problems, so it has been simplified to run synchronously. This makes the channel communication it used to use to communicate errors and output unnecessary. This PR removes that channel and replaces it with simple return statements.
1. Remove channel argument from worker Generate function and return block header, messsages and error directly.
2. Move `Output` struct to scheduler (which still needs to communicate via channel) and rename to `FullBlock`.
3. Remove channel argument from `worker.MIne` and return header, messages and errors instead.
4. Have scheduler log its own errors and signal its shutdown by closing its output channel (which will trigger a shutdown of mining).
5. __Important__: The scheduler no longer …
> remove channel from worker mine

- internal/app/go-filecoin/connectors/fsm_node/connector.go
- internal/app/go-filecoin/internal/submodule/storage_mining_submodule.go
A miner address may be a stable actor address or an ID address. When deriving seal randomness, the entropy must be derived from an ID address, so we should resolve the ID address before passing it into the connector.
The first pass at this would resolve the address just prior to use. This is more correct, because it accounts for the possibility that the ID address changes between the time the connector is constructed and the time the address is used due to a re-org. Unfortunately, this won't work because it would cause the miner address to go out of sync with the storage-fsm. I looked into fixing the storage fsm, but it would touch almost the entire interface between it and the node connector. 
For now I'll leave this simpler solution and miners will need to wait some period of time …
> resolve miner address before using it to derive seal randomness

- internal/app/go-filecoin/internal/submodule/syncer_submodule.go
- internal/pkg/chain/testing.go
- internal/pkg/chainsync/chainsync.go
- internal/pkg/chainsync/fetcher/graphsync_fetcher_test.go
- internal/pkg/chainsync/internal/syncer/syncer.go
- internal/pkg/chainsync/internal/syncer/syncer_test.go
- internal/pkg/consensus/block_validation.go
- internal/pkg/consensus/block_validation_test.go
- internal/pkg/net/blocksub/validator_test.go
- internal/pkg/testhelpers/consensus.go
We need to check call sequence numbers and a few other things on incoming blocks before we declare the tipset ready for processing. This falls under the category of semantic validation so add a new `ValidateMessagesSemantic` function to be run on each block after messages have been fetched for the tipset. 
partially addresses #934
> add block message validation to semantic validation

- cmd/go-filecoin/client.go
- internal/app/go-filecoin/node/node.go
- internal/app/go-filecoin/porcelain/miner.go
- internal/pkg/state/testing.go
The `miner status` currently fails with a serialization error. The cause is some big.Int values were nil, and that breaks the serialization between the daemon and the client. 
This command had become a dumping ground of miner information with redundancies and no real organization. This PR simplifies the lookups required and the result. It fixes the serialization error simply by deleting the offending fields.
> simplify miner status so that command serializes

- cmd/go-filecoin/deals.go
- cmd/go-filecoin/deals_integration_test.go
If you have no active deals and call `deals list`, the response is JSON `null`. This looks like a bug and will require special-casing in languages other than Go.
Emit an empty list (`[]`) instead of `null`.
> return empty list when no deals are present

- internal/pkg/net/network.go
This is another command that outputs null when it should be returning an empty list.
> return empty list in peers result when no peers present

- go.mod
- go.sum
- internal/pkg/enccid/enc_cid.go
- internal/pkg/enccid/enccid_test.go
- internal/pkg/encoding/fxamacker_cbor.go
- internal/pkg/vm/actor/actor.go
Fxamacker cbor library has been upgraded to v2 for a while now.  It seems like a good time to bring in latest version.  There were two very small breaking interface changes.
Update go mod.  Fix a few small interface changes.
Note: I tested this out against syncing latest lotus interopnet.  Haven't tested out when mining with lotus -- we should feel free to postpone merge until post mainnet to be on the extra safe side to make sure we don't introduce further incompatibilities that only show up when we produce blocks.
Closes #
> update fxamacker cbor to v2

- cmd/go-filecoin/address.go
- cmd/go-filecoin/address_integration_test.go
- internal/app/go-filecoin/porcelain/wallet.go
The address and wallet tests had been skipped while some changes in the commands took place. Restore the tests that make sense and delete the ones that don't.
> restore address and wallet command tests

- go.mod
- go.sum
- internal/app/go-filecoin/internal/submodule/retrieval_protocol_submodule.go
- internal/app/go-filecoin/internal/submodule/storage_protocol_submodule.go
Upgrade to latest go-fil-markets
Upgrade to latest go-fil-markets and make any needed changes to get it working.
Changes include:
- We've now moved prefixing datastores largely out of the markets modules, to allow node implementations to customize how they want to prefix their datastores - the module constructors have been updated minimally to stay compatible with the previous release (any greater customization such as setting up in the config file is left to node maintainers)
- The stored ask is now constructed seperately from the storage provider. We've update to constructors with a minimal implementation here, though node maintainers want to interact directly with the ask it's an option
- Per https://github.com/filecoin-project/go-fil-markets/blob/master/storagemarket/impl/provider.go#L …
> Use latest go-fil-markets

- README.md
As written, running the curl command just prints to stdout.
Make it easier for most people to install on MacOS
Pipe the script to bash directly instead of just printing it to stdout.
> Pipe mac-build.sh to bash

- cmd/go-filecoin/init.go
- cmd/go-filecoin/main.go
The `with-miner` flag has been rendered redundant by `MinerActorAddress` and needs to be removed/deprecated 
Remove the `WithMiner` option corresponding to the `with-miner` flag and all references to it from `cmd/go-filecoin/init.go`
Closes #4002
> Removing redundant `with-miner` flag

- app/node/node.go
- app/submodule/discovery/discovery_submodule.go
- app/submodule/network/network_submodule.go
- pkg/discovery/bootstrap.go
- pkg/discovery/bootstrap_test.go
fix `syncerAPI.SyncSubmitBlock` panic in `offline` mode
and make it have the same behavior as running `lotus daemon` with the flag `bootstrap=true`
> fix `syncerAPI.SyncSubmitBlock` causes `venus` panic in `offline` mode

- app/submodule/chain/actor_api.go
- cmd/mpool.go
> add cmd for message select

- app/node/builder.go
- main.go
2 upgade loging package which was impoted in 'main.go' to v2.
avoid syntax error, which was warned by idea.(actually can compile
succesfully)
Closes #
> 1. set rate-limit default log level

- go.mod
- go.sum
sub-uri of 'pprof' is forbidden.
change the logical of 'TrustHandle' to following description:
if 'pattern' with '/' as suffix, 'TrustHandler' treat it as a root path,
that it's all sub-path would be trusted.
if 'pattern' without '/' suffix,
only the URI exactly matches the 'pattern' would be treat as trusted.
Closes #
> update venus-auth go mod for 'trustedhandle'

- documentation/venus-market module design & roadmap.md
As the rebranding of filecoin terminology spearheaded by [FIP0018](https://github.com/filecoin-project/FIPs/blob/master/_fips/fip-0018.md) settled, consensus has been reached across communities (developers, providers, ecosystem partners and etc) to push for taking on more storage deals to improve the public perception on the fact that most of the network storages are still commited capacities (CCs). Given the above sentiment, design and implemenation of venus-market module has been put into the spot light. A clear long-term roadmap is due for Venus community to dissus and iterate on, also as a means for better communications with filecoin eocsystem in general.
> Create venus-market module design & roadmap.md

- pkg/consensusfault/check.go
> fix consensus height check

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> Issue: update issue template

- cmd/chain.go
- cmd/show.go
> Move commands from the show subcommand to the chain subcommand

- pkg/testhelpers/test_daemon.go
The IPFS_REUSEPORT environment variable has been deprecated for LIBP2P_TCP_REUSEPORT since 2018 and has finally been dropped in the latest go-tcp-transport https://github.com/libp2p/go-tcp-transport/pull/104.
Switch the environment variable
Closes #
> switch from IPFS_REUSEPORT to LIBP2P_TCP_REUSEPORT

- cmd/state.go
- pkg/chain/waiter.go
- pkg/wallet/dsbackend.go
> fix message wait

- pkg/vm/gas/gas_tracker.go
#4610 
add EnableGasTracing  env var
Closes #
> use env var to enable gas tracing

- .github/workflows/tag-workflow.yml
auto choose ftp/oss/artifacts for uploading targets.
oss secrets configurations:
- Secrets.OSS_ENDPOINT
- Secrets.OSS_BUCKET
- Secrets.OSS_KEY_SECRET,  
- Secrets.OSS_KEY_ID
ftp secrets configurations:
- Secrets.FTP_HOST
- Secrets.FTP_USER
- Secrets.FTP_PWD
the action would try upload targets to oss first. if failed, upload to artifacts.
> auto choose upload compiling output to ftp first

- .github/workflows/tag-workflow.yml
commit message with strange char causes workflow failed
> fix: commit message with strange char causes workflow failed

- pkg/consensus/processor.go
- pkg/gen/genesis/genesis.go
- pkg/gen/genesis/miners.go
- pkg/statemanger/call.go
- pkg/vm/vm.go
- pkg/vm/vmcontext/syscallsStateView.go
- pkg/vm/vmcontext/vmcontext.go
- tools/conformance/driver.go
- tools/gengen/util/generator.go
> VM: Circ supply should be constant per epoch

- pkg/messagepool/selection_test.go
> fix ci for select msg test

- app/submodule/network/network_submodule.go
- go.mod
- pkg/messagepool/selection_test.go
> disable mplex stream muxer

- Makefile
- pkg/events/cache.go
- pkg/events/eventAPI.go
- pkg/events/events_test.go
> chain notify return error

- app/submodule/chain/miner_api.go
fix api result un-consensus with lotus:
- method:`StateMinerPreCommitDepositForPower`
- params:
`['f01578658', {'SealProof': 8, 'SectorNumber': 17661, 'SealedCID': {'/': 'bagboea4b5abcbejuhtmxfu4onwodjoexmm2nklwdbgh4kd55vatxfgbundz2ddia'}, 'SealRandEpoch': 1437643, 'DealIDs': [3218825], 'Expiration': 2992929, 'ReplaceCapacity': False, 'ReplaceSectorDeadline': 0, 'ReplaceSectorPartition': 0, 'ReplaceSectorNumber': 0}, [{'/': 'bafy2bzacea2bq6apooij7pqoxuef43vwcy4ins5m3homyq7fgons3g223yi6e'}, {'/': 'bafy2bzacea7pncy27vyk55lujkbukoro2ls22xvhblbbo4gc4uvikp42xdbsc'}]]`
- response :
`from lotus : 145614631696114499
from venus : 145614547699876820`
> fix:un-consensus api StateMinerPreCommitDepositForPower

- app/submodule/chain/chaininfo_api.go
- app/submodule/chain/miner_api.go
- app/submodule/mining/mining_api.go
- pkg/consensus/block_validator.go
- pkg/consensus/expected.go
- pkg/consensusfault/check.go
- pkg/fork/fork.go
- pkg/fork/mock.go
- pkg/gen/genesis/genesis.go
- pkg/gen/genesis/miners.go
- pkg/statemanger/call.go
- pkg/vm/dispatch/loader.go
- pkg/vm/runtime/runtime.go
- pkg/vm/vmcontext/invocation_context.go
- pkg/vm/vmcontext/runtime_adapter.go
- pkg/vm/vmcontext/syscalls.go
- pkg/vm/vmcontext/syscallsStateView.go
- pkg/vm/vmcontext/types.go
- pkg/vm/vmcontext/vmcontext.go
- tools/conformance/driver.go
- tools/gengen/util/generator.go
> remove the NtwkVersionGetter

- pkg/types/internal/fil.go
- pkg/types/internal/fil_test.go
support json marshal and unmarshal for type FIl.  maxfee become more clear in config.json
> fix json marshal/unmarshal for FIL type

- pkg/consensus/expected.go
- pkg/fork/fork.go
- pkg/gen/genesis/genesis.go
- pkg/gen/genesis/miners.go
- pkg/state/tree/state.go
- pkg/statemanger/call.go
- pkg/vm/vmcontext/types.go
- pkg/vm/vmcontext/vmcontext.go
- tools/conformance/driver.go
- tools/gengen/util/generator.go
> vm: fix network version not correct

- pkg/consensus/expected.go
- pkg/gen/genesis/genesis.go
- pkg/gen/genesis/miners.go
- pkg/statemanger/call.go
- pkg/vm/vmcontext/invocation_context.go
- pkg/vm/vmcontext/types.go
- pkg/vm/vmcontext/vmcontext.go
- tools/conformance/driver.go
- tools/gengen/util/generator.go
> No need to compare from address and to address

- pkg/wallet/dsbackend.go
> fix wallet unlock failed

- .github/workflows/baisc_checks.yml
- Makefile
- venus-shared/api/chain/v0/mock/full.go
- venus-shared/api/chain/v1/mock/full.go
- venus-shared/api/v0-api-document.md
- venus-shared/api/v1-api-document.md
add ci checks for:
- type compatible check
- api/mock api generation check
- api document generation check
> feat: add ci checks

- app/submodule/chain/chaininfo_api.go
- cmd/dispute.go
- pkg/chain/store.go
- pkg/chain/store_test.go
- pkg/chain/waiter.go
- pkg/events/events_test.go
- pkg/events/observer.go
- venus-devtool/api-gen/example.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/types/api_types.go
> fix: venus-shared: Change the type of HeadChange.Type

- venus-devtool/api-gen/example.go
- venus-shared/api/gateway/v1/market_event.go
- venus-shared/api/gateway/v1/proxy_gen.go
- venus-shared/types/gateway/market_event.go
- venus-shared/types/padded_byte.go
> type: venus-shared: add pad byte index

- pkg/migration/migrate.go
> feat: config: migrate maxfee

- venus-shared/types/market/assigner_type.go
- venus-shared/types/market/storage.go
no
- use `DealProposal` insde `specs-actors`, instead of `venus-shared/actors/builtin/market`
no
> fix: venus-shared: deal proposal usage

- venus-shared/api/gateway/v0/market_event.go
- venus-shared/api/gateway/v0/method.md
- venus-shared/api/gateway/v0/proof_event.go
- venus-shared/api/gateway/v0/proxy_gen.go
- venus-shared/api/gateway/v0/wallet_event.go
- venus-shared/api/gateway/v1/market_event.go
- venus-shared/api/gateway/v1/method.md
- venus-shared/api/gateway/v1/proof_event.go
- venus-shared/api/gateway/v1/proxy_gen.go
- venus-shared/api/gateway/v1/wallet_event.go
no
there are 2 role in `gateway` service, 
1. clients who just wish to use services.
2. clients wish to register itself to `gateway` for **providing** services
we want to split the `IxxxxEvent` interfaces into 2 part by above mentioned roles.
for 1st role, with name like: `IxxxClient`,
for 2nd role, with name like: `IxxxServiceProvider`.
this refactor makes the definition more clear on logical.
- `area`: _venus_, _venus-messager_, _venus-miner_, _venus-gateway_, _venus-auth_, _venus-market_, …
> refactor: venus-share: split-gateway-interfaces-by-role

- venus-shared/api/version.go
> chore: venus-shared: remove unused api version info

- .github/workflows/tag-workflow.yml
> ci: update git workflow

- pkg/vm/vmcontext/vmcontext.go
> sync: fix inconsistent circ supply at the same epoch

- pkg/messagepool/provider.go
GetActorAfter doesn't compute tipset state on needs.
> fix: api: GetActerAfter

- pkg/chainsync/types/target_tracker.go
make user tipst Do NOT include more than one blocks mined by a miner
> fix: make user tipst Do NOT include more than one blocks mined by a miner

- venus-shared/api/market/api.go
- venus-shared/api/market/method.md
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
`./venus-market storage-deals list`命令需要 列出订单时能够显示订单的piece state
`./venus-market storage-deals update` 命令需要能够更新订单的piece state
所以,需要将
`MarketListIncompleteDeals`,`MarketGetDealUpdates`,`UpdateStorageDealStatus`,
接口修改为:
MarketListIncompleteDeals(ctx context.Context, mAddr address.Address) ([]market.MinerDeal, error)      
MarketGetDealUpdates(ctx context.Context) (<-chan market.MinerDeal, error)       
UpdateStorageDealStatus(ctx context.Context, dealProposalCid cid.Cid, state storagemarket.StorageDealStatus, pieceState string) error
> refactor market api for UpdateDealPiecesStatus

- venus-devtool/api-gen/example.go
- venus-shared/api/market/api.go
- venus-shared/api/market/method.md
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
- venus-shared/types/market/assigner_type.go
- venus-shared/types/market/cbor_gen.go
- venus-shared/types/market/miner_deal.go
> new method for import published deal

- venus-shared/api/market/api.go
- venus-shared/api/market/method.md
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
更新AssignUnPackedDeals参数，在调用时传入sector id
> MarketAPI: improve AssignUnPackedDeals API

- app/submodule/chain/chaininfo_api.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
- venus-shared/types/api_types.go
> feat: api: add StateGetNetworkParmas

- venus-shared/api/market/method.md
- venus-shared/types/market/assigner_type.go
n/a
type changes for adding more policy in AssignedUnPackedDeals
> feat(venus-shared): more fields defined in market.GetDealSpec

- Makefile
- docker/venus-buildenv.dockerfile
- dockerfile
change to build docker image from local repo rather than from git chech out
pass env var BUILD_DOCKER_PROXY to docker when make image
change golang version of buildenv to 1.17
> fix: venus-venus: change to  build docker image from local repo 

- .github/workflows/baisc_checks.yml
- Makefile
- venus-devtool/bundle-gen/main.go
- venus-devtool/compatible/actors/render.go
- venus-devtool/go.mod
- venus-devtool/inline-gen/main.go
- venus-devtool/util/fmt.go
> fix: remove goimports

- app/submodule/chain/chaininfo_api.go
- cmd/state.go
- venus-devtool/api-gen/example.go
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
close: https://github.com/filecoin-project/venus/issues/4977
> feat: api: api call to get actors cids

- app/submodule/chain/beacon.go
- app/submodule/chain/chain_submodule.go
- app/submodule/chain/chaininfo_api.go
- cmd/state.go
- go.mod
- go.sum
- pkg/constants/version.go
- venus-devtool/api-gen/example.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/api/chain/v0/chain.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-checksum.txt
- venus-shared/compatible-checks/api-diff.txt
close: https://github.com/filecoin-project/venus/issues/4978
> build: build v1.6.0

- cmd/swarm_integration_test.go
- pkg/config/config_test.go
- pkg/repo/fskeystore/fskeystore_test.go
- pkg/repo/fsrepo_test.go
- pkg/repo/testing.go
A testing cleanup. 
This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
assert.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
https://pkg.go.dev/testing#T.TempDir
- `PR type`: _fix_, _feat_, _INTERFACE BREAKING …
> test: use `T.TempDir` to create temporary test directory

- app/submodule/syncer/syncer_api.go
- pkg/chainsync/dispatcher/dispatcher.go
- venus-shared/types/api_types.go
fix: correct the comments of some functions, would fix #5037
> fix: comments: correct the comments of some functions

- venus-shared/api/market/method.md
- venus-shared/types/market/assigner_type.go
> [venus-shared] 修改结构体以支持订单按生命周期筛选

- app/submodule/network/network_api.go
- pkg/net/network.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/network.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/network.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
> api: add NetDisconnect api

- bin/node_restart
- cmd/main.go
- cmd/main_daemon_test.go
- pkg/testhelpers/test_daemon.go
resolve: https://github.com/filecoin-project/venus/issues/4964
> fix: rename repodir to repo

- venus-shared/api/messager/api.go
- venus-shared/api/messager/method.md
- venus-shared/api/messager/mock/mock_imessager.go
- venus-shared/api/messager/proxy_gen.go
- venus-shared/types/messager/message.go
> refactor: refactor ReplaceMessage api

- dockerfile
fix https://github.com/filecoin-project/venus/issues/4999
update depence of ddl from base image
> fix #4999 :  venus : update depence of ddl from base image

- .github/workflows/tag-workflow.yml
only trigger auto publish on PR is merged
原因及方案说明: #5090
> chore: git action: only trigger auto publish on PR is merged

- cmd/cid.go
resolve: https://github.com/filecoin-project/venus/issues/4987
> cmd: print out actor code CIDs in manifest cid checker

- cmd/state.go
fix: cli: panic caused by `state power` cli if  power of miner not exist
would fixes https://github.com/filecoin-project/venus/issues/5016
> fix: panic caused by `state power` cli if  power of miner not exist

- cmd/daemon.go
> fix: load builtin actors earlier

- cmd/miner_actor.go
fix: command line: list miner control addresses get an error if owner/worker is robust(not account)
would fixes https://github.com/filecoin-project/venus/issues/5041
> fix: command line: list miner control addresses get an error if owner is multi-sig

- .github/pull_request_template.md
involve https://github.com/filecoin-project/venus/issues/4971
change PR template
> chore: change PR template

- .github/workflows/build_upload.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_docker_image.yml
- .github/workflows/docker_image.yml
fix https://github.com/filecoin-project/venus/pull/5169
> ci: fix missing secrets

- app/submodule/chain/miner_api.go
- pkg/vm/dispatch/loader.go
- pkg/vm/register/default.go
- venus-devtool/api-gen/example.go
- venus-devtool/api-gen/proxy.go
- venus-shared/api/chain/v1/chain.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/types/api_types.go
close #github.com/filecoin-project/venus#5181
> feat: 扩展更多的 `State***` 接口 / expand state apis

- pkg/messagepool/messagepool.go
fix: https://github.com/filecoin-project/venus/pull/5099
修复消息验证失败时，会全部分返回 [`pubsub.ValidationReject`](https://github.com/filecoin-project/venus/blob/master/app/submodule/mpool/mpool_submodule.go#L143)，导致peer被扣分
> fix: use %w to wrap error

- cmd/state.go
close https://github.com/filecoin-project/venus/issues/5297
> fix: 默认输出当前网络版本的actor cids / actor-cids cli command now defaults to current network version

- pkg/fork/fork.go
- pkg/fvm/fvm.go
- pkg/fvm/rand_wrapper.go
- pkg/gen/genesis/genesis.go
- pkg/gen/genesis/miners.go
增加两个环境变量：
1. VENUS_FVM_DEBUG_BUNDLE_V8 用于指定actor bundle 的位置
2. VENUS_FVM_DEVELOPER_DEBUG 开发人员用于debug fvm
lotus pr：https://github.com/filecoin-project/lotus/pull/8841
> feat: fvm增加debug功能 / FVM Debug Dual Execution

- app/submodule/mpool/mpool_api.go
- pkg/messagepool/gas.go
- pkg/statemanger/call.go
lotus pr：https://github.com/filecoin-project/lotus/pull/8991
> fix: gas: estimate gas with a zero base-fee

- pkg/consensus/expected.go
- pkg/consensus/processor.go
- pkg/fvm/fvm.go
- pkg/statemanger/call.go
- pkg/vm/gas/gas_tracker.go
- pkg/vm/vmcontext/types.go
- tools/conformance/driver.go
lotus pr：https://github.com/filecoin-project/lotus/pull/9036  https://github.com/filecoin-project/lotus/pull/9037
> feat: FVM: always enable tracing for user-triggered executions

- app/submodule/wallet/remotewallet/remote.go
- app/submodule/wallet/wallet_api.go
- cmd/address.go
- pkg/wallet/backend.go
- pkg/wallet/dsbackend.go
- pkg/wallet/dsbackend_test.go
- pkg/wallet/wallet.go
- pkg/wallet/wallet_test.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v0/wallet.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/api/chain/v1/wallet.go
- venus-shared/compatible-checks/api-diff.txt
> feat: add delete wallet address cmd / 删除钱包命令

- app/submodule/chain/miner_api.go
- cmd/miner.go
- cmd/miner_actor.go
- pkg/events/events_called.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/types/api_types.go
lotus pr: https://github.com/filecoin-project/lotus/pull/9296  https://github.com/filecoin-project/lotus/pull/9308  https://github.com/filecoin-project/lotus/pull/9326
> feat: print beneficiary info in state miner-info

- venus-shared/utils/method_map.go
> fix: add name for MethodMeta

- pkg/fork/fork.go
- pkg/util/blockstoreutil/autobatch.go
https://github.com/filecoin-project/lotus/pull/9518
> chore: migration: Use autobatch bs

- .github/workflows/test.yml
- Makefile
- tools/gengen/util/gengen_test.go
> chore: remove test duplicate package

- pkg/messagepool/messagepool.go
修复一个venus可能会崩溃的bug。
在通过地址删除 消息池消息时， 直接设置了`memset`为nil， 在这里：
https://github.com/filecoin-project/venus/blob/908a4af569caa3e3a8c427c9d576670de3e6d965/pkg/messagepool/messagepool.go#L564-L571
在后续， 如果有推送这个地址的消息时, 会间接调用：`getPendigMessage`， 返回值为：{nil, true, nil}， 最终，导致使用为nil的`memset`导致崩溃：
https://github.com/filecoin-project/venus/blob/908a4af569caa3e3a8c427c9d576670de3e6d965/pkg/messagepool/messagepool.go#L867-L891
> fix: message pool may panic caused by access a nil pointer

- venus-shared/api/market/api.go
- venus-shared/api/market/method.md
- venus-shared/api/market/mock/mock_imarket.go
- venus-shared/api/market/proxy_gen.go
https://github.com/filecoin-project/venus/issues/5410
> feat: Market attribute-related api add miner para

- cmd/daemon.go
- fixtures/networks/network_parse.go
- pkg/config/config.go
- pkg/migration/migrate.go
- pkg/migration/migrate_test.go
- pkg/repo/fsrepo.go
close https://github.com/filecoin-project/venus/issues/5491
`config.json` 中 `parameters`只保留`networkType`字段，其余字段将会被移除
```
"parameters": {
"networkType": 1
},
```
启动时增加日志输出：
```
network params: &{DevNet:false NetworkType:1 AddressNetwork:0 GenesisNetworkVersion:0 ConsensusMinerMinPower:10995116277760 MinVerifiedDealSize:1048576 ReplaceProofTypes:[3 4] BlockDelay:30 DrandSchedule:map[0:5 51000:1] ForkUpgradeParam:0xc00019e2c0 PreCommitChallengeDelay:150 PropagationDelaySecs:10}
upgrade params: &{UpgradeSmokeHeight:51000 UpgradeBreezeHeight:41280 UpgradeIgnitionHeight:94000 UpgradeLiftoffHeight:148888 UpgradeAssemblyHeight:138720 UpgradeRefuelHeight:130800 UpgradeTapeHeight:140760 UpgradeKumquatHeight:170000 UpgradePriceListOopsHeight:0 BreezeGasTampingDuration:120 UpgradeCalicoHeight:265200 …
```
> chore: ignore some fields in the parameters structure of the config.json

- venus-shared/actors/builtin_actors.go
- venus-shared/types/api_types.go
- venus-shared/utils/utils.go
close https://github.com/filecoin-project/venus/issues/5543
* forcenet 使用`testing` bundle 以支持创建32G矿工
* 在搭建forcenet网络时需要指定网络名 `./lotus-seed genesis new --network-name=forcenet localnet.json`，这样方便
venus 根据网络名来加载`testing` bundle
> fix: forcenet use testing bundle

- app/node/rpc.go
- app/submodule/config/config_test.go
- app/submodule/eth/eth_api.go
- venus-shared/api/chain/v1/eth.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/compatible-checks/api-perm.txt
- venus-shared/types/eth.go
- venus-shared/types/eth_test.go
https://github.com/filecoin-project/lotus/pull/9306
> feat: ethrpc: implement call, estimateGas, getTransactionCount

- app/node/builder.go
- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_submodule.go
- venus-devtool/api-gen/example.go
- venus-shared/api/chain/v1/eth.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/types/eth.go
- venus-shared/types/eth_test.go
- venus-shared/types/eth_transactions.go
https://github.com/filecoin-project/lotus/pull/9397
https://github.com/filecoin-project/lotus/pull/9511
https://github.com/filecoin-project/lotus/pull/9531
https://github.com/filecoin-project/lotus/pull/9532
> feat: implement eth_getCode and eth_getStorageAt

- pkg/crypto/crypto.go
- pkg/crypto/crypto_test.go
- pkg/crypto/delegated/init.go
- pkg/crypto/keyinfo.go
- pkg/gen/genesis/fevm.go
- pkg/wallet/dsbackend.go
- pkg/wallet/wallet_test.go
- venus-shared/types/eth.go
- venus-shared/utils/method_map.go
https://github.com/filecoin-project/lotus/pull/9886
> feat: Support creation and signing of Eth keys

- cmd/chain.go
- go.mod
- pkg/consensus/processor.go
- venus-devtool/cborgen/main.go
- venus-shared/types/cbor_gen.go
- venus-shared/types/event.go
- venus-shared/types/message_receipt.go
> feat: add evm cmds

- pkg/consensus/block_validator.go
- pkg/messagepool/messagepool.go
- pkg/messagepool/messagepool_test.go
- pkg/vm/register/default.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/actors/builtin/builtin.go
- venus-shared/actors/builtin/builtin.go.template
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/api/market/client/method.md
- venus-shared/api/market/method.md
- venus-shared/api/messager/method.md
- venus-shared/compatible-checks/actor-sources.txt
- venus-shared/compatible-checks/api-checksum.txt
- venus-shared/compatible-checks/api-diff.txt
- venus-shared/types/eth.go
- venus-shared/utils/method_map_test.go
https://github.com/filecoin-project/lotus/pull/9831
> chore: account abstraction

- pkg/fork/fork.go
resolve https://github.com/filecoin-project/venus/issues/5552
> feat: optionally set max migration workers

- go.mod
- go.sum
- pkg/consensusfault/check.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/internal/message.go
https://github.com/filecoin-project/lotus/pull/9515
> feat: future proof the from & to address protocols

- .github/workflows/common_build_upload.yml
> chore: build macos release

- fixtures/networks/network_parse.go
- venus-devtool/api-gen/example.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/api/gateway/v1/method.md
- venus-shared/api/gateway/v2/method.md
- venus-shared/api/market/client/method.md
- venus-shared/api/market/method.md
- venus-shared/api/messager/api.go
- venus-shared/api/messager/method.md
- venus-shared/api/messager/mock/mock_imessager.go
- venus-shared/api/messager/proxy_gen.go
- venus-shared/types/messager/actor_cfg.go
- venus-shared/types/messager/address.go
- venus-shared/types/messager/node.go
- venus-shared/types/messager/spec.go
- venus-shared/types/uuid.go
- venus-shared/utils/method_map.go
close https://github.com/filecoin-project/venus/issues/5558
> Feat/support method type fee cfg / 支持消息类型级别的费用配置

- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_event_api.go
- cmd/evm.go
- pkg/crypto/delegated/init.go
- pkg/statemanger/call.go
- pkg/wallet/key/keyinfo.go
- venus-devtool/api-gen/example.go
- venus-shared/types/eth.go
- venus-shared/types/eth_test.go
- venus-shared/types/eth_transactions.go
- venus-shared/types/eth_transactions_test.go
- venus-shared/types/message_receipt_test.go
- venus-shared/utils/utils_test.go
>  fix: use ToFilecoinAddress() to get f4 addr and validate v sig + cleanups

- app/submodule/chain/account_api.go
- app/submodule/chain/chaininfo_api.go
- app/submodule/eth/eth_api.go
- app/submodule/mining/mining_api.go
- app/submodule/wallet/wallet_api.go
- pkg/chain/store.go
- pkg/consensus/block_validator.go
- pkg/consensusfault/check.go
- pkg/fvm/fvm.go
- pkg/messagepool/gas.go
- pkg/messagepool/provider.go
- pkg/migration/migrate_test.go
- pkg/paychmgr/mock_test.go
- pkg/paychmgr/paych.go
- pkg/paychmgr/state.go
- pkg/state/power_table_view.go
- pkg/state/signer.go
- pkg/state/signer_test.go
- pkg/state/sigval.go
- pkg/state/testing.go
- pkg/state/view.go
- pkg/state/view_test.go
- pkg/statemanger/call.go
- pkg/statemanger/state_manger.go
- pkg/vm/vm.go
- pkg/vm/vmcontext/invocation_context.go
- pkg/vm/vmcontext/syscalls.go
- pkg/vm/vmcontext/syscallsStateView.go
- pkg/vm/vmcontext/types.go
lotus pr: https://github.com/filecoin-project/lotus/pull/10128
> feat: compute a better gas limit for recursive external contract calls

- fixtures/networks/butterfly.go
- fixtures/networks/calibration.go
- fixtures/networks/forcenet.go
- fixtures/networks/hyperspace.go
- fixtures/networks/integrationtestnet.go
- fixtures/networks/interopnet.go
- fixtures/networks/mainnet.go
- fixtures/networks/net_2k.go
- fixtures/networks/network_parse.go
- fixtures/networks/wallaby.go
- pkg/config/config.go
- pkg/migration/migrate.go
- pkg/migration/migrate_test.go
> fix: fix forcenet

- CHANGELOG.md
- pkg/constants/version.go
> chore: bump version to v1.10.0-rc3

- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
close https://github.com/filecoin-project/venus/issues/5761
- 移除 upgrade
- 升级 go-setup 版本到 v3 ,开启 go cache
> fix/ rm upgrade in github action / 移除 action 中系统软件的升级

- cmd/miner.go
- cmd/miner_proving.go
- cmd/state.go
- cmd/utils.go
close https://github.com/filecoin-project/venus/issues/5756
修复之后
```
./venus state sector t01158 3000
SectorNumber:  3000
SealProof:  8
SealedCID:  bagboea4b5abcbuo2sfywckvcizo7ue6fqik3tm33xkxn4kkxyi5njvfu4cgu2dig
DealIDs:  [37553]
Activation:  350559 (03 Mar 23 19:32 CST, 3 days 14 hours ago)
Expiration:  1904333 (24 Aug 24 07:39 CST, in 1 year 24 weeks)
DealWeight:  53387268123000832
VerifiedDealWeight:  0
InitialPledge:  0.99999998430674944 FIL
ExpectedDayReward:  2.116251967433802461 FIL
ExpectedStoragePledge:  38.764085861862301703 FIL
Deadline:  2
Partition:  0
```
> fix: block delay is 0

- app/submodule/eth/eth_api.go
- pkg/statemanger/state_manger.go
合并 lotus v1.20.0 到 v1.20.1 的修改
https://github.com/filecoin-project/lotus/compare/v1.20.0...v1.20.1
> fix: EthAPI: Make newEthBlockFromFilecoinTipSet faster and correct

- .github/workflows/test.yml
- pkg/chain/chain_index.go
- pkg/chain/chain_index_test.go
- pkg/chain/store_test.go
> feat: make chain tipset fetching 1000x faster

- Makefile
allow setting Go compiler with `GO`
> chore(make): allow setting Go compiler with `GO`

- venus-shared/api/market/v0/api.go
- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v0/mock/mock_imarket.go
- venus-shared/api/market/v0/proxy_gen.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
> opt: DealsImportData adds parameter skipCommP

- fixtures/networks/butterfly.go
- pkg/fork/fork.go
- pkg/gen/genesis/miners.go
- venus-shared/actors/builtin_actors_bundle.go
dep: #5901 
ref:  https://github.com/filecoin-project/lotus/pull/10629 https://github.com/filecoin-project/lotus/pull/10645 
- 更新了 ffi
- 添加 actor 升级 state 迁移的相关代码
> Feat/actor state migrate for nv19  / actor nv19 状态迁移

- pkg/messagepool/check.go
- pkg/messagepool/messagepool.go
- pkg/messagepool/repub.go
- pkg/messagepool/selection.go
> feat: message pool: change locks to RWMutexes for performance

- app/node/config.go
- app/node/init.go
- cmd/daemon.go
fix https://github.com/filecoin-project/venus/issues/5940
修复 `init` 的时候会在启动目录生成 `version` 文件
修复删除 `version` 启动失败
> fix: Fix generating version in the current directory

- venus-devtool/api-gen/example.go
- venus-shared/api/gateway/v2/market_event.go
- venus-shared/api/gateway/v2/method.md
- venus-shared/api/gateway/v2/mock/mock_igateway.go
- venus-shared/api/gateway/v2/proxy_gen.go
- venus-shared/types/gateway/market_event.go
ref https://github.com/filecoin-project/venus/issues/5975
> feat: add unseal state / 增加了 unseal 的状态类型

- venus-shared/api/chain/v1/eth.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-perm.txt
close https://github.com/filecoin-project/venus/issues/5960
> feat: downgrade perm for eth from write to read

- app/submodule/eth/eth_event_api.go
- venus-shared/actors/types/eth.go
close  https://github.com/filecoin-project/venus/issues/5962
> feat: verify eth filter's block index is in hex

- app/submodule/syncer/syncer_submodule.go
- pkg/chainsync/syncer/syncer_integration_test.go
- pkg/chainsync/syncer/syncer_test.go
- pkg/messagepool/messagepool_test.go
- pkg/statemanger/state_manger.go
close https://github.com/filecoin-project/venus/issues/5886
> feat: add ExecutionTrace cache

- pkg/chain/store.go
close https://github.com/filecoin-project/venus/issues/5973
> check if epoch is negative in GetTipsetByHeight()/ 检查epoch 是否是负数在GetTipsetByHeight()方法

- venus-shared/api/market/v0/api.go
- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v0/mock/mock_imarket.go
- venus-shared/api/market/v0/proxy_gen.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
https://github.com/filecoin-project/venus/issues/5943
> refactor: market: rename OfflineDealImport to DealsImport

- .github/dependabot.yml
- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
Updates GitHub Actions actions versions and configures dependabot to auto-update actions in the future. Related to https://filecoinproject.slack.com/archives/C03KLC57LKB/p1686680229440949
> chore: update github actions

- documentation/zh/sync.md
> [venus] add design doc of sync/添加同步设计文档

- cmd/fetch.go
close https://github.com/filecoin-project/venus/issues/6081
> opt: Adjust size flag to string type

- pkg/chain/store.go
这两处退出时没有取消订阅，这样会导致同步卡住：
https://github.com/filecoin-project/venus/blob/master/pkg/chain/store.go#L706 和 https://github.com/filecoin-project/venus/blob/master/pkg/chain/store.go#L713 
日志：
```
2023-08-16T17:22:30.357+0800	INFO	chain.store	chain/store.go:545	SetHead { bafy2bzacea6lern2svj7b56e37h43gijg5xde2kaufsqxe4yrf3x3cbdpyl6e } 3129045
2023-08-16T17:22:30.358+0800	INFO	chainsync.syncer	syncer/syncer.go:263	handle tipset height 3129045, count 1, took 0.1558(s)
2023-08-16T17:22:30.358+0800	ERROR	chain.store	chain/store.go:712	closing head change subscription due to slow reader
2023-08-16T17:38:00.227+0800	INFO	consensus	consensus/block_validator.go:142	block validation	{"took": 0.063988209, "height": "3129076", "block": "bafy2bzaceavo5dysax2deig4mpqxhbeqzgxfxi4v3t3swqbx3pcuvomnot4rs", …
```
> fix: Unsubscribe required on exit

- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_event_api.go
- pkg/events/events.go
close https://github.com/filecoin-project/venus/issues/6112
> set gcConfidence = 2 * constants.ForkLengthThreshold /  设置gcConfidence的值为2 * constants.ForkLengthThreshold

- app/submodule/syncer/syncer_api.go
- pkg/chainsync/chainsync.go
- pkg/chainsync/dispatcher/dispatcher.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v0/mock/mock_fullnode.go
- venus-shared/api/chain/v0/proxy_gen.go
- venus-shared/api/chain/v0/syncer.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/api/chain/v1/syncer.go
- venus-shared/compatible-checks/api-diff.txt
> feat: api: add SyncIncomingBlocks

- pkg/vm/vmcontext/execution.go
> chore: Output log when FVM_CONCURRENCY value is too large

- cmd/miner_proving.go
close https://github.com/filecoin-project/venus/issues/6122
> fix: Print only live sectors by default

- pkg/chainsync/dispatcher/dispatcher.go
- venus-devtool/api-gen/example.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/actors/builtin/market/state.sep.go.template
- venus-shared/actors/builtin/market/state.v0.go
- venus-shared/actors/builtin/market/state.v10.go
- venus-shared/actors/builtin/market/state.v11.go
- venus-shared/actors/builtin/market/state.v12.go
- venus-shared/actors/builtin/market/state.v2.go
- venus-shared/actors/builtin/market/state.v3.go
- venus-shared/actors/builtin/market/state.v4.go
- venus-shared/actors/builtin/market/state.v5.go
- venus-shared/actors/builtin/market/state.v6.go
- venus-shared/actors/builtin/market/state.v7.go
- venus-shared/actors/builtin/market/state.v8.go
- venus-shared/actors/builtin/market/state.v9.go
- venus-shared/actors/builtin/miner/actor.go
- venus-shared/actors/builtin/miner/actor.go.template
- venus-shared/actors/builtin/verifreg/actor.go
- venus-shared/actors/builtin/verifreg/actor.go.template
> chore: Use type proxies instead of versioned GST imports

- app/submodule/chain/chaininfo_api.go
- pkg/chain/store.go
- pkg/events/events_test.go
- pkg/messagepool/messagepool.go
lotus pr: https://github.com/filecoin-project/lotus/pull/11206
> fix: chain: cancel long operations upon ctx cancelation

- app/submodule/syncer/syncer_api.go
- app/submodule/syncer/syncer_submodule.go
- pkg/chainsync/chainsync.go
- pkg/chainsync/dispatcher/dispatcher.go
- pkg/chainsync/dispatcher/dispatcher_test.go
- pkg/chainsync/syncer/syncer_integration_test.go
- pkg/chainsync/syncer/syncer_test.go
- pkg/chainsync/types/target_tracker.go
- pkg/consensus/block_validator.go
- pkg/net/helloprotocol/hello_protocol.go
- pkg/net/helloprotocol/hello_protocol_test.go
- venus-shared/api/chain/v0/method.md
- venus-shared/api/chain/v1/method.md
- venus-shared/types/api_types.go
- venus-shared/types/chain_info.go
close https://github.com/filecoin-project/venus/issues/6147
> refactor: verify and save block messages when receive new bock

- app/submodule/network/network_submodule.go
close https://github.com/filecoin-project/venus/issues/6170
> fix: support exchange protocols

- CHANGELOG.md
- pkg/constants/version.go
> chore: bump version to v1.14.0-rc3

- venus-shared/api/market/v0/api.go
- venus-shared/api/market/v0/method.md
- venus-shared/api/market/v0/mock/mock_imarket.go
- venus-shared/api/market/v0/proxy_gen.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
- venus-shared/types/market/storage.go
https://github.com/ipfs-force-community/droplet/issues/462
> feat: import data by uuid

- CHANGELOG.md
- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump version & update changelog

- pkg/fork/fork.go
- pkg/fvm/fvm.go
https://github.com/filecoin-project/lotus/pull/11399
> fix: nv21fix migration: correctly upgrade system actor

- .circleci/config.yml
- .github/workflows/baisc_checks.yml
- .github/workflows/common_build_upload.yml
- .github/workflows/common_go.yml
- .github/workflows/test.yml
- pkg/messagepool/block_proba_test.go
- pkg/repo/fskeystore/fskeystore_test.go
- pkg/shardedmutex/shardedmutex_test.go
- pkg/util/fr32/fr32_test.go
- pkg/util/merge_peer_test.go
- tools/gengen/util/generator.go
- venus-shared/testutil/value_provider_primitive.go
- venus-shared/testutil/value_provider_primitive_test.go
> chore: ci: update go versin to v1.20

- .github/workflows/common_go.yml
close
messager test 打印日志过多，不利于查找错误的测试用例，调整 action 可以设置 ci 日志的级别
> chore: support update log level

- cmd/import.go
- pkg/chain/store.go
close https://github.com/filecoin-project/venus/issues/6232
> feat: chain import: don't walk to genesis

- cmd/state.go
close https://github.com/filecoin-project/venus/issues/6204
> chore: cmd: sort actor CIDs alphabetically before printing

- CHANGELOG.md
- pkg/constants/version.go
- pkg/net/exchange/client.go
- venus-devtool/cborgen/main.go
- venus-shared/libp2p/exchange/cbor_gen.go
- venus-shared/libp2p/exchange/exchange.go
- venus-shared/libp2p/exchange/protocol_encoding.go
close
lotus pr: https://github.com/filecoin-project/lotus/pull/11507
> Fix/patch release v1.14.2

- pkg/net/exchange/client.go
- venus-component/libp2p/exchange/client/client.go
`mi` 的类型是 `uint64`，当 `mi = math.MaxUint64` 时，`int(mi) = -1`，将会使下面代码检查失效，进而导致后续使用时出现数组越界问题（ https://github.com/filecoin-project/venus/blob/master/pkg/chainsync/syncer/syncer.go#L751 ）。
```
if int(mi) >= len(msgs.Bls) {
return fmt.Errorf("index in BlsIncludes (%d) exceeds number of messages (%d)",
mi, len(msgs.Bls))
}
```
> fix: index too large may out of range

- pkg/beacon/beacon.go
https://github.com/filecoin-project/lotus/pull/11598/files
> feat: drand: refactor round verification

- go.mod
- go.sum
- pkg/beacon/beacon.go
- pkg/beacon/drand.go
- pkg/beacon/drand_test.go
- pkg/beacon/mock.go
- pkg/config/beacon_config.go
- pkg/fork/fork.go
- pkg/testhelpers/test_daemon.go
- venus-devtool/go.mod
- venus-devtool/go.sum
https://github.com/filecoin-project/lotus/pull/11632/files
> chore: update deps and add drand test

- app/node/builder.go
- app/node/node.go
- app/node/rpc.go
- app/submodule/actorevent/actor_event.go
- app/submodule/actorevent/actor_event_module.go
- app/submodule/actorevent/actor_event_test.go
- app/submodule/actorevent/dummy.go
- app/submodule/eth/eth_event_api.go
- app/submodule/eth/eth_submodule.go
- app/submodule/eth/eth_test.go
- go.mod
- go.sum
- pkg/config/config.go
- pkg/events/filter/event.go
- pkg/events/filter/event_test.go
- pkg/events/filter/index.go
- pkg/events/filter/index_test.go
- venus-devtool/api-gen/example.go
- venus-devtool/go.mod
- venus-devtool/go.sum
- venus-shared/actors/types/eth.go
- venus-shared/api/chain/v1/actor_event.go
- venus-shared/api/chain/v1/fullnode.go
- venus-shared/api/chain/v1/method.md
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-checksum.txt
- venus-shared/types/actor_event.go
- venus-shared/types/actor_event_test.go
- venus-shared/types/event.go
…ctor events
https://github.com/filecoin-project/lotus/pull/11618/files
> feat: events: Add APIs to consume smart contract and built-in actor events

- venus-devtool/api-gen/example.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
- venus-shared/types/market/assigner_type.go
- venus-shared/types/market/storage.go
> feat: direct deal

- CHANGELOG.md
- go.mod
- go.sum
- pkg/constants/version.go
- venus-devtool/go.mod
- venus-devtool/go.sum
> chore: bump version to v1.15.0

- .github/workflows/test.yml
- CHANGELOG.md
- fixtures/networks/mainnet.go
- pkg/config/config.go
- pkg/constants/version.go
- pkg/events/filter/index.go
> chore: bump v1.15.1

- .github/workflows/common_go.yml
> chore: skip codecov error

- cmd/main.go
- pkg/beacon/beacon.go
- pkg/events/state/predicates.go
- pkg/messagepool/selection_test.go
- pkg/vm/vmcontext/vmcontext.go
- tools/conformance/driver.go
> chore: remove repetitive words

- pkg/chainsync/syncer/syncer.go
- pkg/consensus/block_validator.go
- pkg/market/fundmanager.go
- pkg/net/blocksub/validator.go
- pkg/net/exchange/client.go
- pkg/repo/fskeystore/fskeystore_test.go
- pkg/repo/fskeystore/memkeystore_test.go
- venus-component/libp2p/exchange/client/client.go
- venus-shared/types/tipset_marshal.go
> chore: fix some typos in comments

- app/submodule/chain/miner_api.go
- app/submodule/eth/eth_event_api.go
- pkg/chain/circulating_supply.go
> chore: fix function name in comment

- app/submodule/eth/eth_event_api.go
- pkg/events/filter/event.go
> fix(events): check for sync-in-progress

- pkg/net/exchange/peer_tracker.go
- pkg/net/exchange/protocol.go
- pkg/net/exchange/server.go
- pkg/net/helloprotocol/hello_protocol.go
> feat: libp2p: stream cleanup

- pkg/net/helloprotocol/hello_protocol.go
> fix: hello: avoid dialing when fetching hello tipset

- app/submodule/eth/eth_api.go
- pkg/statemanger/call.go
- venus-shared/actors/types/eth.go
- venus-shared/compatible-checks/api-diff.txt
> fix: ETH Call should use the parent state root of the subsequent tipset

- app/submodule/eth/eth_utils.go
- venus-shared/actors/types/eth.go
- venus-shared/types/eth.go
> feat: support safe param for eth_getBlockByNumber for 30 blocks

- pkg/events/filter/index.go
- pkg/messagepool/messagepool.go
- pkg/messagepool/selection.go
- pkg/vm/runtime/runtime.go
- pkg/wallet/dsbackend.go
- pkg/wallet/wallet.go
No
- Remove duplicate words in comments and error message.
> chore: remove duplicate words

- app/submodule/mpool/mpool_api.go
> fix: sanity check the to address of outgoing messages

- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
> feat: market api: update deal payload size

- app/node/builder.go
- app/submodule/mining/mining_submodule.go
- app/submodule/network/network_submodule.go
- go.mod
- go.sum
- pkg/net/pubsub/indexer_message.go
- pkg/net/pubsub/ratelimit/queue.go
- pkg/net/pubsub/ratelimit/queue_test.go
- pkg/net/pubsub/ratelimit/window.go
- pkg/net/pubsub/ratelimit/window_test.go
- venus-shared/api/market/v1/api.go
- venus-shared/api/market/v1/method.md
- venus-shared/api/market/v1/mock/mock_imarket.go
- venus-shared/api/market/v1/proxy_gen.go
> feat(market): add index provider api

- go.mod
- go.sum
- pkg/constants/version.go
> chore: bump version to v1.16.0

- pkg/chain/waiter.go
- pkg/clock/chainclock_test.go
- pkg/vm/runtime/runtime.go
- pkg/vm/vmcontext/vmcontext.go
> chore: fix some comments

- pkg/wallet/dsbackend.go
- tools/conformance/chaos/actor.go
> fix dsbackend lock

- app/node/builder.go
- app/node/node.go
- app/submodule/f3/f3_submodule.go
- app/submodule/wallet/wallet_submodule.go
- cmd/daemon.go
- cmd/main.go
- pkg/config/config.go
- pkg/vf3/ec.go
- pkg/vf3/f3.go
- pkg/vf3/signer.go
- pkg/wallet/gateway/wallet_gateway.go
- pkg/wallet/gateway/wallet_gateway_test.go
- pkg/wallet/wallet.go
- venus-shared/types/msg_meta.go
- venus-shared/types/wallet/sign_types.go
> feat: Use sophon gateway to sign f3 message

- fixtures/networks/integrationtestnet.go
- pkg/vf3/participation_lease.go
- venus-shared/types/api_types.go
> chore: disable f3 in integration test

- app/submodule/chain/chaininfo_api.go
- pkg/beacon/mock.go
- pkg/chain/randomness.go
- pkg/gen/genesis/miners.go
- pkg/vm/vmcontext/types.go
- tools/conformance/rand_fixed.go
- tools/conformance/rand_record.go
- tools/conformance/rand_replay.go
- venus-shared/api/chain/v1/chain.go
> fix: StateGetBeaconEntry uses chain beacons for historical epochs

- fixtures/networks/network_parse.go
- pkg/constants/env.go
- venus-shared/api/chain/v1/method.md
> feat: Disable f3 environment variables

- app/submodule/eth/dummy.go
- app/submodule/eth/eth_api.go
- venus-shared/api/chain/v1/eth.go
- venus-shared/api/chain/v1/mock/mock_fullnode.go
- venus-shared/api/chain/v1/proxy_gen.go
- venus-shared/compatible-checks/api-diff.txt
> feat: fix GetBlock for null rounds by returning nil

- pkg/vf3/f3.go
- pkg/vf3/participation_lease.go
https://github.com/filecoin-project/lotus/pull/12577
> fix: send the last gpbft message for each new participant

- venus-shared/actors/types/eth.go
- venus-shared/actors/types/eth_test.go
> fix: eth_getBlockReceipts should work similarly as geth

- pkg/chainsync/syncer/syncer.go
- pkg/statemanger/state_manger.go
> fix: rollback tipset

- pkg/util/ffiwrapper/impl/config.go
- pkg/vm/vmcontext/invocation_context.go
- venus-shared/actors/types/eth.go
close
修复评论中一些结构体的名称，借鉴自 https://github.com/filecoin-project/venus/pull/6380
已执行 `make api-gen `
```go
cd ./venus-devtool/ && go run ./api-gen/ client
cd ./venus-devtool/ && go run ./api-gen/ doc
not found method:  EthSubscription
cd ./venus-devtool/ && go run ./api-gen/ mock
```
> chore: fix struct name in comment

- cmd/main.go
- cmd/rpc.go
- pkg/repo/fsrepo.go
> feat: add rpc command

- app/submodule/chain/chain_submodule.go
- pkg/chain/store.go
- pkg/chain/store_test.go
- pkg/chainsync/syncer/syncer.go
> fix(sync): do not allow to expand checkpointed tipsets

- app/submodule/chain/chaininfo_api.go
- app/submodule/eth/eth_api.go
- app/submodule/eth/eth_utils.go
use errors.New to replace fmt.Errorf with no parameters
> chore: use errors.New to replace fmt.Errorf with no parameters

- cmd/miner_proving.go
- pkg/chainsync/syncer/syncer.go
> chore: miner prove dealines cmd add timestamp field
